/* UI for the persistent court ledger. All player speeches are reconstructed. */
function lcNotice(fn){try{fn();}catch(e){const el=document.getElementById('courtNotice');if(el)el.textContent=e.message;else alert(e.message);}}
function lcStatus(){const c=lcInit(world);return '<div class="court-budget"><span>'+Math.max(0,8-(c.spent[lcYear(world)]||0))+' court weeks available</span><span>'+c.purse+' household funds</span></div><p class="court-small">Court business uses a limited allowance within the current year. Travel continues as you decide cases. Spending also strains royal credit. Funds are abstract, not pounds.</p><p id="courtNotice" role="status"></p>';}
function lcOpen(){const c=lcInit(world),people=Object.keys(LC_PEOPLE).filter(id=>lcAlive(world,id));
 const pending=c.orders.filter(o=>o.status==='travelling');const meetings=c.audiences.filter(m=>m.status==='open');
 openSheet('The King’s Business','<div class="eyebrow">LIVING COURT · EXPERIMENTAL</div>'+lcStatus()+
 '<div class="court-tabs"><button id="courtCouncil">Royal Council</button><button id="courtLedger">Promises & correspondence</button></div>'+
 '<form id="courtForm"><label for="courtAction">Your initiative</label><select id="courtAction">'+Object.entries(LC_ACTIONS).map(([id,a])=>'<option value="'+id+'">'+E(a.name)+'</option>').join('')+'</select><label for="courtPerson">Whom do you approach?</label><select id="courtPerson">'+people.map(id=>'<option value="'+id+'">'+E(LC_PEOPLE[id].name)+'</option>').join('')+'</select><label for="courtPurpose">Purpose of the meeting</label><select id="courtPurpose"><option value="service">Service and commissions</option><option value="appointments">A disputed appointment</option><option value="settlement">A regional settlement</option><option value="confidence">Private confidence</option><option value="diplomacy">Diplomatic terms</option><option value="patronage">Household stipend</option><option value="land">A Crown demesne lease</option><option value="privilege">A safe-conduct privilege</option></select><p id="courtCost" class="court-small"></p><button class="court-primary" type="submit">Send my instructions</button></form>'+
 '<div class="eyebrow court-heading">READY TO BE HEARD</div>'+(meetings.map(m=>'<button class="court-row" data-audience="'+E(m.id)+'"><b>'+E(m.target?LC_PEOPLE[m.target].name:'The Royal Council')+'</b><span>'+E(m.topic)+' · '+(m.private?'private audience':'formal business')+'</span></button>').join('')||'<p class="court-small">No replies are waiting.</p>')+
 '<details class="reading-detail"><summary>Messengers on the road <span>'+pending.length+'</span></summary><div class="reading-detail-body">'+pending.map(o=>'<p>'+E(LC_ACTIONS[o.kind].name)+' · '+E(LC_PEOPLE[o.target]?.name||'Council')+' · at least '+Math.max(0,o.due-c.clock)+' court weeks</p>').join('')+'</div></details>');
 const kind=document.getElementById('courtAction'),target=document.getElementById('courtPerson'),purpose=document.getElementById('courtPurpose');
 function cost(){const a=LC_ACTIONS[kind.value];document.getElementById('courtCost').textContent=a.weeks+' court week(s) · '+a.cost+' funds · reply may be delayed, conditional or refused.';target.disabled=kind.value==='council';if(['mediate','intervene'].includes(kind.value))purpose.value='settlement';if(kind.value==='patronage')purpose.value='patronage';if(['diplomacy','alliance'].includes(kind.value))purpose.value='diplomacy';}kind.onchange=cost;cost();
 document.getElementById('courtForm').onsubmit=e=>{e.preventDefault();lcNotice(()=>{lcIssue(world,kind.value,target.value,purpose.value);lcOpen();});};
 document.getElementById('courtCouncil').onclick=lcCouncil;document.getElementById('courtLedger').onclick=lcLedger;
 sheet.querySelectorAll('[data-audience]').forEach(b=>b.onclick=()=>lcAudience(b.dataset.audience));
}
function lcAudience(id){const m=lcMeeting(world,id);if(!m)return lcOpen();const target=m.target;
 const buttons=m.kind==='council'?[['record','Let every dissent be entered. I reserve judgment.'],['delegate','My senior officer shall examine the terms.'],['dismiss','We shall meet again when there is more to consider.']]:[
 ...(!m.evidence?[['question','I will hear the witnesses and examine the warrants.']]:[]),['reassure','Your lawful service has not lost my regard.'],['threaten','You will answer for defiance of my commission.'],['promise','I pledge to hear your claim before another grant.'],['settle',m.topic==='patronage'?'I offer a stipend. Let disputed title be heard lawfully.':'I offer witnessed terms. Both households shall be heard.'],['dismiss','We shall speak again when there is more to consider.']];
 openSheet(target?LC_PEOPLE[target].name:'The Royal Council',lcStatus()+'<div class="eyebrow">'+E(m.private?'PRIVATE AUDIENCE':m.kind==='council'?'COUNCIL DELIBERATION':'FORMAL REPLY')+'</div><blockquote class="court-speech">“'+E(m.line)+'”</blockquote>'+(m.goal?'<p><b>What he seeks:</b> '+E(m.goal)+'</p>':'')+
 (m.views||[]).map(v=>'<div class="row"><b>'+E(LC_PEOPLE[v.id].name)+'</b><span>“'+E(v.text)+'”</span><small>'+E(v.info)+'</small></div>').join('')+
 (m.status==='open'?'<div class="court-responses">'+buttons.map(([move,text])=>'<button data-court-response="'+move+'">“'+E(text)+'”<small>'+E(move==='dismiss'?'End audience · no cost':move==='settle'?'1 week · 2 funds · assent is uncertain':move==='promise'?'1 week · fulfil through a witnessed settlement within 5 court weeks':'1 week')+'</small></button>').join('')+'</div>':'<p><b>This audience has ended.</b></p>')+
 '<details class="reading-detail"><summary>Earlier words & this audience</summary><div class="reading-detail-body">'+[...m.memories.map(x=>x.text),...m.transcript.map(x=>x.text)].map(t=>'<p>'+E(t)+'</p>').join('')+'</div></details><p class="court-small">All dialogue is fictional reconstruction. A hearing does not establish guilt or transfer disputed land.</p><button id="courtBack" class="court-primary">Return to royal business</button>');
 sheet.querySelectorAll('[data-court-response]').forEach(b=>b.onclick=()=>lcNotice(()=>{lcRespond(world,id,b.dataset.courtResponse);lcAudience(id);}));document.getElementById('courtBack').onclick=lcOpen;
}
function lcCouncil(){const members=lcMembers(world),c=lcInit(world);openSheet('The Royal Council',lcStatus()+'<p>Your officers and invited servants offer counsel through their own interests and connections. Removing an officer does not strip his hereditary lands or Church dignity.</p><button class="court-primary" id="conveneCouncil">Convene the Council · 1 week / 1 fund</button>'+
 Object.entries(LC_OFFICES).map(([office,title])=>'<div class="court-office"><h3>'+E(title)+'</h3><p>'+E(LC_PEOPLE[world.offices[office]]?.name||world.offices[office].replaceAll('_',' '))+'</p><label for="candidate-'+office+'">Eligible replacement</label><select id="candidate-'+office+'">'+Object.keys(LC_PEOPLE).filter(id=>lcAlive(world,id)&&LC_PEOPLE[id].offices.includes(office)).map(id=>'<option value="'+id+'">'+E(LC_PEOPLE[id].name)+'</option>').join('')+'</select><div class="court-tabs"><button data-appoint="'+office+'">Appoint · 1 week / 1 fund</button><button data-dismiss="'+office+'" '+(!LC_PEOPLE[world.offices[office]]?'disabled':'')+'>Dismiss · 1 week</button></div></div>').join('')+
 '<div class="eyebrow court-heading">PERSONAL COUNSEL</div>'+Object.keys(LC_PEOPLE).filter(id=>lcAlive(world,id)&&LC_PEOPLE[id].offices.length).map(id=>'<details class="reading-detail"><summary>'+E(LC_PEOPLE[id].name)+' <span>'+E(members.includes(id)?'in council':'outside council')+'</span></summary><div class="reading-detail-body"><p>'+E(LC_PEOPLE[id].goal)+'</p><p><b>Connections:</b> '+E(LC_PEOPLE[id].family)+'; '+E(LC_PEOPLE[id].kin.map(k=>LC_PEOPLE[k]?.name||k).join(', ')||'individual royal service')+'</p><p><b>Information:</b> '+E(LC_PEOPLE[id].info)+'</p>'+c.people[id].memory.slice(-2).map(m=>'<p>'+E(m.text)+'</p>').join('')+'<button data-seat="'+id+'" data-invite="'+(!members.includes(id))+'">'+(members.includes(id)?'Exclude from counsel':'Invite to counsel')+' · 1 week</button></div></details>').join('')+'<p class="court-small">Alternate appointments are gameplay developments. The office of Chancellor requires an experienced clerical administrator in this model. Documented battle deaths are not imposed on a reign where that battle never occurred.</p>');
 sheet.querySelectorAll('[data-appoint]').forEach(b=>b.onclick=()=>lcNotice(()=>{lcAppoint(world,b.dataset.appoint,document.getElementById('candidate-'+b.dataset.appoint).value);lcCouncil();}));sheet.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=()=>lcNotice(()=>{lcDismiss(world,b.dataset.dismiss);lcCouncil();}));sheet.querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>lcNotice(()=>{lcSeat(world,b.dataset.seat,b.dataset.invite==='true');lcCouncil();}));document.getElementById('conveneCouncil').onclick=()=>lcNotice(()=>{const id=lcIssue(world,'council',null,'appointments');lcAudience(id);});
}
function lcLedger(){const c=lcInit(world);openSheet('Words the Court Remembers','<div class="eyebrow">PROMISES · REPORTS · ROYAL ORDERS</div>'+c.promises.slice().reverse().map(p=>'<div class="row"><b>'+E(LC_PEOPLE[p.target]?.name)+' · '+E(p.status)+'</b><span>A hearing before another grant · '+E(p.topic)+(p.status==='open'?' · '+Math.max(0,p.due-c.clock)+' court weeks remain':'')+'</span></div>').join('')+'<details class="reading-detail" open><summary>Royal business <span>'+c.journal.length+' entries</span></summary><div class="reading-detail-body">'+c.journal.slice(-25).reverse().map(j=>'<div class="row"><b>'+E(j.year)+'</b><span>'+E(j.text)+'</span></div>').join('')+'</div></details><details class="reading-detail"><summary>The king’s spoken decisions <span>'+c.spoken.length+'</span></summary><div class="reading-detail-body">'+c.spoken.slice(-20).reverse().map(j=>'<p>'+E(j.year)+' · '+E(j.register)+'<br>“'+E(j.text)+'”</p>').join('')+'</div></details>');}
function lcInstall(){if(!current||!document.getElementById('card'))return;let bar=document.getElementById('courtAccess');if(!bar){bar=document.createElement('button');bar.id='courtAccess';bar.type='button';bar.className='court-access';bar.onclick=lcOpen;const anchor=document.getElementById('tapActions')||app.querySelector('.nav');if(anchor)anchor.before(bar);}
 const ready=lcInit(world).audiences.filter(m=>m.status==='open').length;if(bar)bar.textContent='♔ Royal Initiative'+(ready?' · '+ready+' replies':'');
 const source=arena?current[arena]:current;
 document.querySelectorAll('#tapActions [data-choice]').forEach(b=>{const side=b.dataset.choice;if(source?.[side])b.textContent='“'+lcVoice(source[side].label)+'”';});
 for(const side of ['left','right']){const chip=document.getElementById(side==='left'?'chipLeft':'chipRight');if(chip&&source?.[side])chip.textContent='“'+lcVoice(source[side].label)+'”';}
}
const _lcRender=renderCard;renderCard=function(){current=lcVoiceCard(current);_lcRender();lcInstall();};
const _lcReadRender=edwardReadingRender;edwardReadingRender=function(){_lcReadRender();lcInstall();};
const _lcCouncilArchive=showCouncil;showCouncil=lcCouncil;
const _lcCloseSheet=closeSheet;closeSheet=function(){_lcCloseSheet();lcInstall();};
const _lcMenu=edwardGameMenu;edwardGameMenu=function(){_lcMenu();const b=document.createElement('button');b.className='menu-choice';b.textContent='Royal Initiative & remembered promises';b.onclick=lcOpen;sheet.appendChild(b);};
window.EDWARD_COURT={open:lcOpen,council:lcCouncil,get state(){return lcInit(world);},issue:(kind,target,topic)=>lcIssue(world,kind,target,topic),respond:(id,move)=>lcRespond(world,id,move)};
