/* EDWARD: 40 authored historical-political situations, 1461–1464.
   The dialogue is fictionalized. Dates and historical anchors are separated in `record`.
   The engine decides what happens from facts, offices, relationships and knowledge. */
const CHAPTERS=[
 {id:'spring61',name:'Victory is not peace',date:'March–April 1461',limit:10},
 {id:'summer61',name:'A crown to govern',date:'June–September 1461',limit:11},
 {id:'autumn61',name:'The king and the law',date:'November 1461',limit:9},
 {id:'year62',name:'The unsettled North',date:'1462',limit:12},
 {id:'year63',name:'The cost of reconciliation',date:'1463',limit:10},
 {id:'year64',name:'A marriage and a kingdom',date:'1464',limit:11}
];
const HIST={
 towton:['29 March 1461: Towton was a decisive Yorkist victory. Edward had been proclaimed king earlier that March.','https://www.westminster-abbey.org/abbey-commemorations/royals/edward-iv'],
 crown:['Edward IV was crowned at Westminster on 28 June 1461.','https://www.westminster-abbey.org/abbey-commemorations/royals/edward-iv'],
 north:['Lancastrian resistance persisted in northern England after Towton, supported by Scottish connections.','https://www.english-heritage.org.uk/visit/places/warkworth-castle-and-hermitage/history/'],
 office:['Warwick and his Neville kin were major figures in Edward IV’s early regime; George Neville was Chancellor.','https://www.historyofparliamentonline.org/'],
 attainder:['The first Parliament of Edward IV met in November 1461 and attainted Lancastrian supporters.','https://www.british-history.ac.uk/no-series/parliament-rolls-medieval/november-1461'],
 paston:['The Paston Letters provide evidence of property disputes, patronage and the politics of late-medieval England.','https://www.bl.uk/collection-guides/paston-letters'],
 somerset:['Henry Beaufort, Duke of Somerset, received Edward IV’s pardon and was later restored to favour, before returning to Lancastrian resistance.','https://www.cambridge.org/core/books/abs/fifteenth-century-xiv/treatment-of-traitors-children-and-edward-ivs-clemency-in-the-1460s/8AA4ED257881366FA5127C3F633DF83B'],
 north64:['The battles of Hedgeley Moor and Hexham in 1464 helped break organized Lancastrian resistance in the North.','https://www.battlefieldstrust.com/'],
 marriage:['Edward IV secretly married Elizabeth Woodville on 1 May 1464; the marriage became publicly known later.','https://www.westminster-abbey.org/abbey-commemorations/royals/edward-iv'],
 politics:['The specific petition, private conversation and outcome are fictionalized, built around documented fifteenth-century institutions and pressures.','https://www.cambridge.org/core/books/wars-of-the-roses/']
};
const C=(label,effects={})=>({label,effects});
const I=(id,ch,who,role,where,when,quote,context,left,right,extra={})=>({id,ch,who,role,where,when,quote,context,left,right,priority:5,record:'politics',...extra});
const SITUATIONS=[
// 1461 spring
I('towton','spring61','Richard Neville','Earl of Warwick','Towton','29 March 1461',
 'The Lancastrian line has broken. The road north is open, but our men have fought all day in snow and mud.',
 'Henry VI and Margaret of Anjou remain free. Your victory has not yet settled their cause.',
 C('Pursue them north.',{facts:{pursuit:'ordered'},links:{warwick:1},records:['Warwick was sent in pursuit after Towton.']}),
 C('Hold the army together.',{facts:{pursuit:'restrained'},records:['Edward halted the pursuit to gather his army.']}),
 {priority:100,record:'towton',tag:'BATTLEFIELD'}),
I('prisoners','spring61','Sir William','Captain of the guard','Towton','March 1461',
 s=>s.facts.pursuit==='ordered'?'We have taken prisoners along the river. They slow the pursuit, and Warwick asks whether to press on.':'Men from the broken Lancastrian host have come forward to surrender. We cannot keep all of them under guard.',
 'Prisoners may become subjects again—or enemies whose families remember their treatment.',
 C('Take their surrender.',{facts:{prisoners:'accepted'},records:['Edward accepted the surrender of captured Lancastrians.'],precedents:['The king accepted surrender after Towton.']}),
 C('Let the captains decide.',{facts:{prisoners:'delegated'},links:{warwick:1},records:['Edward left the fate of prisoners to his captains.']}),
 {after:['towton'],priority:85,record:'towton',tag:'WAR'}),
I('young_knight','spring61','Thomas of Yorkshire','Lancastrian landholder (composite)','Yorkshire','April 1461',
 'My father served King Henry. I fought beside him. I will swear to you, Your Grace, if my family may remain upon its land.',
 'A Yorkist captain has already asked for the same estate as his reward.',
 C('Swear to me and keep your lands.',{facts:{first_pardon:true},links:{warwick:-1},obligations:[['thomas','edward','oath and restored lands','public']],precedents:['A defeated landholder kept his estate after swearing to Edward.'],records:['Edward restored a former enemy after receiving his oath.']}),
 C('The land is forfeit.',{facts:{first_pardon:false},links:{warwick:1},records:['A Lancastrian estate was granted away as a reward.']}),
 {after:['prisoners'],priority:82,tag:'PATRONAGE'}),
I('york_oath','spring61','Mayor of York','Civic magistrate','York','April 1461',
 'The city welcomes King Edward and prays that peace will return. Shall our oath be taken here, before the citizens?',
 'The city has received you. Public ceremony can also make a public commitment.',
 C('Let them swear before the city.',{facts:{york_oath:'public'},precedents:['York publicly renewed obedience to Edward.'],records:['York swore obedience before its citizens.']}),
 C('Their welcome is enough.',{facts:{york_oath:'informal'},records:['Edward accepted York’s welcome without a new public oath.']}),
 {after:['towton'],priority:80,record:'north',tag:'RECOGNITION'}),
I('north_command','spring61','Richard Neville','Earl of Warwick','York','April 1461',
 'The northern castles are not quiet. Give me men and authority and I will secure the country in your name.',
 'Warwick has soldiers and local connections. Delegating power may also increase his independent influence.',
 C('Go north in my name.',{facts:{warwick_north:'broad'},offices:{northern_commission:'warwick'},links:{warwick:2},records:['Warwick received broad authority in the North.']}),
 C('Report to me before settling terms.',{facts:{warwick_north:'limited'},offices:{northern_commission:'warwick_limited'},links:{warwick:-1},records:['Edward limited Warwick’s northern commission.']}),
 {after:['york_oath'],priority:76,record:'north',tag:'DELEGATION',up:{title:'Ask the Chancellor',who:'George Neville',role:'Chancellor; Warwick’s brother',quote:'Authority can be delegated without granting lands or permanent offices. But a narrow commission may be slow in the North.',left:C('Permit submissions, reserve grants.',{facts:{warwick_north:'bounded'},offices:{northern_commission:'warwick_bounded'},links:{warwick:1},records:['Warwick could accept submissions but not make permanent grants.']}),right:C('Leave the terms with Warwick.',{facts:{warwick_north:'broad'},offices:{northern_commission:'warwick'},links:{warwick:2},records:['Warwick received a broad commission after Council advice.']})},down:{title:'Private instruction',who:'Warwick’s messenger',role:'Alone with Edward',quote:'A private restriction can remain between the two of you. Warwick may regard it as confidence—or later deny what was said.',left:C('Trust Warwick privately.',{facts:{warwick_north:'private'},links:{warwick:1},obligations:[['warwick','edward','private instructions about the North','private']],records:['Edward issued Warwick private instructions.']}),right:C('No private bargain.',{facts:{warwick_north:'limited'},records:['Edward refused an unwitnessed commission.']})}}),
I('first_messenger','spring61','A northern messenger','Rider from the border','York','April 1461',
 s=>s.facts.warwick_north==='broad'?'My lord Warwick has received the obedience of several gentlemen. They say his word is the King’s word.':'Northern gentlemen ask whose word will settle their property: the King’s in Westminster, or Warwick’s in the field?',
 'Authority travels more slowly than a mounted messenger; people must decide whom to trust.',
 C('Confirm the settlement publicly.',{facts:{northern_policy:'ratified'},precedents:['The Crown ratified a northern settlement made in its name.'],records:['Edward publicly confirmed the northern terms.']}),
 C('Require my seal on every grant.',{facts:{northern_policy:'reserved'},links:{warwick:-1},records:['Edward reserved permanent grants to the Great Seal.']}),
 {after:['north_command'],priority:74,record:'north',tag:'PRECEDENT'}),
// 1461 summer
I('coronation','summer61','Thomas Bourchier','Archbishop of Canterbury','Westminster Abbey','28 June 1461',
 'Today the realm sees you crowned. Tomorrow the men who helped win the crown will ask what their service has earned.',
 'A coronation gives public form to kingship. It does not distribute every office, estate and obligation.',
 C('Honour those who carried me here.',{facts:{reward_policy:'magnates'},links:{warwick:1},records:['Edward promised generous rewards to the men of Towton.']}),
 C('The Crown must keep its gifts.',{facts:{reward_policy:'crown'},records:['Edward reserved royal patronage for direct decision.']}),
 {priority:100,record:'crown',tag:'CORONATION'}),
I('chancellor','summer61','George Neville','Chancellor of England','Westminster','Summer 1461',
 'The Great Seal makes your decisions known throughout the realm. It must be clear whose instructions I am to obey.',
 'George Neville is Warwick’s brother. His office is royal; his family ties remain.',
 C('Keep the Seal close to Council.',{facts:{seal_policy:'council'},links:{warwick:1},records:['Edward relied on the Chancellor and Council to issue grants.']}),
 C('Bring disputed grants to me.',{facts:{seal_policy:'king'},records:['Edward required personal review of disputed grants.']}),
 {after:['coronation'],priority:87,record:'office',tag:'INSTITUTION'}),
I('hastings','summer61','William Hastings','Trusted household servant','Westminster','Summer 1461',
 'I have served your cause since before Towton. Give me charge of the household, and you will know who has your ear.',
 'The Chamberlain controls access to the king. Household government is political government.',
 C('Make Hastings Chamberlain.',{offices:{chamberlain:'hastings'},links:{hastings:2},facts:{hastings_promoted:true},records:['Hastings became Lord Chamberlain.']}),
 C('Give him service, not the office.',{offices:{chamberlain:'unassigned'},links:{hastings:-1},facts:{hastings_promoted:false},records:['Hastings remained a servant without the chamberlainship.']}),
 {after:['coronation'],priority:84,record:'office',tag:'HOUSEHOLD'}),
I('reward_claim','summer61','Sir Robert','Yorkist veteran (composite)','Westminster','Summer 1461',
 s=>s.facts.first_pardon?'The estate you restored to that Lancastrian was promised to me after Towton. Is a defeated man’s oath worth more than my service?':'The estate forfeited by a Lancastrian could support the men who won your crown. I ask you to remember my service.',
 'A reward for one man may dispossess another. Both will remember the answer.',
 C('Give him another grant.',{facts:{veteran_compensated:true},obligations:[['robert','edward','compensation for service','public']],records:['Edward compensated a disappointed Yorkist veteran.']}),
 C('My earlier decision stands.',{facts:{veteran_compensated:false},links:{warwick:-1},records:['Edward refused a veteran’s request for compensation.']}),
 {after:['hastings','young_knight'],priority:81,tag:'CONSEQUENCE'}),
I('warwick_grant','summer61','George Neville','Chancellor','Westminster','Summer 1461',
 s=>s.facts.warwick_north==='limited'?'Warwick has restored a northern lord to his castle, although your commission required approval. He says the district would otherwise have risen.':'Warwick has restored a northern lord to his castle in your name. The settlement is popular with his men, but the patent has not yet passed the Seal.',
 'The decision tests whether a successful agent may establish precedents without explicit royal consent.',
 C('Confirm Warwick’s settlement.',{facts:{warwick_grant:'confirmed'},links:{warwick:2},precedents:['Warwick’s northern settlement was confirmed after the fact.'],records:['Edward confirmed a grant made through Warwick.']}),
 C('No grant without my approval.',{facts:{warwick_grant:'rejected'},links:{warwick:-2},records:['Edward reversed Warwick’s northern grant.']}),
 {after:['chancellor','north_command'],priority:78,record:'office',tag:'ROYAL AUTHORITY',up:{title:'Hear the legal argument',who:'George Neville',role:'Chancellor',quote:'A limited commission would preserve the King’s right of grant. It may also make the northern lords fear every settlement can be undone.',left:C('Issue a bounded commission.',{facts:{warwick_grant:'bounded'},offices:{northern_commission:'warwick_bounded'},links:{warwick:1},records:['A bounded northern commission was issued under the Great Seal.']}),right:C('Confirm the existing grant.',{facts:{warwick_grant:'confirmed'},links:{warwick:2},records:['Edward ratified Warwick’s disputed settlement.']})}}),
I('warwick_reply','summer61','Richard Neville','Earl of Warwick','Westminster','Summer 1461',
 'If my word may be undone after men have submitted, I must know what authority I possess. Shall I wait for Westminster while the North burns?',
 'This grievance exists because Edward previously restricted or reversed Warwick’s authority.',
 C('Let him settle urgent submissions.',{facts:{warwick_reply:'compromise'},links:{warwick:1},records:['Edward restored limited discretion to Warwick.']}),
 C('He will await my seal.',{facts:{warwick_reply:'refused'},links:{warwick:-2},records:['Edward refused Warwick’s request for discretion.']}),
 {requires:s=>s.facts.warwick_grant==='rejected'||s.facts.warwick_north==='limited',after:['warwick_grant'],priority:83,tag:'RECURRING GRIEVANCE',down:{title:'Speak without witnesses',who:'Richard Neville',role:'Private audience',quote:'You may command me as king, Edward. But do not ask me to govern a border and then make a fool of me before the men I must govern.',left:C('Promise to consult him first.',{facts:{warwick_reply:'private_promise'},obligations:[['edward','warwick','consult before reversing northern grants','private']],links:{warwick:1},records:['Edward privately promised Warwick prior consultation.']}),right:C('The office is not his property.',{facts:{warwick_reply:'refused'},links:{warwick:-2},records:['Edward refused Warwick in private.']})}}),
I('wardship','summer61','A widow','Petitioner (composite)','Westminster','September 1461',
 'My husband died for Henry. His son is nine years old. Must the boy lose his inheritance because his father chose wrongly?',
 'Wardship gives custody, income and influence to whoever receives it.',
 C('Keep the heir under Crown wardship.',{facts:{wardship:'crown'},obligations:[['child_heir','edward','royal wardship','public']],records:['Edward took a defeated family’s heir into royal wardship.']}),
 C('Place him with a loyal household.',{facts:{wardship:'magnate'},links:{hastings:1},records:['Edward placed a Lancastrian heir with a trusted household.']}),
 {after:['coronation'],priority:65,record:'somerset',tag:'INHERITANCE'}),
// 1461 autumn
I('parliament','autumn61','George Neville','Chancellor','Westminster','4 November 1461',
 'Parliament is assembled. Victory in the field must now become a settlement in law.',
 'Acts of Parliament can formalize loyalty, forfeiture and royal authority, but those acts have consequences for families.',
 C('Let the Commons hear our case.',{facts:{parliament_style:'public'},records:['Edward framed the new settlement before Parliament.']}),
 C('Let Council prepare the terms.',{facts:{parliament_style:'council'},records:['Council prepared the terms of the new settlement.']}),
 {priority:100,record:'attainder',tag:'PARLIAMENT',up:{title:'Ask for legal scrutiny',who:'Parliamentary clerk',role:'Record and petition',quote:'An act may settle a title today while creating petitions for reversal tomorrow. We should name each estate and heir carefully.',left:C('Record every claim precisely.',{facts:{parliament_style:'careful'},precedents:['The attainder process reserved detailed examination of claims.'],records:['Edward required a more precise parliamentary record.']}),right:C('Proceed swiftly.',{facts:{parliament_style:'swift'},records:['Edward pushed Parliament toward rapid settlement.']})}}),
I('attainder','autumn61','A parliamentary clerk','Keeper of the roll','Westminster','November 1461',
 'The names of those who held to Henry are ready. Shall the bill take their lands and honours?',
 'Attainder punishes enemies but also transfers estates to men who expect to keep them.',
 C('Pass the attainders.',{facts:{attainders:'broad'},precedents:['Attainder was used broadly against Lancastrian adherents.'],records:['Parliament attainted prominent Lancastrian adherents.']}),
 C('Reserve some cases for petition.',{facts:{attainders:'reviewed'},precedents:['Some forfeitures were reserved for petition.'],records:['Edward reserved disputed attainders for review.']}),
 {after:['parliament'],priority:95,record:'attainder',tag:'LAW'}),
I('confiscated_estate','autumn61','Sir Robert','Yorkist veteran (composite)','Westminster','November 1461',
 s=>s.facts.veteran_compensated?'You granted me another reward, Your Grace. Now the forfeitures are settled, will the patent finally be sealed?':'I have waited since Towton. Now Parliament has acted, will you grant me the estate promised to men who served?',
 'Promises of land are expensive when other claimants still exist.',
 C('Seal the veteran’s grant.',{facts:{veteran_estate:'granted'},obligations:[['robert','edward','estate confirmed by grant','public']],records:['A Yorkist veteran received a sealed grant.']}),
 C('Review the competing claims.',{facts:{veteran_estate:'review'},records:['Edward delayed a veteran’s estate grant pending review.']}),
 {after:['attainder'],priority:82,tag:'PATRONAGE'}),
I('city_credit','autumn61','A London alderman','Merchant representative','London','November 1461',
 'Your officers seek a loan. London can advance money, but merchants require assurances that royal promises will be honoured.',
 'Trade and royal credit depend on confidence as much as coercion.',
 C('Issue a formal repayment warrant.',{facts:{london_credit:'warrant'},obligations:[['edward','london','repay merchant loan','public']],records:['Edward borrowed from London under a formal warrant.']}),
 C('Ask leading merchants privately.',{facts:{london_credit:'personal'},obligations:[['edward','merchants','personal credit obligation','private']],records:['Edward sought private merchant credit.']}),
 {after:['parliament'],priority:73,tag:'FINANCE',down:{title:'Private merchant audience',who:'A London alderman',role:'No councillors present',quote:'A private pledge may secure money quickly, but a merchant cannot present it openly as a claim upon the Crown.',left:C('Give a personal assurance.',{facts:{london_credit:'private_promise'},obligations:[['edward','london','private promise of repayment','private']],records:['Edward privately pledged repayment to London merchants.']}),right:C('Use the ordinary warrant.',{facts:{london_credit:'warrant'},records:['The merchant loan was placed under a public warrant.']})}}),
I('calais','autumn61','Richard Neville','Captain of Calais','Westminster','November 1461',
 'Calais guards our passage to the Continent. Its garrison must be paid, whatever quarrels occupy England.',
 'Warwick’s captaincy gives him military prestige and access to continental politics.',
 C('Fund the garrison through Warwick.',{facts:{calais_supply:'warwick'},links:{warwick:1},records:['Edward entrusted Calais supply to Warwick’s administration.']}),
 C('Send royal auditors with the funds.',{facts:{calais_supply:'audited'},links:{warwick:-1},records:['Edward attached royal auditors to Calais funding.']}),
 {after:['parliament'],priority:67,record:'office',tag:'CALAĪS'}),
I('writ_dispute','autumn61','A sheriff','County official (composite)','Westminster','November 1461',
 s=>s.facts.seal_policy==='king'?'Two men carry conflicting instructions. One bears a local lord’s letter; the other says he awaits your seal. Which shall I obey?':'The local lord says his authority is sufficient. The clerk says the warrant lacks the proper seal. Which word binds the county?',
 'Royal government depends on local officers who must decide which instructions are valid.',
 C('Only a sealed warrant binds him.',{facts:{writ_rule:'seal'},precedents:['A sheriff was instructed to require the Great Seal.'],records:['Edward insisted upon the formal warrant.']}),
 C('Accept a trusted lord’s letter.',{facts:{writ_rule:'affinity'},links:{warwick:1},records:['Edward permitted a trusted magnate’s instruction to suffice.']}),
 {after:['chancellor','parliament'],priority:69,tag:'INSTITUTION'}),
// 1462
I('scots_border','year62','A border captain','Northern officer (composite)','Newcastle','1462',
 'Men cross the border with letters and supplies for Henry. The Scots do not need to conquer England to keep your enemies alive.',
 'Henry VI and his household have connections in Scotland; border security is both war and diplomacy.',
 C('Strengthen the northern garrisons.',{facts:{border_policy:'fortify'},records:['Edward reinforced the northern frontier.']}),
 C('Send envoys as well as soldiers.',{facts:{border_policy:'parley'},records:['Edward opened a channel for border negotiation.']}),
 {priority:100,record:'north',tag:'BORDER'}),
I('castle_garrison','year62','Captain of Alnwick','Garrison officer (composite)','Northumberland','1462',
 'We can hold the castle with more men and supplies. Without them, we must depend upon the neighbouring lords.',
 'Northern fortresses could remain contested even after Edward’s victory.',
 C('Send royal stores and men.',{facts:{garrison:'royal'},records:['Edward sent royal resources to a northern garrison.']}),
 C('Ask local lords to provision it.',{facts:{garrison:'magnate'},links:{warwick:1},records:['Edward relied on local magnates to supply the garrison.']}),
 {after:['scots_border'],priority:88,record:'north',tag:'CASTLE'}),
I('border_truce','year62','A Scottish envoy','Messenger from the border','Newcastle','1462',
 'A pause in raids could spare both countries. But your enemies may use the same roads while our captains stand down.',
 'The envoy is a fictional composite; cross-border pressure and diplomacy are historically grounded.',
 C('Hear terms for a local truce.',{facts:{border_truce:'talks'},records:['Edward permitted exploratory border talks.']}),
 C('Keep the captains at readiness.',{facts:{border_truce:'rejected'},records:['Edward refused local truce discussions.']}),
 {after:['scots_border'],priority:67,record:'north',tag:'DIPLOMACY',up:{title:'Refer to Council',who:'George Neville',role:'Chancellor',quote:'A written truce needs witnesses and terms. Without them, every raid will become an argument over who broke the peace.',left:C('Negotiate written terms.',{facts:{border_truce:'written'},records:['Council drafted formal terms for a border truce.']}),right:C('Leave the matter to captains.',{facts:{border_truce:'captains'},records:['Border captains received discretion over a local truce.']})}}),
I('percy_return','year62','A Percy kinsman','Northern noble (composite)','York','1462',
 'My family has held these lands for generations. If we serve you, must every Percy name be treated as an enemy?',
 'The Percy affinity remains a major northern force even after defeat and forfeiture.',
 C('Accept service on sworn terms.',{facts:{percy_policy:'reconcile'},obligations:[['percy','edward','northern service after pardon','public']],records:['Edward offered a Percy kinsman conditional reconciliation.']}),
 C('Keep the forfeitures in place.',{facts:{percy_policy:'exclude'},records:['Edward maintained the Percy forfeitures.']}),
 {after:['scots_border'],priority:80,record:'north',tag:'NOBILITY'}),
I('percy_petition','year62','Sir Robert','Yorkist grantee (composite)','York','1462',
 s=>s.facts.percy_policy==='reconcile'?'You speak of returning Percy lands. Those lands were granted to men who stood by you. What shall we tell their sons?':'The Percys still have friends in the shires. My tenants ask whether your earlier grants can be trusted.',
 'Reconciliation can collide with the property rights created by victory.',
 C('Honour the Yorkist grant.',{facts:{percy_grants:'protected'},records:['Edward protected a Yorkist grantee against competing Percy claims.']}),
 C('Seek a divided settlement.',{facts:{percy_grants:'compromise'},precedents:['Edward attempted to divide a contested northern inheritance.'],records:['Edward ordered a negotiated settlement of Percy claims.']}),
 {after:['percy_return'],priority:77,tag:'OLD PROMISE',up:{title:'Order an inquest',who:'County jurors',role:'Inquiry into title',quote:'The witnesses disagree about rents, service and possession. The inquest may clarify the title, but not satisfy either family.',left:C('Wait for the finding.',{facts:{percy_grants:'inquest'},records:['Edward ordered an inquest into competing Percy claims.']}),right:C('Compensate both households.',{facts:{percy_grants:'compensation'},obligations:[['edward','grantees','compensation for divided lands','public']],records:['Edward offered compensation to both claimants.']})}}),
I('henry_scotland','year62','An English informant','Northern correspondent (composite)','Durham','1462',
 'Henry is still called king by men who have never seen him. His name travels farther than his household.',
 'Henry VI’s continuing claim gives scattered Lancastrian resistance a common symbol.',
 C('Offer pardon to those who leave him.',{facts:{henry_policy:'pardon'},precedents:['Edward offered pardon to defectors from Henry VI.'],records:['Edward offered pardons to those abandoning Henry VI.']}),
 C('Treat his adherents as rebels.',{facts:{henry_policy:'severe'},records:['Edward ordered a harder line against Henry’s adherents.']}),
 {after:['scots_border'],priority:75,record:'north',tag:'LEGITIMACY'}),
I('sanctuary','year62','An abbot','Religious superior (composite)','Durham','1462',
 'A man accused of carrying Lancastrian letters has sought sanctuary. My house asks that its liberties be respected.',
 'Church liberties and royal security may collide over one messenger.',
 C('Respect the sanctuary claim.',{facts:{sanctuary:'respected'},records:['Edward respected a sanctuary claim.']}),
 C('Demand an inquiry into his letters.',{facts:{sanctuary:'inquiry'},records:['Edward sought an inquiry into a suspected Lancastrian messenger.']}),
 {after:['henry_scotland'],requires:s=>s.facts.henry_policy==='pardon',priority:83,tag:'CHURCH',down:{title:'Speak to the abbot alone',who:'The abbot',role:'Private audience',quote:'If you protect our house today, I may be able to persuade the messenger to speak without force.',left:C('Give the abbot time.',{facts:{sanctuary:'negotiated'},records:['Edward entrusted a sanctuary dispute to the abbot.']}),right:C('No private understanding.',{facts:{sanctuary:'inquiry'},records:['Edward declined the abbot’s private mediation.']})}}),
// 1463
I('somerset_pardon','year63','Henry Beaufort','Duke of Somerset','Westminster','1463',
 'I fought for Henry. I cannot undo that. But I may serve you if you will receive me without dishonour.',
 'Somerset’s submission could weaken Lancaster, but his former enemies have been rewarded with confiscated property.',
 C('Receive him into the king’s peace.',{facts:{somerset:'pardoned'},obligations:[['somerset','edward','pardon and royal protection','public']],precedents:['Somerset was received into the king’s peace.'],records:['Edward pardoned Somerset.']}),
 C('He must remain outside the court.',{facts:{somerset:'excluded'},records:['Edward declined to restore Somerset to favour.']}),
 {priority:100,record:'somerset',tag:'RECONCILIATION',up:{title:'Consult Council',who:'George Neville',role:'Chancellor',quote:'A pardon is not the same as restoring every office or estate. We can admit his allegiance without overturning all forfeitures.',left:C('Pardon, but reserve the estates.',{facts:{somerset:'conditional'},precedents:['Somerset was pardoned on restricted terms.'],records:['Edward granted Somerset a conditional pardon.']}),right:C('Restore him to full favour.',{facts:{somerset:'pardoned'},obligations:[['somerset','edward','full reconciliation','public']],records:['Somerset was restored to royal favour.']})}}),
I('somerset_at_court','year63','William Hastings','Royal servant','Westminster','1463',
 s=>s.facts.somerset==='excluded'?'Somerset has not come to court. Yet his name is heard among northern men. Absence does not make a rival harmless.':'Somerset eats at your table now. The men who fought him are watching whom you choose to honour.',
 'Access to the king can signify acceptance more clearly than a legal document.',
 C('Make reconciliation visible.',{facts:{somerset_court:'public'},links:{hastings:-1},records:['Edward made the Somerset reconciliation visible at court.']}),
 C('Keep the arrangement discreet.',{facts:{somerset_court:'private'},records:['Edward kept Somerset’s position discreet.']}),
 {after:['somerset_pardon'],priority:89,record:'somerset',tag:'COURT'}),
I('dispossessed_yorkist','year63','Sir Robert','Yorkist grantee (composite)','Westminster','1463',
 s=>s.facts.somerset==='excluded'?'Men ask whether the Crown still intends to use forfeited estates to reward loyal service.':'The Duke of Somerset sits at your table. Shall those of us who took his lands now surrender them?',
 'Reconciliation may undo patronage promises made after Towton.',
 C('Protect the existing grants.',{facts:{somerset_estates:'grantees'},records:['Edward protected grants made from Somerset’s forfeited lands.']}),
 C('Arrange compensation and review.',{facts:{somerset_estates:'review'},obligations:[['edward','grantees','compensation for contested estates','public']],records:['Edward opened review of contested Somerset estates.']}),
 {after:['somerset_pardon'],priority:84,tag:'CONSEQUENCE'}),
I('french_match','year63','Richard Neville','Earl of Warwick','Westminster','1463',
 'France might be brought to terms. A marriage can accomplish what armies cannot. Let me sound out the court.',
 'Warwick’s diplomatic influence creates a second kind of delegated authority.',
 C('Let Warwick explore a French match.',{facts:{warwick_diplomacy:'french'},links:{warwick:2},records:['Edward authorized Warwick to explore a French marriage.']}),
 C('Keep marriage negotiations open.',{facts:{warwick_diplomacy:'open'},links:{warwick:-1},records:['Edward declined to commit marriage diplomacy to Warwick.']}),
 {after:['somerset_pardon'],priority:80,record:'office',tag:'DIPLOMACY'}),
I('burgundy_trade','year63','A merchant of Calais','Continental trader (composite)','Calais','1463',
 'The Burgundian markets matter to English cloth. What you say in France is heard in Bruges.',
 'Foreign policy affects merchants and the supply of a garrison as well as dynastic marriage.',
 C('Keep the Burgundian channel open.',{facts:{burgundy_policy:'open'},records:['Edward maintained contacts with Burgundian merchants.']}),
 C('Put the French approach first.',{facts:{burgundy_policy:'cool'},links:{warwick:1},records:['Edward prioritized a French diplomatic approach.']}),
 {after:['french_match'],requires:s=>s.facts.warwick_diplomacy==='open',priority:86,tag:'TRADE'}),
I('unpaid_retinue','year63','A northern captain','Military officer (composite)','York','1463',
 s=>s.facts.london_credit==='warrant'?'Your London warrant is respected, but the men at the border still await payment.':'Our men are owed wages. Promises made in Westminster do not feed horses in Northumberland.',
 'Armies are maintained through credit, grants, captains and local resources.',
 C('Give the captain a royal warrant.',{facts:{retinue_pay:'warrant'},obligations:[['edward','northern_captain','wages due','public']],records:['Edward issued a warrant for unpaid northern soldiers.']}),
 C('Ask local lords to advance the money.',{facts:{retinue_pay:'magnates'},links:{warwick:1},records:['Edward relied on local lords to advance soldiers’ pay.']}),
 {after:['somerset_pardon'],priority:73,tag:'WAR FINANCE'}),
I('percy_unrest','year63','A northern sheriff','County officer (composite)','York','1463',
 s=>s.facts.percy_policy==='reconcile'?'A Percy retainer invokes the oath you accepted last year. He says the sheriff may not arrest him without a hearing.':'A Percy retainer claims that the old house will return. Men wait to see whose title the King will protect.',
 'The meaning of a past pardon changes when a local official must enforce it.',
 C('Hear the retainer’s claim.',{facts:{percy_enforcement:'hearing'},records:['Edward ordered a hearing into a Percy retainer’s claim.']}),
 C('Support the sheriff’s authority.',{facts:{percy_enforcement:'sheriff'},records:['Edward backed the sheriff against a Percy retainer.']}),
 {after:['percy_return'],priority:77,tag:'PRECEDENT RETURNS'}),
// 1464
I('somerset_defection','year64','John Neville','Lord Montagu','Northumberland','Early 1464',
 s=>s.facts.somerset_1464==='stays'?'Somerset has kept his oath and remains near your court. But other Lancastrian captains have raised men in the North.':s.facts.somerset==='excluded'?'Lancastrian captains have gathered again. Somerset remains among your enemies, as before.':'Somerset has returned to the Lancastrian cause. Men who heard your pardon now ask whether his oath ever meant anything.',
 'The renewed northern campaign is a historical pressure; the personal meaning depends on whether Edward pardoned Somerset.',
 C('Offer terms to lesser adherents.',{facts:{northern_1464:'terms'},records:['Edward distinguished lesser Lancastrian adherents from their leaders.']}),
 C('Prepare to defeat the rising.',{facts:{northern_1464:'force'},records:['Edward ordered preparations against the northern rising.']}),
 {priority:100,record:'somerset',tag:'RETURNING CONSEQUENCE'}),
I('hedgeley','year64','John Neville','Lord Montagu','Northumberland','25 April 1464',
 'The rebels have taken the field. If I am to meet them, I need to know whether prisoners may be offered terms.',
 'Hedgeley Moor was fought in April 1464. Edward’s specific instructions here are dramatized.',
 C('Let Montagu offer surrender.',{facts:{montagu_terms:'offered'},links:{montagu:1},records:['Montagu was authorized to offer surrender before battle.']}),
 C('Tell him to break the force.',{facts:{montagu_terms:'hard'},links:{montagu:1},records:['Montagu was ordered to press the northern campaign.']}),
 {after:['somerset_defection'],priority:95,record:'north64',tag:'BATTLEFIELD'}),
I('hexham','year64','John Neville','Lord Montagu','Northumberland','15 May 1464',
 'The Lancastrian host has been beaten. The prisoners include men whose families you have already dealt with.',
 'Hexham followed Hedgeley Moor. Its aftermath brings Edward’s earlier mercy and forfeitures back into question.',
 C('Distinguish the leaders from their men.',{facts:{hexham_policy:'selective'},precedents:['After Hexham, Edward distinguished leaders from lesser adherents.'],records:['Edward ordered selective treatment of Hexham prisoners.']}),
 C('Enforce the penalties of rebellion.',{facts:{hexham_policy:'strict'},records:['Edward ordered strict penalties after Hexham.']}),
 {after:['hedgeley'],priority:93,record:'north64',tag:'AFTERMATH'}),
I('elizabeth_petition','year64','Elizabeth Woodville','Widow of Sir John Grey','Near Grafton','Spring 1464',
 'My husband died fighting for Lancaster. My sons have a claim to their father’s inheritance. I ask the king to hear it.',
 'Elizabeth comes from an established, well-connected family. Marriage into royalty could greatly amplify that network.',
 C('Have the claim examined.',{facts:{elizabeth_audience:'formal'},records:['Edward referred Elizabeth Woodville’s petition for examination.']}),
 C('Hear her personally.',{facts:{elizabeth_audience:'personal'},links:{woodville:1},records:['Edward granted Elizabeth Woodville a personal audience.']}),
 {priority:89,record:'marriage',tag:'PERSONAL / POLITICAL',down:{title:'Private audience',who:'Elizabeth Woodville',role:'Widow and petitioner',quote:'I did not come to beg for a husband, Your Grace. I came because my sons must have a future.',left:C('Promise to examine her sons’ claims.',{facts:{elizabeth_audience:'promise'},obligations:[['edward','elizabeth','review her sons’ inheritance','private']],links:{woodville:1},records:['Edward privately promised to review the Grey inheritance.']}),right:C('Ask her to return to court.',{facts:{elizabeth_audience:'court'},links:{woodville:2},records:['Edward invited Elizabeth Woodville to court.']})}}),
I('marriage_diplomacy','year64','Richard Neville','Earl of Warwick','Westminster','Spring 1464',
 s=>s.facts.warwick_diplomacy==='french'?'I have sounded out France as you commanded. If the marriage is to serve the realm, I must know that your word still stands.':'A foreign marriage may steady the kingdom. France and Burgundy both watch what you intend.',
 'A marriage negotiation is also a promise made through an agent. Warwick’s reputation is involved.',
 C('Continue the French approach.',{facts:{marriage_policy:'french'},links:{warwick:1},records:['Edward continued the French marriage approach.']}),
 C('Leave every option open.',{facts:{marriage_policy:'open'},links:{warwick:-1},records:['Edward kept his marriage options open.']}),
 {priority:88,record:'marriage',tag:'DYNASTY',up:{title:'Hear the diplomatic costs',who:'George Neville',role:'Chancellor',quote:'An English match may secure a household. A foreign match may secure a treaty. Either choice will disappoint those who prepared the other.',left:C('Keep formal talks with France.',{facts:{marriage_policy:'french'},records:['Edward directed Council to continue French negotiations.']}),right:C('Suspend negotiations discreetly.',{facts:{marriage_policy:'suspended'},links:{warwick:-1},records:['Edward suspended marriage diplomacy.']})}}),
I('marriage_choice','year64','William Hastings','Royal household','Westminster','May 1464',
 s=>s.facts.elizabeth_audience==='personal'||s.facts.elizabeth_audience==='court'?'Your Grace has seen the widow Woodville. Warwick speaks of France. They cannot both be the future of your marriage.':'Warwick asks for an answer about France. At court, there is also talk of Elizabeth Woodville and the Grey inheritance.',
 'Historically Edward married Elizabeth Woodville secretly on 1 May 1464. Here, history supplies the possibility, not the compulsory result.',
 C('Marry Elizabeth Woodville.',{facts:{marriage:'elizabeth',marriage_secret:true},links:{woodville:3,warwick:-2},obligations:[['edward','elizabeth','marriage and protection','private']],records:['Edward married Elizabeth Woodville in private.']}),
 C('Pursue a diplomatic marriage.',{facts:{marriage:'foreign',marriage_secret:false},links:{warwick:1},records:['Edward chose a foreign marriage policy instead.']}),
 {after:['elizabeth_petition','marriage_diplomacy'],priority:96,record:'marriage',tag:'THE KING’S CHOICE',down:{title:'A private decision',who:'Elizabeth Woodville',role:'Private conversation',quote:'A marriage made without Council can still bind the kingdom. But you must decide whether you will stand by it when everyone knows.',left:C('Marry her and keep it secret.',{facts:{marriage:'elizabeth',marriage_secret:true},links:{woodville:3,warwick:-2},obligations:[['edward','elizabeth','secret marriage','private']],records:['Edward secretly married Elizabeth Woodville.']}),right:C('Do not promise marriage.',{facts:{marriage:'unsettled',marriage_secret:false},records:['Edward refused a secret marriage and left succession unsettled.']})}}),
I('woodville_network','year64','William Hastings','Royal household','Westminster','Autumn 1464',
 s=>s.facts.marriage==='elizabeth'?'The queen’s brothers and sisters now have suitors. Men who never approached the Woodvilles before are seeking their favour. Warwick notices.':s.facts.marriage==='foreign'?'The Woodvilles remain a notable family, but the marriage negotiations have created a different circle of petitioners around the court.':'There is no queen. Families still press their claims, and Warwick asks whether the marriage question is settled.',
 'A family is a political network before and after royal marriage; access to the Crown changes the reach of that network.',
 C('Permit household patronage.',s=>({facts:{network_policy:'patronage'},links:s.facts.marriage==='elizabeth'?{woodville:2,hastings:-1}:{hastings:1},records:['Edward permitted a new circle of household patronage.']})),
 C('Require Council review of marriages.',s=>({facts:{network_policy:'review'},links:s.facts.marriage==='elizabeth'?{woodville:-1}:{},records:['Edward subjected major marriage arrangements to Council review.']})),
 {after:['marriage_choice'],priority:92,record:'marriage',tag:'POLITICAL GRAVITY',up:{title:'Bring the marriages to Council',who:'George Neville',role:'Chancellor',quote:'Every match binds two households. Review may restrain the queen’s kin, but it also gives councillors power over your family.',left:C('Record the alliances publicly.',{facts:{network_policy:'recorded'},records:['Edward required major marriage alliances to be recorded.']}),right:C('Leave them to the household.',s=>({facts:{network_policy:'patronage'},links:s.facts.marriage==='elizabeth'?{woodville:1}:{hastings:1},records:['Edward left household marriages to private negotiation.']}))}})
];
if(SITUATIONS.length!==40)throw new Error('Expected 40 authored situations; found '+SITUATIONS.length);
