/* EDWARD v0.9 — contingent storylets. All unnamed petitions and speeches are fictionalized.
   They are not assertions that these particular exchanges happened in 1461–1464. */
SITUATIONS.push(
// SPRING 1461: aftermath changes the people who can speak to the Crown
I('captains_prisoners','spring61','A captain of foot','Yorkist officer (composite)','Towton','April 1461',
 'Your Grace accepted their surrender. My men say they gave quarter while their brothers lay dead in the snow.',
 'The king’s public mercy has costs inside the victorious army.',
 C('Hear the captains in person.',{facts:{army_quarter:'heard'},obligations:[['edward','captains','hearing after Towton','public']],records:['Edward heard the grievance of the captains who accepted surrender.']}),
 C('The king’s peace stands.',{facts:{army_quarter:'affirmed'},precedents:['Quarter promised in the king’s name must be honoured.'],records:['Edward publicly upheld his promise of quarter.']}),
 {requires:s=>s.facts.prisoners==='accepted',after:['prisoners'],priority:103,tag:'THE PRICE OF QUARTER'}),
I('captains_dispute','spring61','A chaplain','Witness to a quarrel (composite)','York','April 1461',
 'Two captains have claimed the same prisoners. One says he was given the right to decide their fate.',
 'Delegating a decision did not remove responsibility for it.',
 C('Require a written account.',{facts:{captains_account:'ordered'},records:['Edward required his captains to account for their treatment of prisoners.']}),
 C('Leave the dispute to Warwick.',{facts:{captains_account:'warwick'},links:{warwick:1},records:['Warwick was left to settle the captains’ quarrel.']}),
 {requires:s=>s.facts.prisoners==='delegated',after:['prisoners'],priority:103,tag:'DELEGATED VIOLENCE'}),
I('restored_knight_surety','spring61','Thomas of Yorkshire','Landholder (composite)','York','April 1461',
 'My oath is yours. Yet Sir Robert says the land has already been promised to him. Shall I send my son to court as surety?',
 'The pardon did not settle the competing claims to the same estate.',
 C('Accept the son at court.',{facts:{thomas_son:'court'},obligations:[['thomas','edward','son placed at court','public']],records:['The restored knight sent his son into Edward’s household.']}),
 C('Require a public hearing.',{facts:{thomas_son:'hearing'},records:['Edward required both claimants to submit evidence.']}),
 {requires:s=>s.facts.first_pardon===true,after:['young_knight'],priority:102,tag:'TWO CLAIMS'}),
I('forfeited_knight_family','spring61','A widow from Yorkshire','Petitioner (composite)','York','April 1461',
 'My husband is dead, my son is twelve, and the captain says our home belongs to the Crown. Who will hear a widow?',
 'A forfeiture affects heirs and dependants who never held a sword.',
 C('Reserve the child’s maintenance.',{facts:{widow_maintenance:'reserved'},precedents:['Forfeiture did not automatically extinguish maintenance for a child.'],records:['Edward reserved support for a forfeited family’s child.']}),
 C('Refer the matter to the grantee.',{facts:{widow_maintenance:'grantee'},records:['The grantee was asked to provide for the forfeited family.']}),
 {requires:s=>s.facts.first_pardon===false,after:['young_knight'],priority:102,tag:'THE HEIRS'}),
I('warwick_early_grant','spring61','A northern steward','Warwick’s officer (composite)','York','April 1461',
 'My lord has promised protection to a household that surrendered. Their neighbours now say the promise is the King’s.',
 'Warwick has used the space created by his commission.',
 C('Ratify the protection.',{facts:{warwick_protection:'ratified'},links:{warwick:1},records:['Edward ratified Warwick’s local protection.']}),
 C('Demand the terms first.',{facts:{warwick_protection:'review'},links:{warwick:-1},records:['Edward demanded the terms of Warwick’s protection before ratification.']}),
 {requires:s=>s.facts.agent_north==='warwick_settlement',after:['north_command'],priority:107,tag:'AN AGENT ACTS'}),
I('north_waiting_family','spring61','A Northumberland messenger','Household intermediary (composite)','York','April 1461',
 'The household wishes to submit, but no one will promise that its castle will be safe until Westminster answers.',
 'Central review has made the terms uncertain.',
 C('Send a provisional safe-conduct.',{facts:{north_safeconduct:'sent'},records:['Edward offered provisional protection while reviewing the northern petition.']}),
 C('Let them wait for the Seal.',{facts:{north_safeconduct:'refused'},records:['Edward refused to promise protection before formal review.']}),
 {requires:s=>s.facts.agent_north==='petition_delayed',after:['north_command'],priority:107,tag:'A DELAYED OATH'}),
// SUMMER 1461: royal office and patronage compete
I('warwick_clients_royal','summer61','William Hastings','Royal servant','Westminster','Summer 1461',
 'The men Warwick settled in the North now call themselves his men as readily as yours. He has brought you peace, and they have brought him followers.',
 'Successful delegated authority can create a lasting personal network.',
 C('Confirm Warwick’s clients.',{facts:{client_policy:'confirm'},links:{warwick:2},records:['Edward confirmed grants negotiated through Warwick’s affinity.']}),
 C('Take their oaths directly.',{facts:{client_policy:'direct'},links:{hastings:1},records:['Edward required Warwick’s clients to swear directly to the Crown.']}),
 {requires:s=>s.facts.agent_north==='warwick_settlement',priority:105,tag:'WHOSE MEN?'}),
I('king_seal_queue','summer61','George Neville','Chancellor','Westminster','Summer 1461',
 'Three petitioners have waited weeks for your signature. None will take possession without a document he can show his neighbours.',
 'Personal oversight is credible only if Edward can actually process decisions.',
 C('Appoint a clerk to prepare warrants.',{facts:{warrant_clerk:'appointed'},records:['Edward appointed a clerk to prepare grants for royal approval.']}),
 C('Keep the review entirely personal.',{facts:{warrant_clerk:'none'},records:['Edward retained personal review of all contested grants.']}),
 {requires:s=>s.facts.seal_policy==='king'||s.facts.northern_policy==='reserved',priority:105,tag:'CROWN CAPACITY'}),
I('hastings_direct_access','summer61','William Hastings','Royal household','Westminster','Summer 1461',
 'Men you rewarded at Towton now come to me with their petitions. Shall I turn them away when the Chancellor is occupied?',
 'A trusted servant can become a new political gatekeeper.',
 C('Receive their petitions through Hastings.',{facts:{hastings_channel:'open'},links:{hastings:2},records:['Hastings was permitted to receive petitions for Edward.']}),
 C('Send them through the Chancellor.',{facts:{hastings_channel:'closed'},links:{george:1},records:['Edward directed Hastings to send petitions through chancery.']}),
 {requires:s=>s.offices.chamberlain==='hastings',after:['hastings'],priority:105,tag:'ACCESS'}),
I('neville_petition_routed','summer61','A chancery clerk','Clerk (composite)','Westminster','Summer 1461',
 'The Chancellor’s brother has sent a petition with instructions already written in the margin. Shall it be treated like any other?',
 'Kinship and office meet on the same piece of parchment.',
 C('Require an ordinary hearing.',{facts:{neville_petition:'ordinary'},links:{george:-1},records:['Edward required ordinary scrutiny of a Neville petition.']}),
 C('Trust the Chancellor’s judgment.',{facts:{neville_petition:'favoured'},links:{george:1},records:['Edward accepted the Chancellor’s handling of a Neville petition.']}),
 {requires:s=>s.facts.agent_chancery==='kin_preference',after:['chancellor'],priority:107,tag:'THE GREAT SEAL'}),
I('yorkist_reward_friction','summer61','Sir Robert','Yorkist veteran (composite)','Westminster','Summer 1461',
 'I was promised land. The king restored its former owner. Tell me whether service at Towton is worth less than a Lancastrian oath.',
 'An act of mercy creates a claim by someone who expected the opposite.',
 C('Offer Robert another grant.',{facts:{robert_compensation:'other'},obligations:[['edward','robert','alternative reward','public']],records:['Edward promised another reward to a displaced Yorkist.']}),
 C('Let the restoration stand.',{facts:{robert_compensation:'none'},records:['Edward upheld the restoration despite a Yorkist complaint.']}),
 {requires:s=>s.facts.first_pardon===true,after:['reward_claim'],priority:104,tag:'THE OTHER PROMISE'}),
I('ward_kinship','summer61','A guardian','Guardian (composite)','Westminster','September 1461',
 'The widow asks for her child to remain with her kin. Another household offers to pay handsomely for the wardship.',
 'Wardship can be care, income and political leverage at once.',
 C('Hear the mother’s kin.',{facts:{wardship_dispute:'kin'},records:['Edward ordered the mother’s kin to be heard in the wardship dispute.']}),
 C('Allow a supervised grant.',{facts:{wardship_dispute:'grant'},records:['Edward permitted a supervised wardship grant.']}),
 {requires:s=>s.visited.includes('wardship'),priority:99,tag:'THE CHILD AS PATRONAGE'}),
// AUTUMN 1461: formal acts create new interests
I('attainder_widow','autumn61','A widow of the attainted','Petitioner (composite)','Westminster','November 1461',
 'The act names my husband. It does not name my children. Yet the sheriff has taken everything.',
 'Parliamentary punishment becomes a practical problem in a local household.',
 C('Review the children’s provision.',{facts:{attainder_children:'review'},records:['Edward ordered provision for the children of an attainted man to be reviewed.']}),
 C('Apply the forfeiture strictly.',{facts:{attainder_children:'strict'},records:['Edward refused an exception to the forfeiture.']}),
 {requires:s=>s.visited.includes('attainder'),priority:107,tag:'AFTER PARLIAMENT'}),
I('parliamentary_exception','autumn61','A Commons spokesman','Parliamentary petitioner (composite)','Westminster','November 1461',
 'Your Grace asks the realm to recognise its new king. Some of those who swore to you now ask whether their old offences can be excepted.',
 'The reach of an attainder can be negotiated, but exceptions have witnesses.',
 C('Hear named exceptions.',{facts:{parliament_exceptions:'heard'},records:['Edward allowed petitions for exceptions to forfeiture.']}),
 C('Keep the settlement uniform.',{facts:{parliament_exceptions:'none'},records:['Edward declined to hear exceptions to the attainder.']}),
 {requires:s=>s.facts.first_pardon===true&&s.visited.includes('parliament'),priority:105,tag:'A LAW WITH EXCEPTIONS'}),
I('merchant_credit_rumour','autumn61','A London creditor','Merchant (composite)','London','November 1461',
 'I advanced money on the understanding that your officers would pay promptly. A clerk now says the payment must wait.',
 'Royal credit depends on whether earlier commitments survive the paperwork.',
 C('Pay the debt before new grants.',{facts:{credit_priority:'repay'},records:['Edward ordered an outstanding royal debt paid before new grants.']}),
 C('Ask the city for more time.',{facts:{credit_priority:'extend'},obligations:[['edward','london_creditors','extended royal credit','public']],records:['Edward asked London creditors to extend the Crown’s terms.']}),
 {requires:s=>s.facts.agent_credit==='payment_disputed',priority:108,tag:'ROYAL CREDIT'}),
I('sheriff_two_writs','autumn61','A county sheriff','Sheriff (composite)','Westminster','November 1461',
 'Two writs have reached me concerning the same manor. One bears a Neville clerk’s instructions; the other claims your own command.',
 'Conflicting administrative channels can create a local political crisis.',
 C('Suspend both writs.',{facts:{writ_collision:'suspended'},records:['Edward suspended conflicting writs pending investigation.']}),
 C('Enforce the later sealed writ.',{facts:{writ_collision:'sealed'},records:['Edward directed the sheriff to follow the later sealed writ.']}),
 {requires:s=>s.facts.agent_chancery==='kin_preference'&&s.facts.seal_policy==='king',priority:110,tag:'COMPETING ORDERS'}),
I('london_merchants_patron','autumn61','A London alderman','Merchant representative','London','November 1461',
 'Your officers have kept their promises. Some in the city would rather lend to the Crown directly than through a great lord.',
 'Reliable administration can build an alternative base of influence.',
 C('Receive a civic delegation.',{facts:{city_access:'direct'},records:['Edward opened a direct audience for London creditors.']}),
 C('Keep loans with the usual officers.',{facts:{city_access:'mediated'},records:['Edward left the handling of city credit with established officers.']}),
 {requires:s=>s.facts.agent_credit==='trust_earned',priority:105,tag:'A NEW CHANNEL'}),
I('northern_hearing_request','autumn61','A northern petitioner','Landholder (composite)','Westminster','November 1461',
 'The men who brought my oath to Warwick say it is settled. A clerk here says no settlement is valid until you confirm it.',
 'The king’s two channels of authority disagree.',
 C('Confirm the oath provisionally.',{facts:{northern_oath:'provisional'},records:['Edward provisionally confirmed a northern oath pending the final grant.']}),
 C('Hear Warwick’s officers first.',{facts:{northern_oath:'warwick_hearing'},records:['Edward called Warwick’s officers to explain their northern terms.']}),
 {requires:s=>s.facts.agent_north==='warwick_settlement'&&s.facts.northern_policy==='reserved',priority:109,tag:'A PROMISE IN TWO PLACES'}),
// 1462: local actors respond to the state of the North
I('percy_retainer_recruitment','year62','A Percy retainer','Northern gentleman (composite)','York','1462',
 'The house has been allowed back. Men who once hid their colours now gather openly at its hall.',
 'A pardon can restore not only an estate but the capacity to mobilise followers.',
 C('Require the men to swear to Edward.',{facts:{percy_retinue:'crown_oath'},records:['Edward required the Percy retinue to swear to the Crown.']}),
 C('Let the household answer for them.',{facts:{percy_retinue:'household'},records:['Edward allowed the Percy household to guarantee its followers.']}),
 {requires:s=>s.facts.agent_percy==='retinue_growing',priority:108,tag:'THE HOUSEHOLD RETURNS'}),
I('percy_dispossessed_followers','year62','A former Percy tenant','Tenant (composite)','York','1462',
 'The new grantee demands rent from men who paid the Percys all their lives. Two of my neighbours have left their fields.',
 'Forfeiture changes who collects income; it does not immediately change loyalties.',
 C('Investigate the rents.',{facts:{percy_rents:'investigate'},records:['Edward ordered inquiry into rents demanded by the new grantee.']}),
 C('Enforce the grantee’s title.',{facts:{percy_rents:'enforce'},records:['Edward supported the grantee’s claim to the rents.']}),
 {requires:s=>s.facts.agent_percy==='displaced_followers',priority:108,tag:'A HOUSE WITHOUT LAND'}),
I('border_report_conflict','year62','John Neville','Lord Montagu','Northumberland','1462',
 'One report says the garrison is starving; another says it is provisioning for a raid. I cannot confirm both.',
 'The king receives competing accounts, neither of which is omniscient.',
 C('Send a second messenger.',{facts:{border_intel:'verify'},records:['Edward sought independent confirmation of the border reports.']}),
 C('Reinforce immediately.',{facts:{border_intel:'reinforce'},records:['Edward sent reinforcements before the reports could be reconciled.']}),
 {requires:s=>s.facts.agent_border==='conflicting_reports',priority:109,tag:'WHO KNOWS?'}),
I('warwick_discretion_1462','year62','Richard Neville','Earl of Warwick','York','1462',
 'The northern gentlemen say they submitted to me under your commission. Shall I now tell them that Westminster will reconsider everything?',
 'An agent whose authority is narrowed can still command the loyalty of people he settled.',
 C('Let the earlier promises stand.',{facts:{warwick_1462:'ratify'},links:{warwick:1},records:['Edward ratified earlier northern promises made by Warwick.']}),
 C('Review each claim in Council.',{facts:{warwick_1462:'review'},links:{warwick:-1},records:['Edward reopened Warwick’s northern settlements for review.']}),
 {requires:s=>s.facts.agent_north==='warwick_settlement',priority:107,tag:'THE COST OF REVERSAL'}),
I('northern_delay_1462','year62','A northern sheriff','Sheriff (composite)','York','1462',
 'Three households are willing to submit, but none will bring its keys until it knows whether its old rights survive.',
 'Waiting for royal procedure has become an independent political fact.',
 C('Grant temporary protection.',{facts:{north_1462:'safeconduct'},records:['Edward issued temporary protection for undecided northern households.']}),
 C('Demand surrender first.',{facts:{north_1462:'unconditional'},records:['Edward required unconditional surrender before any protection.']}),
 {requires:s=>s.facts.agent_north==='petition_delayed',priority:107,tag:'AN UNANSWERED LETTER'}),
I('retinue_pay_dispute','year62','A garrison paymaster','Military officer (composite)','Northumberland','1462',
 'The men have remained at their posts. Their pay has not. Their captain asks whether he should dismiss them.',
 'Royal military authority depends on the practical ability to maintain service.',
 C('Borrow for the garrison.',{facts:{garrison_pay:'borrowed'},obligations:[['edward','creditors','garrison wage loan','public']],records:['Edward borrowed to pay the northern garrison.']}),
 C('Reduce the garrison.',{facts:{garrison_pay:'reduced'},records:['Edward reduced the garrison to meet available funds.']}),
 {requires:s=>s.facts.agent_garrison==='unpaid'&&s.facts.garrison==='royal',priority:109,tag:'UNPAID MEN'}),
// 1463: Somerset, rivals, sureties
I('somerset_contact_rumour','year63','William Hastings','Royal household','Westminster','1463',
 'A man from the North says Somerset has exchanged messages with an old Lancastrian companion. He did not see the letters.',
 'A rumour is a reason to inquire, not proof of treason.',
 C('Ask Somerset openly.',{facts:{somerset_inquiry:'open'},records:['Edward questioned Somerset openly about reported correspondence.']}),
 C('Watch the messenger instead.',{facts:{somerset_inquiry:'quiet'},records:['Edward ordered discreet observation of Somerset’s messenger.']}),
 {requires:s=>s.facts.agent_somerset==='old_contacts',priority:111,tag:'UNPROVEN INTELLIGENCE',down:{title:'Speak without witnesses',who:'Henry Beaufort',role:'Duke of Somerset',quote:'A man does not forget every person he knew before his pardon. Would you have me confess to friendship as treason?',left:C('Accept his explanation for now.',{facts:{somerset_inquiry:'private_trust'},records:['Edward accepted Somerset’s private explanation without a public accusation.']}),right:C('Require a personal surety.',{facts:{somerset_inquiry:'surety'},records:['Edward required Somerset to offer a personal surety.']})}}),
I('somerset_clients_claim','year63','A Yorkist grantee','Petitioner (composite)','Westminster','1463',
 'The duke’s old retainers are returning. They say his pardon gives them rights in estates I now hold.',
 'Restoring a leader may revive expectations throughout his affinity.',
 C('Separate his pardon from land claims.',{facts:{somerset_clients:'separated'},records:['Edward ruled that Somerset’s pardon did not itself restore his clients’ estates.']}),
 C('Hear the clients together.',{facts:{somerset_clients:'hearing'},records:['Edward heard the land claims of Somerset’s returning clients.']}),
 {requires:s=>s.facts.somerset==='pardoned',priority:108,tag:'A PARDON SPREADS'}),
I('somerset_outside_court','year63','A northern correspondent','Informant (composite)','Durham','1463',
 'Somerset has not received your pardon. His friends still send letters across the border, and the men who know them will not name them.',
 'Exclusion can preserve a rival network outside the court’s knowledge.',
 C('Offer terms through an intermediary.',{facts:{somerset_outreach:'terms'},records:['Edward offered renewed terms through an intermediary.']}),
 C('Leave him outside the peace.',{facts:{somerset_outreach:'refused'},records:['Edward refused further overtures to Somerset.']}),
 {requires:s=>s.facts.somerset==='excluded',priority:110,tag:'THE EXCLUDED MAGNATE'}),
I('hastings_petition_competition','year63','George Neville','Chancellor','Westminster','1463',
 'Your household receives petitions before they reach the Seal. Shall an usher decide which claim the Chancellor is allowed to see?',
 'Hastings’s new access challenges chancery’s procedural authority.',
 C('Require both offices to keep a register.',{facts:{petition_register:'joint'},records:['Edward ordered a common register for household and chancery petitions.']}),
 C('Leave Hastings to judge urgency.',{facts:{petition_register:'household'},links:{hastings:1},records:['Edward left urgent petitions in Hastings’s hands.']}),
 {requires:s=>s.facts.agent_hastings==='petition_circle',priority:109,tag:'TWO DOORS TO THE KING'}),
I('warwick_diplomatic_commitment','year63','Richard Neville','Earl of Warwick','Westminster','1463',
 'I have spoken in your name abroad. If you now change course, those who heard me will call my word empty.',
 'Diplomatic delegation creates a promise that cannot be recalled without a cost.',
 C('Confirm his instructions in writing.',{facts:{warwick_mission:'confirmed'},links:{warwick:1},records:['Edward confirmed Warwick’s diplomatic instructions.']}),
 C('Tell him no marriage is promised.',{facts:{warwick_mission:'limited'},links:{warwick:-1},records:['Edward limited the authority of Warwick’s marriage diplomacy.']}),
 {requires:s=>s.facts.warwick_diplomacy==='french'||s.facts.agent_warwick==='diplomatic_promise',priority:109,tag:'A WORD GIVEN ABROAD'}),
I('north_local_reconciliation','year63','A Northumberland parish priest','Local mediator (composite)','Northumberland','1463',
 'I have two sworn promises: neither household will raid the other before harvest. But both demand the same meadow rents. Three tenant families dare not bring their grain to market until you protect the road. Will you seal the truce before judging the deeds?',
 'NEW EVIDENCE: two sworn pledges and three households unable to trade. The truce can protect tenants now; deciding title may take months. This is a fictional local petition, not a documented medieval letter.',
 C('Seal the truce; hear the title later.',{facts:{local_truce:'confirmed',north_tenant_road:'protected'},delayed:[{id:'north-truce-harvest',delay:3,from:'A northern sheriff',text:'The sworn truce held through the harvest. Tenants have resumed market journeys, but rival rent collectors still dispute the meadow.'}],records:['Edward accepted sworn sureties for safe passage and reserved the meadow title for a later hearing.']}),
 C('Require deeds before confirming peace.',{facts:{local_truce:'postponed',north_tenant_road:'unprotected'},delayed:[{id:'north-truce-delay',delay:3,from:'The parish priest',text:'Neither household signed a truce without a land ruling. Tenants report that carts still avoid the contested road.'}],records:['Edward withheld ratification until both title deeds were examined; the tenants received no immediate protection.']}),
 {requires:s=>s.facts.agent_north==='warwick_settlement'||s.facts.agent_north==='petition_delayed',priority:105,tag:'THE MEADOW AND THE OATH'}),
// 1464: the state can generate a different outcome to the same pressures
I('somerset_kept_oath','year64','Henry Beaufort','Duke of Somerset','Westminster','Early 1464',
 'My old friends ask where I stand. I have taken your peace, and men will now judge whether I meant it.',
 'An alternate settlement changes who participates in the northern crisis.',
 C('Give Somerset a public role.',{facts:{somerset_public_role:'appointed'},records:['Edward gave the reconciled Somerset a public role in his regime.']}),
 C('Keep him close to the household.',{facts:{somerset_public_role:'court'},records:['Edward kept Somerset near court rather than giving him independent authority.']}),
 {requires:s=>s.facts.somerset_1464==='stays',priority:119,tag:'A DIFFERENT 1464'}),
I('somerset_breaks_oath','year64','A northern messenger','Correspondent (composite)','York','Early 1464',
 'A man once received into your peace has crossed back to your enemies. His friends say he was never safe at court.',
 'A broken reconciliation leaves both sides arguing about what the king promised.',
 C('Publish the terms of his pardon.',{facts:{somerset_public_terms:'published'},records:['Edward published the terms of Somerset’s former pardon.']}),
 C('Say nothing until the campaign ends.',{facts:{somerset_public_terms:'silent'},records:['Edward withheld public comment on Somerset’s broken settlement.']}),
 {requires:s=>s.facts.somerset_1464==='rebels'&&s.facts.somerset==='pardoned',priority:117,tag:'A FAILED EXPERIMENT'}),
I('woodville_family_petitions','year64','Jacquetta of Luxembourg','Duchess of Bedford','Westminster','Summer 1464',
 'Our family has friends and clients who knew us before my daughter spoke to you. They will not vanish if she does not become queen.',
 'The Woodville network existed before royal marriage and can pursue interests independently.',
 C('Hear the family’s existing claims.',{facts:{woodville_independent:'audience'},links:{woodville:1},records:['Edward received the Woodville family’s petitions without requiring a royal marriage.']}),
 C('Refer them through the usual channels.',{facts:{woodville_independent:'chancery'},records:['Edward referred the Woodville family to chancery.']}),
 {requires:s=>s.facts.marriage!=='elizabeth'&&s.visited.includes('marriage_choice'),priority:111,tag:'A FAMILY BEFORE A QUEEN'}),
I('queen_kin_arrangements','year64','A royal usher','Court officer (composite)','Westminster','Autumn 1464',
 'Three households seek introductions to the queen’s kin. None has asked the king directly.',
 'Access to the royal household has become a political asset.',
 C('Require disclosure of royal petitions.',{facts:{queen_kin_policy:'register'},records:['Edward ordered petitions through the queen’s kin to be recorded.']}),
 C('Let the queen’s household arrange them.',{facts:{queen_kin_policy:'private'},links:{woodville:1},records:['Edward allowed the queen’s household to manage its introductions.']}),
 {requires:s=>s.facts.marriage==='elizabeth'&&s.facts.agent_woodville==='kin_matches',priority:112,tag:'THE NEW ACCESS'}),
I('foreign_envoy_reaction','year64','A foreign envoy','Diplomatic representative (composite)','Westminster','Autumn 1464',
 'My masters have heard that your marriage intentions have changed. They ask whether their envoys negotiated with a king or only his servant.',
 'Foreign courts remember negotiations even when Edward has not made a final treaty.',
 C('Explain the change through Council.',{facts:{foreign_reply:'formal'},records:['Edward sent a formal explanation of the changed marriage policy.']}),
 C('Let Warwick answer privately.',{facts:{foreign_reply:'warwick'},links:{warwick:1},records:['Edward left Warwick to answer the foreign court.']}),
 {requires:s=>s.facts.agent_warwick==='diplomatic_promise'&&s.facts.marriage!=='foreign',priority:112,tag:'THE ENVOY REMEMBERS'}),
I('north_campaign_avoided','year64','John Neville','Lord Montagu','York','Spring 1464',
 'Some northern lords have submitted under the terms you offered. The danger is not ended, but there is no host before us today.',
 'This is a counterfactual branch: historical battles are not forced if the simulation has prevented the rising.',
 C('Confirm the negotiated peace.',{facts:{northern_1464:'settled'},records:['Edward confirmed a negotiated northern peace in this alternate reign.']}),
 C('Maintain troops until oaths are tested.',{facts:{northern_1464:'guarded'},records:['Edward kept forces ready despite the negotiated northern peace.']}),
 {requires:s=>s.facts.north_rising_1464==='averted',priority:122,tag:'THE BATTLE THAT DID NOT HAPPEN'}),
I('northern_king_in_person','year64','A northern sheriff','Sheriff (composite)','York','1464',
 'Your officers disagree about who may take submission. Some ask that you come north and hear them yourself.',
 'A king can resolve a delegation problem by travelling—but only at the cost of leaving other matters unattended.',
 C('Go north to hear the oaths.',{facts:{royal_progress:'north'},records:['Edward ordered a royal progress to hear northern submissions.']}),
 C('Send a commission of inquiry.',{facts:{royal_progress:'commission'},records:['Edward sent an inquiry instead of travelling north.']}),
 {requires:s=>s.facts.agent_north==='petition_delayed',priority:109,tag:'ROYAL PRESENCE'})
);
