/* EDWARD — historical-world guardrail and provenance lens.
   Documentary chronology is never silently inserted into the player's alternate reign.
   Events and speeches not explicitly documented remain marked reconstructed. */
const EDWARD_HISTORY_ANCHORS=[
 {year:1461,title:'Edward takes the crown · Towton',record:'Edward was proclaimed king on 4 March 1461; the Battle of Towton followed on 29 March. The battle consolidated, rather than preceded, his claim.',source:'https://www.nationalarchives.gov.uk/explore-the-collection/explore-by-time-period/medieval/the-wars-of-the-roses/',status:s=>'The campaign of 1461 forms the opening setting. Your subsequent settlements can diverge.'},
 {year:1464,title:'Edward and Elizabeth Woodville',record:'Edward IV married Elizabeth Woodville privately in 1464; the marriage became public later that year.',source:'https://www.royal.uk/edward-iv',status:s=>s.facts.marriage==='elizabeth'?'In this reign Edward chose Elizabeth Woodville.':'This reign has not followed the recorded Woodville marriage.'},
 {year:1465,title:'Henry VI taken into custody',record:'Henry VI was imprisoned in the Tower from June 1465 until October 1470, then imprisoned again in 1471.',source:'https://www.hrp.org.uk/tower-of-london/history-and-stories/henry-vi/',status:s=>s.sandbox?.narrative?.seen?.captive?(s.facts.north_rising_1464==='averted'?'The alternate northern settlement changed how Henry is pursued.':'The custody question reached Edward’s court.'):'This is a historical reference point, not an event the simulation assumes occurred.'},
 {year:1467,title:'The Great Seal and George Neville',record:'Edward dismissed George Neville as Lord Chancellor in June 1467 while Warwick was abroad. In an alternate reign this removal is a political choice, not a mandatory event.',source:'https://en.wikisource.org/wiki/Dictionary_of_National_Biography%2C_1885-1900/Neville%2C_George_%281433%3F-1476%29',status:s=>s.offices.chancellor==='george'?'George Neville still holds the Great Seal in this alternate reign.':'The office has passed out of George Neville’s hands in this reign.'},
 {year:1469,title:'Caister and the Pastons',record:'In 1469 the Duke of Norfolk besieged Caister Castle and took it after six weeks. The Paston letters preserve the family’s side of the dispute.',source:'https://historicengland.org.uk/listing/the-list/list-entry/1002882',status:s=>{const f=s.sandbox?.story?.flags||{};return f.caisterPeace==='prevented'?'In this alternate reign an earlier commission prevented an emergency siege.':f.caisterPeace==='abandoned'?'Royal intervention was refused; possession remains contested.':'The legal and military outcome is contingent on the player’s decisions.';}},
 {year:1470,title:'Nibley Green · a private battle',record:'The Berkeley–Talbot dispute led to a battle in Gloucestershire on 20 March 1469/70, normally called 20 March 1470 in modern dating. Thomas Talbot, Viscount Lisle, was killed in recorded history.',source:'https://www.northnibley.org.uk/battle.php',status:s=>s.sandbox?.narrative?.seen?.nibley?'A fictional royal intervention reached the Gloucestershire feud; the outcome is contingent.':'The recorded battle is historical context, not a fixed game event.'},
 {year:1470,title:'Warwick changes allegiance',record:'In recorded history Warwick and Clarence turned against Edward; Henry VI briefly returned to the throne.',source:'https://www.royal.uk/edward-iv',status:s=>{const p=s.sandbox?.pressure?.cases?.warwick;const f=s.sandbox?.story?.flags||{};return p?'A confrontation arose from Warwick’s grievance; its resolution is not predetermined.':f.nevilleTerms==='negotiated'?'Edward negotiated with Warwick; the recorded betrayal is not automatic.':'This simulation does not impose a betrayal in 1470.';}},
 {year:1471,title:'Barnet, Tewkesbury and Henry VI',record:'Warwick was killed at Barnet (14 April 1471); Edward’s victory at Tewkesbury followed in May. Henry VI died in the Tower in May 1471, in circumstances that remain disputed.',source:'https://historicengland.org.uk/listing/the-list/list-entry/1000001',status:s=>s.sandbox?.pressure?.cases?.warwick?.stage>=2?'The king faced an alternate armed dispute. It is not the documented Battle of Barnet.':'These historical deaths and battles are not scripted into the alternate timeline.'},
 {year:1475,title:'Edward’s campaign and Picquigny',record:'Edward invaded France in 1475 and negotiated the Treaty of Picquigny with Louis XI, including substantial payments.',source:'https://www.royal.uk/edward-iv',status:s=>{const f=s.sandbox?.story?.flags||{};return f.frenchSettlement==='payments'?'This reign prepared an expedition and negotiated French payments.':f.frenchSettlement==='trade-truce'?'No expedition was ordered: merchants negotiated safe passage, not a royal pension.':f.frenchSettlement==='divided-trade'?'No invasion: the king kept separate trading licences.':f.frenchSettlement==='campaign'?'Edward continued a continental military commitment.':'A campaign and a treaty are conditional, not automatic.';}},
 {year:1476,title:'Death of Archbishop George Neville',record:'George Neville, Archbishop of York and Edward’s former Chancellor, died on 8 June 1476. His death was not the same as Warwick’s political fall.',source:'https://en.wikisource.org/wiki/Dictionary_of_National_Biography%2C_1885-1900/Neville%2C_George_%281433%3F-1476%29',status:s=>s.facts.george_neville_death_recorded?'The death has been entered; George Neville no longer holds the Great Seal.':'The event has not yet reached the simulated calendar.'},
 {year:1478,title:'Clarence and royal justice',record:'George, Duke of Clarence, Edward’s brother, was executed in 1478 after an attainder. His fate is not compulsory in the game.',source:'https://www.royal.uk/edward-v',status:s=>{const v=s.sandbox?.story?.flags?.clarenceCharge;return v==='audit'||v==='conditional'?'Clarence’s household accounts were heard; no treason case was presumed.':v?'A dispute involving Clarence reached the Crown; no execution is automatic.':'The historical execution is not assumed to occur in this reign.';}},
 {year:1483,title:'Edward IV dies · succession',record:'Edward IV died in April 1483, leaving his young son Edward V as heir in recorded history. The ensuing crisis is historically documented, but its alternate outcome is not predetermined.',source:'https://www.royal.uk/edward-v',status:s=>s.sandbox?.ended?'The game’s conditional succession epilogue reflects the political world the player left.':'The royal household and succession arrangements remain open to the player.'}
];
function edwardHistoryAudit(s){const sb=s.sandbox,f=sb?.story?.flags||{},problems=[];
 if(!sb)return problems;
 if(f.frenchSettlement==='payments'&&f.calaisPolicy!=='expedition')problems.push('French payments without an expeditionary basis.');
 if(f.caisterPeace==='prevented'&&f.caisterGate==='royal')problems.push('A military emergency garrison was ordered after the siege was prevented.');
 if(sb.marriage!=='elizabeth'&&sb.deep?.heirs?.edward?.mother==='woodville')problems.push('A Woodville royal heir was recorded without the Woodville marriage.');
 if(!Object.prototype.hasOwnProperty.call(sb.unrest,'East Anglia'))problems.push('East Anglia missing from the unrest model.');
 if(!Object.prototype.hasOwnProperty.call(sb.unrest,'West Country'))problems.push('West Country missing from the unrest model.');
 if(sb.story?.quietClosures?.some(x=>x.beat==='muster'&&x.arc==='caister')&&sb.story.journal.some(x=>x.arc==='caister'&&x.beat==='muster'))problems.push('A prevented siege was also presented as a battle.');
 return problems;
}
function edwardHistoricalLens(){const year=world.sandbox?.year||Number(CHAPTERS[world.chapterIndex]?.date?.match(/14\d\d/)?.[0]||1461),notes=EDWARD_HISTORY_ANCHORS;
 const rows=notes.map(a=>'<div class="history-anchor"><div class="eyebrow">'+E(a.year)+' · RECORDED HISTORY</div><b>'+E(a.title)+'</b><p>'+E(a.record)+'</p><div class="history-in-your-reign"><strong>In your reign</strong> '+E(a.status(world))+'</div><a href="'+E(a.source)+'" target="_blank" rel="noopener noreferrer">Historical source ↗</a></div>').join('');
 const p=world.sandbox?.pressure,st=world.sandbox?.story,crises=p?.journal||[],quiet=st?.quietClosures||[];
 const recent=crises.slice(-6).reverse().map(x=>'<div class="row"><div class="eyebrow">'+E(x.year)+' · GENERATED BY THE WORLD</div><b>'+E(WP_CASES[x.id]?.name||x.id)+'</b><span>'+E(x.outcome)+'</span></div>').join('');
 const avoided=quiet.slice(-5).reverse().map(x=>'<div class="row"><div class="eyebrow">'+E(x.year)+' · DID NOT HAPPEN</div><b>'+E(SE_STORIES[x.arc]?.title||x.arc)+'</b><span>'+E(x.reason)+'</span></div>').join('');
 openSheet('History & Your Reign','<div class="reading-summary"><div class="eyebrow">DOCUMENTED WORLD · EMERGENT OUTCOMES</div><p>History sets the pressures. Your decisions determine what follows.</p><div class="reading-stakes">Real dates and institutions are kept distinct from invented speeches, local petitions and alternate events.</div></div><div class="eyebrow">THE DOCUMENTED TIMELINE</div>'+rows+'<details class="reading-detail"><summary>Crises caused by this reign <span>'+crises.length+' decisions</span></summary><div class="reading-detail-body">'+(recent||'<p>No conditional crisis has been heard yet.</p>')+'</div></details><details class="reading-detail"><summary>Crises that never happened <span>'+quiet.length+' avoided scenes</span></summary><div class="reading-detail-body">'+(avoided||'<p>Earlier settlements have not yet prevented a major confrontation.</p>')+'</div></details>');
}
