/* EDWARD — HISTORICAL DOSSIERS LAB (experimental, not a claim of documentary dialogue).
   Authored pressures create playable, state-sensitive episodes and follow-ups.
   Outcomes are counterfactual unless explicitly stated in the historical reference.
*/
const ND_CASES={
 captive:{year:1465,until:1466,actor:'lancaster',where:'London',title:'THE CAPTIVE KING',source:'https://www.hrp.org.uk/tower-of-london/history-and-stories/henry-vi/',anchor:'Henry VI was captured in 1465 and confined in the Tower. The custody discussions and alternatives here are fictional reconstructions.',
  eligible:s=>s.sandbox.actors.lancaster.alive,
  intro:s=>s.facts.north_rising_1464==='averted'?({who:'A northern correspondent',role:'Reports concerning Henry VI',quote:'The northern lords are quiet, yet no man will tell us where Henry of Lancaster is sheltered. Shall we hunt him or send an offer of peace?',context:'In this alternate reign the northern settlement changed the pursuit. A name can still attract loyalty even when its bearer is absent.',left:'Send men to locate Henry.',right:'Offer safe conduct through envoys.'}):({who:'Keeper of the Tower',role:'Royal custody · Westminster',quote:'Henry of Lancaster is in our hands. A king in captivity is still a name men may rally to. Who is permitted to see him?',context:'A prisoner may be guarded, but visitors, priests and letters can turn confinement into politics. Edward has reports, not certainty about who remains loyal to Henry.',left:'Restrict all access to Henry.',right:'Permit supervised visits.'}),
  echo:(s,v)=>s.facts.north_rising_1464==='averted'?({who:'The northern correspondent',role:'A second uncertain report',quote:v==='left'?'Your search has reached the border. The local captains now ask whether finding Henry will mean a pardon or a prison.':'An intermediary says Henry’s friends might accept safe conduct. No one will name who has given him that authority.',context:'A report from a messenger is not proof of Henry’s whereabouts or intentions.',left:'Demand a witnessed answer.',right:'Continue discreet negotiations.'}):({who:'The Keeper',role:'A report from the Tower',quote:v==='left'?'A priest protests that he cannot reach the prisoner. His friends now say the king fears even a Mass.':'A visitor has repeated Henry’s words outside the Tower. We cannot tell whether he spoke for himself or for those who listen.',context:'Your custody order has become part of the contest over legitimacy. You cannot know how every listener interpreted it.',left:'Issue a clear public order.',right:'Leave the keeper discretion.'})},
 queen:{year:1466,until:1467,actor:'woodville',where:'Westminster',title:'THE QUEEN’S KIN',source:'https://www.hrp.org.uk/tower-of-london/history-and-stories/the-princes-in-the-tower/',anchor:'Edward IV’s marriage to Elizabeth Woodville reshaped access and patronage at court. The particular petition and dialogue are fictional.',
  eligible:s=>s.sandbox.marriage==='elizabeth',
  intro:s=>({who:'Elizabeth Woodville',role:'Queen of England',quote:'My brother asks for a place. He will serve you faithfully. Must every favour to my family be treated as an offence?',context:'The Woodvilles had standing before the marriage. Royal favour can strengthen their network, while other households count each appointment.',left:'Grant the office openly.',right:'Send the petition through Council.'}),
  echo:(s,v)=>({who:v==='left'?'William Hastings':'Elizabeth Woodville',role:'A matter of access',quote:v==='left'?'There is talk that a man must now marry into the queen’s family to be heard. I do not say it is true.':'Your Council has delayed the petition again. My family hears the delay as a judgment upon me.',context:'Court access is a political resource. Both favour and refusal can create expectations beyond the original request.',left:'Invite the households together.',right:'Keep the appointments separate.'})},
 seal:{year:1467,until:1468,actor:'warwick',where:'Westminster',title:'THE GREAT SEAL',source:'https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1885-1900/Neville,_Richard_(1428-1471)',anchor:'In 1467 Edward removed the Great Seal from George Neville while Warwick pursued French diplomacy. This game allows the royal relationship to develop differently.',
  eligible:s=>s.sandbox.actors.warwick.alive,
  intro:s=>({who:'George Neville',role:'Chancellor · Warwick’s brother',quote:'My brother negotiates with France, yet merchants speak of Burgundy as though an agreement were already made. Which royal policy am I to seal?',context:'Warwick favours French negotiation; Edward’s court has reasons to look toward Burgundy. George Neville holds an office, but he is not outside the family dispute.',left:'Back the Burgundian approach.',right:'Let Warwick pursue France.'}),
  echo:(s,v)=>({who:v==='left'?'Richard Neville, Earl of Warwick':'A Burgundian envoy',role:'An embassy returns',quote:v==='left'?'I went abroad as your servant. I return to learn that your purpose was settled without me.':'The king’s agents speak warmly of France, but the merchants of Flanders ask whether England means to abandon their trade.',context:'The diplomatic direction you chose has changed who trusts the Crown’s assurances. The choice is now harder to reverse.',left:'Give a public explanation.',right:'Negotiate quietly with the injured party.'})},
 caister:{year:1469,until:1470,actor:'london',where:'Norfolk',title:'THE LETTERS FROM CAISTER',source:'https://historicengland.org.uk/listing/the-list/list-entry/1002882',anchor:'The Paston family disputed Caister Castle with the Duke of Norfolk. In 1469 Norfolk besieged and seized it. The royal intervention imagined here is counterfactual.',
  eligible:s=>s.sandbox.royalAuthority>-5,
  intro:s=>({who:'A messenger for Margaret Paston',role:'Caister Castle · Norfolk',quote:'The Duke of Norfolk says his title is better. My lady says the castle was left to her family. His men are gathering, Your Grace. Shall a widow wait for the law while armed men ride?',context:'The Pastons claim Sir John Fastolf’s legacy; the duke has greater military resources. The Crown has received competing claims, not a final judgment.',left:'Send a royal commission immediately.',right:'Leave the title to local arbitration.'}),
  echo:(s,v)=>({who:'Margaret Paston’s messenger',role:'A second letter from Norfolk',quote:v==='left'?'Your commissioners arrived before the gate was forced. The duke’s men still demand entry, and now invoke your name.':'Caister’s stores are running low. The duke’s men hold the approaches. The family asks whether the king’s peace extends to their walls.',context:v==='left'?'The royal commission has delayed violence, but its authority is contested.':'A local dispute has become a test of whether royal justice can act before armed possession decides the case.',left:'Enforce the royal peace.',right:'Seek a compromise over possession.'})},
 nibley:{year:1470,until:1471,actor:'hastings',where:'Gloucestershire',title:'THE FIELD AT NIBLEY',source:'https://www.northnibley.org.uk/battle.php',anchor:'The Berkeley–Talbot inheritance feud culminated in the Battle of Nibley Green on 20 March 1469/70 (20 March 1470 in modern year reckoning). The game presents a fictional opportunity for royal intervention before violence.',
  eligible:s=>s.sandbox.royalAuthority>-6,
  intro:s=>({who:'A sheriff from Gloucestershire',role:'Berkeley lands · A disputed inheritance',quote:'Lord Berkeley and Viscount Lisle each claim the inheritance. Their retainers are mustering. Both swear that they defend lawful title.',context:'This is a real inheritance dispute between named historical families. A legal claim, armed following and local allies are becoming inseparable.',left:'Order both sides to give sureties.',right:'Let the competing titles be heard first.'}),
  echo:(s,v)=>({who:'The sheriff',role:'A report from the Severn valley',quote:v==='left'?'Both houses have pledged the peace, but neither has sent all his men home. One party asks whether the other’s surety is worth more than his own.':'The hearing is delayed. Tenants say the roads are crowded with armed men; neither lord will be the first to stand down.',context:'Your order shaped the tempo of the dispute, but the parties still control their retainers. A royal judgment without enforcement may not end a feud.',left:'Appoint a local peace commission.',right:'Summon both lords before you.'})},
 france:{year:1475,until:1476,actor:'burgundy',where:'Calais',title:'THE PRICE OF PEACE',source:'https://www.universalis.fr/index/traite-de-picquigny/',anchor:'Edward IV crossed to France in 1475 and made the Treaty of Picquigny with Louis XI, receiving payments. In this game the diplomatic result is contingent.',
  eligible:s=>s.sandbox.actors.burgundy.alive,
  intro:s=>({who:'An envoy of Louis XI',role:'The French frontier',quote:'My master will pay for peace. Burgundy promises arms, yet the roads are empty of his men. Which promise can Your Grace afford to believe?',context:'The English Crown must weigh military honour, royal finance, merchants’ interests and the reliability of its allies. The offer has not been accepted.',left:'Negotiate the French payment.',right:'Keep faith with the campaign.'}),
  echo:(s,v)=>({who:v==='left'?'A royal treasurer':'A captain at Calais',role:'The cost of a decision',quote:v==='left'?'The first payment has arrived. Men who wanted battle now ask whether France has bought the king’s claim.':'The companies ask for wages. Burgundy’s men have not joined us as expected, and the French king still offers terms.',context:'Peace changes the Crown’s credit; continued war changes what soldiers and allies expect. Neither outcome settles England’s dynastic tensions.',left:'Explain the policy to Parliament.',right:'Settle the matter through household envoys.'})},
 clarence:{year:1478,until:1479,actor:'hastings',where:'Westminster',title:'A BROTHER BEFORE PARLIAMENT',source:'https://thewarsoftheroses.co.uk/attainder-of-george-duke-of-clarence/',anchor:'George, Duke of Clarence, was attainted and executed in 1478. Here Edward can choose another course; no execution is forced by history.',
  eligible:s=>s.sandbox.royalAuthority>-8,
  intro:s=>({who:'A clerk of the royal Council',role:'The accusations against Clarence',quote:'The Duke is your brother. Some men swear he has received oaths that belong to the Crown. Others will not testify openly against a prince of the blood.',context:'The allegations are serious; not every allegation is proven by the fact that it is repeated. Family loyalty and the king’s peace now meet in public.',left:'Bring the charges before Parliament.',right:'Seek a binding family settlement.'}),
  echo:(s,v)=>({who:v==='left'?'The Speaker’s messenger':'A household servant of Clarence',role:'A royal family divided',quote:v==='left'?'The Commons ask whether the King will insist on the full penalty. The law has made the quarrel visible to the realm.':'Clarence has sworn to keep the peace, but his friends say the terms humiliate a royal brother. They ask what guarantee survives your next change of mind.',context:'Your earlier choice is now a precedent: either Parliament has been drawn into the family quarrel, or the royal household must enforce a private settlement.',left:'Make the settlement binding.',right:'Allow a limited reconciliation.'})},
 heirs:{year:1482,until:1483,actor:'woodville',where:'Westminster',title:'WHO WILL KEEP THE HEIR?',source:'https://www.hrp.org.uk/tower-of-london/history-and-stories/the-princes-in-the-tower/',anchor:'The succession of Edward IV and the position of his children became a crisis after his death in 1483. The negotiations depicted here are fictional counterfactuals.',
  eligible:s=>true,
  intro:s=>({who:'A councillor of the King',role:'The royal household · Succession',quote:s.sandbox.heir==='undecided'?'There is no agreed successor. Every household speaks of the future as if it were already theirs. Who will have authority if Your Grace cannot govern?':'The heir has protectors already, though no man calls himself one. Should the prince’s household belong to his mother’s kin, or to officers who answer to the Crown?',context:s.sandbox.heir==='undecided'?'The succession has not been clearly settled in this reign. Powerful households already ask who will govern during uncertainty.':'The named heir may be secure in law and vulnerable in practice. Access to the child can become access to government.',left:'Record a public guardianship.',right:'Keep guardianship within the household.'}),
  echo:(s,v)=>({who:'A messenger from the royal nursery',role:'The future court',quote:v==='left'?'Those named in the guardianship ask for revenues and officers. They say they cannot protect the heir without them.':'Two households claim to have received your private confidence. Neither will put its words in writing.',context:'Protection, income and physical custody need not be held by the same person. Your arrangement will outlive your ability to enforce it.',left:'Separate custody from revenue.',right:'Confirm one household’s charge.'})}
};
function ndInit(s){const sb=s.sandbox;if(!sb.narrative)sb.narrative={seen:{},choices:{},pending:[],journal:[],outcomes:{},scheduledYears:{},lastDossier:null};return sb.narrative;}
function ndCanStart(s,key){const def=ND_CASES[key],n=ndInit(s),sb=s.sandbox;return sb.year>=def.year&&sb.year<=def.until&&!n.seen[key]&&def.eligible(s);}
function ndMakeEvent(s,key,stage){const sb=s.sandbox,def=ND_CASES[key];return {serial:++sb.serial,actor:def.actor,template:'petition',where:def.where,year:sb.year,origin:'historical-dossier',sourceAction:'historically grounded political pressure',parent:null,caseId:key,caseStage:stage};}
function ndSchedule(s){const sb=s.sandbox,n=ndInit(s),year=sb.year;
 if(n.scheduledYears[year])return;
 n.scheduledYears[year]=true;
 const due=n.pending.filter(p=>p.year<=year);n.pending=n.pending.filter(p=>p.year>year);
 const additions=due.map(p=>ndMakeEvent(s,p.key,'echo'));
 const starts=Object.keys(ND_CASES).filter(key=>ndCanStart(s,key));
 if(starts.length){const key=starts[0];n.seen[key]=true;additions.push(ndMakeEvent(s,key,'intro'));}
 // Put a remembered consequence first, then a new political question.
 for(let i=additions.length-1;i>=0;i--)sb.events.unshift(additions[i]);
}
const _ndOldSbEvent=sbEvent;
sbEvent=function(s){sbInit(s);ndSchedule(s);return _ndOldSbEvent(s);};
const _ndOldSbBuild=sbBuildCard;
sbBuildCard=function(s,ev){if(!ev.caseId)return _ndOldSbBuild(s,ev);
 const def=ND_CASES[ev.caseId],n=ndInit(s),prev=n.choices[ev.caseId],stage=ev.caseStage;
 const scene=stage==='intro'?def.intro(s):def.echo(s,prev);
 const mk=(side,arena)=>({label:side==='left'?scene.left:scene.right,effects:world=>{
  ndResolve(world,ev,side,arena);return {records:[`${def.title} (${ev.year}): ${side==='left'?scene.left:scene.right}`],facts:{last_historical_dossier:ev.caseId},obligations:arena==='down'?[['edward',ev.actor,`Private assurance concerning ${def.title}`,'private']]:[]};
 }});
 const card={id:'sb-'+ev.serial,where:def.where,when:String(s.sandbox.year),who:scene.who,role:scene.role,tag:def.title,record:'politics',quote:scene.quote,context:scene.context+(stage==='echo'?' Your earlier decision has returned.':''),left:mk('left','direct'),right:mk('right','direct'),dynamic:true,caseInfo:{title:def.title,anchor:def.anchor,source:def.source,stage}};
 if(stage==='intro'){
  card.up={title:'Take formal counsel',who:'The King’s Council',role:'Recorded deliberation',quote:'A formal answer will be remembered by everyone who hears it. But the witnesses may not share your interests.',left:mk('left','up'),right:mk('right','up')};
  card.down={title:'Hear a private voice',who:scene.who,role:'Private audience',quote:'Without witnesses, a promise may be easier to make—and harder to prove or enforce.',left:mk('left','down'),right:mk('right','down')};
 }
 return card;
};
function ndResolve(s,ev,side,arena){const sb=s.sandbox,n=ndInit(s),key=ev.caseId,stage=ev.caseStage,yes=side==='left',a=sb.actors[ev.actor];
 if(stage==='intro'){
  n.choices[key]=side;n.pending.push({key,year:Math.min(1483,sb.year+1)});
  n.outcomes[key]=yes?'intervention':'restraint';
 }else n.outcomes[key]+=' / '+(yes?'enforced':'reconciled');
 // Case-specific political consequences, no generic identical reward/punishment.
 if(key==='captive'){sb.legitimacy=sbClamp(sb.legitimacy+(yes?1:-1),-8,8);sbAdjust(sb,'lancaster',{grievance:yes?1:0,trust:yes?-1:1});}
 if(key==='queen'){sbAdjust(sb,'woodville',{influence:yes?1:0,trust:yes?1:-1});sbAdjust(sb,'warwick',{grievance:yes?1:0});}
 if(key==='seal'){sbAdjust(sb,'warwick',{grievance:yes?2:-1,trust:yes?-1:1});sbAdjust(sb,'burgundy',{trust:yes?1:-1});sb.royalAuthority=sbClamp(sb.royalAuthority+(yes?1:0),-8,8);}
 if(key==='caister'){sb.unrest['East Anglia']=sbClamp((sb.unrest['East Anglia']||0)+(yes?-1:1),0,9);sb.royalAuthority=sbClamp(sb.royalAuthority+(yes?1:-1),-8,8);}
 if(key==='nibley'){sb.unrest['West Country']=sbClamp((sb.unrest['West Country']||0)+(yes?-2:2),0,9);sb.royalAuthority=sbClamp(sb.royalAuthority+(yes?1:0),-8,8);}
 if(key==='france'){sb.credit=sbClamp(sb.credit+(yes?2:-2),-8,8);sbAdjust(sb,'burgundy',{grievance:yes?1:0,trust:yes?-1:1});}
 if(key==='clarence'){sb.royalAuthority=sbClamp(sb.royalAuthority+(yes?1:-1),-8,8);sb.unrest.Court=sbClamp(sb.unrest.Court+(yes?1:-1),0,9);}
 if(key==='heirs'){sb.regency=yes?'council':'household';sb.legitimacy=sbClamp(sb.legitimacy+(yes?1:0),-8,8);}
 if(arena==='up'){sb.royalAuthority=sbClamp(sb.royalAuthority+1,-8,8);}
 if(arena==='down'){sbAdjust(sb,ev.actor,{trust:1});}
 const def=ND_CASES[key];const scene=stage==='intro'?def.intro(s):def.echo(s,n.choices[key]);const label=yes?scene.left:scene.right;const record={year:sb.year,key,stage,choice:side,arena:arena||'direct',summary:`${def.title}: ${label}${stage==='echo'?' — consequence of an earlier ruling':''}`};n.journal.push(record);n.lastDossier=key;
 sb.history.push({serial:ev.serial,year:sb.year,actor:ev.actor,template:'dossier:'+key,where:def.where,origin:'historical-dossier',side,arena,caseStage:stage,parent:stage==='echo'?key:null});sb.reactiveCount++;sb.yearTurn++;
 if(sb.yearTurn>=sb.perYear)sbAdvanceYear(s);
}
