/* Reactive storylets: fictionalized conversations around real institutions and pressures.
   Each one is eligible only when prior actions have created the corresponding situation. */
SITUATIONS.push(
I('mercy_witness','spring61','Sir Robert','Yorkist veteran (composite)','York','April 1461',
 'The man you spared is back upon his estate. My brother died for you at Towton. What shall I tell his widow?',
 'Your pardon has reached another household. The veteran believes the same estate had been promised as reward.',
 C('Hear the widow’s claim.',{facts:{widow_claim:'hearing'},obligations:[['edward','robert','hear a competing estate claim','public']],records:['Edward agreed to hear a Yorkist widow’s competing claim.']}),
 C('The pardon stands.',{facts:{widow_claim:'dismissed'},records:['Edward upheld the restored Lancastrian’s estate despite a Yorkist petition.']}),
 {requires:s=>s.facts.first_pardon===true,after:['young_knight'],priority:91,tag:'A PARDON REMEMBERED',record:'politics',up:{title:'Ask for the charters',who:'A royal clerk',role:'The king’s record',quote:'A promise to one household may not erase a claim recorded for another. We should examine what was actually granted.',left:C('Call for both instruments.',{facts:{widow_claim:'documents'},records:['Edward ordered both estate instruments examined.']}),right:C('Trust the original pardon.',{facts:{widow_claim:'dismissed'},records:['Edward treated his earlier pardon as decisive.']})}}),
I('forfeiture_witness','spring61','A Yorkshire parish priest','Local intermediary (composite)','York','April 1461',
 'The forfeited manor has a church patronage right. The new landholder says he may appoint the next rector; the present priest fears being driven out now. Will your officers distinguish the living priest from the right to nominate his successor?',
 'A grant of land can transfer an advowson (the right to present a future rector), but does not automatically remove the current incumbent. This petition is an invented example of a real legal distinction.',
 C('Protect the rector; review the patronage.',{facts:{forfeiture_dependants:'protected'},precedents:['The incumbent priest was protected while the patronage right was reviewed.'],records:['Edward ordered that the incumbent remain while the patronage right was examined.']}),
 C('Recognise the new patron’s future right.',{facts:{forfeiture_dependants:'discretion'},records:['Edward recognised the new landholder’s right of future presentation, without removing the incumbent.']}),
 {requires:s=>s.facts.first_pardon===false,after:['young_knight'],priority:91,tag:'FORFEITURE REMEMBERED'}),
I('neville_kinship','summer61','William Hastings','Royal household','Westminster','Summer 1461',
 'The Chancellor is Warwick’s brother. The two are able servants, Your Grace. When their advice agrees, who will question it?',
 'The Great Seal is a royal office, but kinship makes private coordination possible.',
 C('Require a second opinion.',{facts:{council_review:'second_opinion'},links:{hastings:1,george:-1},records:['Edward required an independent review of disputed grants.']}),
 C('Let the Chancellor govern.',{facts:{council_review:'chancellor'},links:{george:1,warwick:1},records:['Edward continued to rely upon Neville counsel.']}),
 {after:['chancellor'],priority:89,tag:'KINSHIP AND OFFICE',down:{title:'Ask Hastings privately',who:'William Hastings',role:'Private household counsel',quote:'You need not distrust them to build servants of your own, Your Grace.',left:C('Build a household channel.',{facts:{council_review:'household'},links:{hastings:2},records:['Edward asked Hastings to establish a separate household channel.']}),right:C('Do not create factions.',{facts:{council_review:'chancellor'},records:['Edward declined a separate household channel.']})}}),
I('northern_seal_echo','summer61','A northern clerk','Messenger (composite)','Westminster','Summer 1461',
 s=>s.facts.warwick_grant==='rejected'?'Warwick’s men will not accept a submission without fresh instructions. Two households now wait upon the same land.':'A grant was made in your name in the North. Its holders ask whether Westminster will recognise it.',
 'The limits of delegated authority now determine whether local arrangements are secure.',
 C('Send an expedited warrant.',{facts:{seal_courier:'expedited'},records:['Edward sent a rapid warrant to resolve a northern settlement.']}),
 C('Require the full procedure.',{facts:{seal_courier:'ordinary'},records:['Edward insisted on the ordinary procedure for northern grants.']}),
 {after:['warwick_grant'],priority:89,tag:'DELEGATED AUTHORITY',up:{title:'Hear the chancery clerk',who:'A chancery clerk',role:'Great Seal office',quote:'A short warrant can resolve this case. It cannot resolve every future case in the North.',left:C('Establish a standard form.',{facts:{seal_courier:'standard'},precedents:['A standard form was authorized for northern grants.'],records:['Edward established a standard form for northern warrants.']}),right:C('Decide each case separately.',{facts:{seal_courier:'ordinary'},records:['Edward reserved northern grants for individual examination.']})}}),
I('hastings_clients','summer61','William Hastings','Royal household','Westminster','Autumn 1461',
 'A gentleman asks to enter your service. Warwick knows his family. I could receive him into the household, if you wish.',
 'An appointment can create a direct royal servant or another link between existing affinities.',
 C('Receive him through Hastings.',{facts:{household_recruitment:'direct'},links:{hastings:2},records:['Edward received a gentleman through the royal household.']}),
 C('Ask Warwick for his opinion.',{facts:{household_recruitment:'warwick'},links:{warwick:1},records:['Edward sought Warwick’s advice before a household appointment.']}),
 {after:['hastings'],priority:77,tag:'HOUSEHOLD SERVICE'}),
I('widow_claim_returns','autumn61','A parliamentary clerk','Petitions officer (composite)','Westminster','November 1461',
 s=>s.facts.widow_claim==='documents'?'The two charters you ordered examined are inconsistent. Neither household will withdraw its claim.':'The widow whose claim you heard after Towton now asks whether Parliament will give her a remedy.',
 'A personal promise has become a question of written title and public law.',
 C('Refer the claim to judges.',{facts:{widow_resolution:'judges'},records:['The competing claim was referred for judicial examination.']}),
 C('Settle it through royal grace.',{facts:{widow_resolution:'royal'},obligations:[['edward','robert','compensation after estate dispute','public']],records:['Edward promised compensation in the disputed estate case.']}),
 {requires:s=>s.facts.widow_claim==='hearing'||s.facts.widow_claim==='documents',after:['attainder'],priority:96,tag:'A CLAIM RETURNS'}),
I('chancery_queue','autumn61','George Neville','Chancellor','Westminster','November 1461',
 'The clerks are holding warrants while they seek your judgment. The Crown’s care is becoming the Crown’s delay.',
 'Formal oversight prevents unauthorized grants but can slow government when every case comes to Edward.',
 C('Delegate routine cases.',{facts:{chancery_policy:'routine'},links:{george:1},records:['Edward delegated routine warrants to chancery.']}),
 C('Appoint a reviewing clerk.',{facts:{chancery_policy:'review'},links:{hastings:1},records:['Edward appointed a separate reviewer for disputed warrants.']}),
 {requires:s=>s.facts.seal_policy==='king'||s.facts.council_review==='second_opinion',after:['parliament'],priority:87,tag:'THE COST OF CONTROL'}),
I('london_receipt','autumn61','A London merchant','Creditor (composite)','Westminster','December 1461',
 'My partners say a private assurance is not a warrant. If I die, how will my heirs prove what the king promised?',
 'A private loan can be fast but difficult for others to enforce or verify.',
 C('Put the debt in writing.',{facts:{merchant_proof:'written'},obligations:[['edward','london','written evidence of merchant debt','public']],records:['Edward ordered a written acknowledgment of merchant credit.']}),
 C('Ask him to trust your word.',{facts:{merchant_proof:'personal'},records:['Edward maintained a personal, unwitnessed assurance to a creditor.']}),
 {requires:s=>s.facts.london_credit==='personal'||s.facts.london_credit==='private_promise',after:['city_credit'],priority:92,tag:'A PRIVATE PROMISE',down:{title:'Speak alone',who:'A London merchant',role:'Creditor',quote:'Your Grace, I do trust you. But my children cannot inherit my trust.',left:C('Write a private bond.',{facts:{merchant_proof:'bond'},records:['Edward issued a private written bond to a merchant.']}),right:C('Keep the agreement verbal.',{facts:{merchant_proof:'personal'},records:['Edward kept the credit agreement unwritten.']})}}),
I('northern_discretion','year62','A Northumberland landholder','Petitioner (composite)','York','1462',
 s=>['broad','private'].includes(s.facts.warwick_north)?'Warwick accepted my oath and gave me terms. A neighbour says only the king can confirm them.':'My neighbours wait for warrants from Westminster. Until one arrives, no one dares surrender his castle.',
 'The consequences of the commission are now visible to northern households.',
 C('Confirm local submissions.',{facts:{north_submissions:'confirmed'},records:['Edward confirmed terms already offered in the North.']}),
 C('Require new sworn assurances.',{facts:{north_submissions:'renewed'},records:['Edward required fresh oaths before confirming northern submissions.']}),
 {after:['scots_border'],priority:97,tag:'AUTHORITY IN THE NORTH'}),
I('border_misinformation','year62','John Neville','Lord Montagu','Northumberland','1462',
 'Two riders tell opposite stories. One says a Lancastrian captain is ready to submit. The other says he is buying arms.',
 'Reports can be contradictory; the king cannot observe the border directly.',
 C('Send a trusted investigator.',{facts:{border_intelligence:'checked'},records:['Edward ordered an independent check of northern intelligence.']}),
 C('Act upon the warning.',{facts:{border_intelligence:'urgent'},records:['Edward treated the more alarming border report as actionable.']}),
 {after:['scots_border'],priority:92,tag:'INCOMPLETE INFORMATION',up:{title:'Hear the messengers separately',who:'Two royal clerks',role:'Separate depositions',quote:'They disagree about the captain, but both passed through the same market town. Someone there may know what was said.',left:C('Examine the common source.',{facts:{border_intelligence:'source'},records:['Edward sought the shared source of two contradictory reports.']}),right:C('Question the riders publicly.',{facts:{border_intelligence:'public'},records:['Edward ordered public questioning of contradictory messengers.']})}}),
I('retinue_wages','year62','A garrison lieutenant','Officer (composite)','Northumberland','1462',
 'My men were promised wages by the lord who raised them. He says the king will pay. Your treasurer has seen no warrant.',
 'Royal and private military obligations overlap, but their accounts do not.',
 C('Pay upon verified rolls.',{facts:{wage_policy:'audited'},records:['Edward required muster rolls before paying a retinue.']}),
 C('Leave the lord responsible.',{facts:{wage_policy:'magnate'},records:['Edward held the raising lord responsible for his soldiers’ pay.']}),
 {after:['castle_garrison'],priority:86,tag:'WAR AND ACCOUNTING'}),
I('somerset_sureties','year63','Henry Beaufort','Duke of Somerset','Westminster','1463',
 'You have given me your peace. Some at court still watch me as though I were a prisoner. Whose word will protect me?',
 'A pardon is a legal act; acceptance into a political network is a different problem.',
 C('Take his oath before Council.',{facts:{somerset_surety:'public'},obligations:[['somerset','edward','oath before council','public']],records:['Somerset renewed his oath before Council.']}),
 C('Give him your private word.',{facts:{somerset_surety:'private'},obligations:[['edward','somerset','personal protection','private']],records:['Edward privately assured Somerset of protection.']}),
 {requires:s=>s.facts.somerset==='pardoned',after:['somerset_pardon'],priority:95,tag:'THE MEANING OF MERCY',down:{title:'Ask him privately',who:'Henry Beaufort',role:'Duke of Somerset',quote:'Your Grace, a man may receive pardon and still have no place to stand. I ask for protection from those who profited by my ruin.',left:C('Promise a place at court.',{facts:{somerset_surety:'court'},records:['Edward promised Somerset a place at court.']}),right:C('Promise only the king’s peace.',{facts:{somerset_surety:'peace'},records:['Edward promised Somerset legal protection but no further favour.']})}}),
I('percy_son','year63','A Percy retainer','Northern gentleman (composite)','York','1463',
 'The young men of the household ask whether their fathers’ service to Henry will be counted against them forever.',
 'A reconciliation can create expectations among the next generation.',
 C('Accept fresh oaths from heirs.',{facts:{percy_heirs:'accepted'},precedents:['Northern heirs could swear fresh oaths without inheriting all prior penalties.'],records:['Edward permitted a new generation of northern heirs to swear allegiance.']}),
 C('Require sureties from families.',{facts:{percy_heirs:'sureties'},records:['Edward required family sureties before accepting northern heirs.']}),
 {after:['percy_return'],priority:86,tag:'INHERITED ALLEGIANCE'}),
I('household_rivalry','year63','William Hastings','Royal household','Westminster','1463',
 s=>s.facts.council_review==='household'?'The servants you asked me to gather now bring you petitions before Warwick’s men hear them. They say we are building a second council.':'Warwick’s friends bring northern petitions to George Neville. Other petitioners seek me because they think I speak more freely to you.',
 'The route by which a petition reaches Edward is itself a form of power.',
 C('Permit both channels.',{facts:{petition_channels:'plural'},links:{hastings:1,warwick:1},records:['Edward allowed parallel household and Neville petition channels.']}),
 C('Send petitions through chancery.',{facts:{petition_channels:'chancery'},links:{george:1},records:['Edward directed petitions through the Chancellor.']}),
 {after:['somerset_pardon'],priority:89,tag:'ACCESS TO THE KING'}),
I('somerset_oath_echo','year64','A Yorkist captain','Veteran (composite)','York','1464',
 s=>s.facts.somerset_1464==='stays'?'Somerset remains with you. My men ask why the man who once fought us has been trusted with honour while they still wait for their grants.':'Somerset has broken with you. Men remember the day you received him into your peace. They ask what the royal oath is worth.',
 'An earlier act of reconciliation has become a precedent for allies and enemies alike.',
 C('Defend the earlier settlement.',{facts:{somerset_legacy:'defended'},records:['Edward publicly defended the logic of his earlier reconciliation.']}),
 C('Review the terms of future pardons.',{facts:{somerset_legacy:'review'},records:['Edward ordered closer scrutiny of future political pardons.']}),
 {requires:s=>s.facts.somerset==='pardoned',after:['somerset_pardon'],priority:97,tag:'THE PAST RETURNS'}),
I('queen_suitors','year64','Jacquetta of Luxembourg','Duchess of Bedford','Westminster','Autumn 1464',
 'My daughter’s new place draws petitions to the whole family. Some are honourable matches. Others merely hope to buy the king’s ear.',
 'The Woodvilles had kinship and standing before the marriage; royal access magnifies the network.',
 C('Allow family introductions.',{facts:{woodville_access:'family'},links:{woodville:2},records:['Edward permitted the queen’s kin to present suitors at court.']}),
 C('Route petitions through officers.',{facts:{woodville_access:'officers'},links:{hastings:1},records:['Edward directed Woodville-sponsored petitions through royal officers.']}),
 {requires:s=>s.facts.marriage==='elizabeth',after:['marriage_choice'],priority:94,tag:'A FAMILY BECOMES A COURT',down:{title:'Speak to Jacquetta privately',who:'Jacquetta of Luxembourg',role:'The queen’s mother',quote:'Our family was not born yesterday, Your Grace. We knew courts before your marriage, and we will know them afterward.',left:C('Ask her to advise the queen.',{facts:{woodville_access:'advice'},links:{woodville:1},records:['Edward privately asked Jacquetta to advise the queen’s household.']}),right:C('Keep royal appointments separate.',{facts:{woodville_access:'officers'},records:['Edward separated royal appointments from Woodville family introductions.']})}}),
I('foreign_betrothal','year64','A Burgundian merchant','Diplomatic intermediary (composite)','London','Autumn 1464',
 'Your foreign marriage policy has pleased some trading houses and alarmed others. They ask whose promises bind the English crown.',
 'A foreign match shifts diplomatic expectations even before a wedding takes place.',
 C('Keep negotiations formal.',{facts:{foreign_marriage_network:'formal'},records:['Edward kept foreign marriage negotiations within formal diplomacy.']}),
 C('Invite merchant counsel.',{facts:{foreign_marriage_network:'merchants'},records:['Edward heard commercial interests on foreign marriage policy.']}),
 {requires:s=>s.facts.marriage==='foreign',after:['marriage_choice'],priority:94,tag:'A DIFFERENT COURT'}),
I('unmarried_crown','year64','George Neville','Chancellor','Westminster','Autumn 1464',
 'There is still no queen. A childless crown invites calculations no councillor will state aloud. Shall the question remain open?',
 'Refusing one marriage does not remove the dynastic problem.',
 C('Reopen marriage negotiations.',{facts:{unmarried_policy:'negotiations'},records:['Edward reopened the search for a royal marriage.']}),
 C('Attend first to the succession.',{facts:{unmarried_policy:'succession'},records:['Edward asked Council to examine succession without an immediate marriage.']}),
 {requires:s=>s.facts.marriage==='unsettled',after:['marriage_choice'],priority:94,tag:'AN ABSENCE HAS CONSEQUENCES'}),
I('court_petition_routes','year64','A court usher','Royal household (composite)','Westminster','Winter 1464',
 s=>s.facts.marriage==='elizabeth'?'The queen’s kin, Warwick’s men and Hastings’s servants each offer to carry petitions. The petitioners ask which door reaches you.':s.facts.marriage==='foreign'?'Warwick’s men and the household both offer to carry petitions. Merchants also ask which door reaches you.':'The household and the Chancellor’s men each offer to carry petitions. There is no queen to settle precedence.',
 'Access is a political resource. Edward may shape the route by which information reaches him.',
 C('Keep several doors open.',{facts:{access_final:'plural'},records:['Edward kept multiple petition channels open at court.']}),
 C('Require a common register.',{facts:{access_final:'register'},precedents:['Petitions to the king were entered in a common register.'],records:['Edward ordered a common register for petitions.']}),
 {after:['woodville_network'],priority:99,tag:'THE KING’S ATTENTION',up:{title:'Hear the ushers and clerks',who:'A chancery clerk',role:'Council procedure',quote:'A register makes a petition visible. It also tells everyone who came to you, and when.',left:C('Register names and requests.',{facts:{access_final:'register'},records:['Edward instituted a register of petitions.']}),right:C('Keep access informal.',{facts:{access_final:'plural'},records:['Edward left access to the king through several households.']})}})
);
