/* Four conditional crossover hearings: they do not exist unless two earlier
   chronicles collide. Speeches and incidents are counterfactual reconstructions. */
const SE_CROSSOVERS={
 two_doors:{title:'THE TWO DOORS OF WESTMINSTER',year:1469,until:1475,where:'Westminster',actor:'hastings',who:'William Hastings',role:'The chamberlain · a divided royal court',tag:'TWO DOORS, ONE KING',
  source:'https://www.royal.uk/edward-iv',anchor:'Edward’s household, Warwick’s network and the queen’s kin competed for influence. The particular dispute over access is fictional.',
  requires:(s,f)=>f.queenAccess==='direct'&&(f.embassy==='private'||f.foreignProcess==='private'||f.petitionDoor==='separate'),
  q:'The queen’s clerks admit petitioners through one door; Warwick’s men wait at another. Both now claim that their answer comes from you. A merchant has paid twice to be heard once. Shall we record a single royal hearing?',
  ctx:'This hearing exists because earlier choices gave direct access to the queen’s kin while bypassing or dividing other channels. The merchant’s allegation is not yet independently proven.',
  l:'Make one public register for all petitions.',r:'Let each household retain its own audience.',
  le:{authority:2,credit:-1,people:{woodville:{grievance:1},warwick:{trust:1},hastings:{trust:1}},flags:{crossoverDoors:'one-register'},report:'A shared petition register begins. Household clerks complain about the loss of discretion.'},
  re:{authority:-1,people:{woodville:{influence:1},warwick:{grievance:1},hastings:{grievance:1}},flags:{crossoverDoors:'separate'},report:'The royal households keep separate audiences. Petitioners begin carrying duplicate requests.'}},
 northern_writ:{title:'THE WRIT NO CAPTAIN WOULD CARRY',year:1471,until:1477,where:'York',actor:'montagu',who:'A northern royal commissioner',role:'The Percy–Neville settlement · York',tag:'THE WRIT WITHOUT A GUARD',
  source:'https://www.historyofwar.org/articles/battles_barnet.html',anchor:'The historical Percy restoration in 1470 displaced Neville interests. This disputed commission and dialogue are invented.',
  requires:(s,f)=>f.northEarldom==='percy'&&f.nevilleTerms==='ultimatum',
  q:'You restored Percy rights, but the Neville captains refuse to escort the sheriff who must read your writ. Percy’s men offer to do it instead. If the writ arrives under one rival’s banner, the other will call it conquest.',
  ctx:'This crisis can arise only when Percy restoration intersects with an unresolved Neville ultimatum. The commissioner knows the escort has been refused, not the Earl’s private instructions.',
  l:'Send paid royal men to deliver the writ.',r:'Ask Montagu to guarantee the transfer.',
  le:{credit:-2,authority:2,unrest:{North:-1},people:{montagu:{grievance:1},percy:{trust:1}},flags:{crossoverNorth:'royal-escort'},report:'The writ is read under the king’s banner. Both houses send observers.'},
  re:{authority:-1,unrest:{North:1},people:{montagu:{trust:1,influence:1},percy:{grievance:1}},flags:{crossoverNorth:'neville-escort'},report:'Montagu agrees to escort the writ but asks that its boundaries be reopened.'}},
 empty_chest:{title:'THE TWO EMPTY CHESTS',year:1476,until:1480,where:'Calais',actor:'london',who:'A clerk of the royal Exchequer',role:'Wages for the Channel and the shires',tag:'TWO GARRISONS, ONE TREASURY',
  source:'https://academic.oup.com/histres/article-abstract/83/220/253/5609937',anchor:'The French campaign of 1475 and the royal financial settlement are historical pressures. This particular accounting conflict is imagined.',
  requires:(s,f)=>(f.frenchSettlement==='campaign'||f.calaisPolicy==='expedition')&&(f.northGarrison==='crown'||f.caisterGate==='royal'),
  q:'The ships at Calais and the royal men holding disputed English lands draw wages from the same receipt. Both captains have shown me your warrant. The chest will not pay both. Which oath shall I ask them to break?',
  ctx:'The Crown promised an overseas commitment while taking direct responsibility for a domestic garrison. The financial shortage follows those two decisions, not a random annual penalty.',
  l:'Pay the home garrison first.',r:'Pay the Channel captains first.',
  le:{credit:-1,authority:1,unrest:{Calais:2,North:-1},people:{burgundy:{grievance:1}},flags:{crossoverTreasury:'home'},report:'The home garrison is paid. Calais captains demand a date for their arrears.'},
  re:{credit:-1,authority:-1,unrest:{Calais:-1,North:2},people:{london:{grievance:1}},flags:{crossoverTreasury:'channel'},report:'The Channel captains receive their wages. A domestic constable threatens to surrender his keys.'}},
 two_guardians:{title:'THE TWO GUARDIANSHIPS',year:1481,until:1483,where:'Westminster',actor:'woodville',who:'A clerk of the royal Council',role:'The heir’s household and the queen’s wardship',tag:'WHO HOLDS THE KEYS',
  source:'https://www.cambridge.org/core/journals/historical-journal/article/abs/i-attainder-and-forfeiture-1453-to-15091/1EA8D0EFB954878797B941400045B969',anchor:'Guardianship, inheritance and succession were politically consequential. The combined hearing is a fictional product of the player’s earlier choices.',
  requires:(s,f)=>f.queenWard==='united'&&f.heirHousehold==='united',
  q:'You placed the queen’s wardship and the royal successor’s household under concentrated guardianship. Two seals now authorize officers to collect rents from the same estate. The child’s safety is cited by both sides. Shall the Council separate the keys?',
  ctx:'This conflict exists only because two earlier decisions concentrated guardianship in households. The clerk can identify the duplicate warrants but cannot know every private promise.',
  l:'Separate custody, revenues and command by public writ.',r:'Confirm the existing guardian’s broad authority.',
  le:{authority:2,credit:-1,people:{woodville:{grievance:2},hastings:{trust:1}},flags:{crossoverGuardians:'divided'},report:'The Council separates guardianship and revenue; one household protests that protection is now impossible.'},
  re:{authority:-2,people:{woodville:{influence:2},hastings:{grievance:1}},flags:{crossoverGuardians:'concentrated'},report:'The guardian retains custody and income. Rival councillors preserve copies of the conflicting warrants.'}}
};
