/* EDWARD — INTERWOVEN CHRONICLES: 36 authored narrative beats in six causal arcs.
   Historic background is documented in the linked sources; ALL speeches, warrants,
   letters, negotiations and counterfactual incidents here are fictional reconstructions.
   Each scene has two independently authored versions, conditioned on previous choices.
   No scripted victory, betrayal, battle, or death is imposed on a counterfactual reign.
*/
const SE_STORIES={
 neville:{title:'THE KINGMAKER’S PRICE',start:1465,source:'https://www.royal.uk/edward-iv',anchor:'Warwick was an essential supporter of Edward IV, but their diplomatic and domestic interests diverged. Warwick changed sides in 1470 in recorded history. This simulation never forces that outcome.',lead:'warwick',beats:[
 {id:'counsel',year:1465,who:'Richard Neville, Earl of Warwick',role:'The king’s principal magnate · Westminster',where:'Westminster',tag:'THE PRICE OF COUNSEL',
  q:['Your Grace, my captains hold the northern roads in your name. Yet I cannot answer them when every petition must wait for a chamberlain’s whisper. Give me a clear commission, and I shall answer for my men.','Your Grace, the council has not forgotten Towton. If your servants now seek to govern without those who fought beside you, say so openly.'],
  ctx:'Warwick has military clients and authority in Calais. His request for a commission is also a request to distribute patronage.',
  l:'Issue a bounded northern commission.',r:'Keep appointments in the royal household.',
  le:{authority:1,people:{warwick:{trust:1,influence:1},montagu:{trust:1}},flags:{nevilleCommission:'bounded'},report:'Warwick accepts a commission whose terms are entered by the clerks.'},
  re:{authority:1,people:{warwick:{grievance:2,trust:-1},hastings:{influence:1}},flags:{nevilleCommission:'refused'},report:'Warwick returns to his household without a new warrant.'}},
 {id:'seal',year:1467,who:'George Neville',role:'Lord Chancellor · the Great Seal',where:'Westminster',tag:'THE SEAL AND THE ENVOY',
  q:['My brother believes that a French understanding will keep our enemies divided. Yet a Burgundian agent has been entertained in secret. Which undertaking am I to seal in the king’s name?','I have the Seal, Your Grace, but not your confidence. Warwick says your servants promise Burgundy what your envoys promise France. Shall I put my office behind either word?'],
  ctx:'The Chancellor is Warwick’s brother. A sealed letter binds the Crown more visibly than a private conversation.',
  l:'Record an open council policy.',r:'Reserve diplomacy to Edward’s own envoys.',
  le:{authority:1,credit:-1,people:{warwick:{trust:1},burgundy:{grievance:1}},flags:{foreignProcess:'council'},report:'The Chancellor records a public diplomatic instruction.'},
  re:{people:{warwick:{grievance:2},hastings:{trust:1},burgundy:{trust:1}},flags:{foreignProcess:'private'},reaction:{actor:'warwick',rival:'hastings',kind:'intelligence'},report:'George Neville requests a written explanation for the exclusion of Chancery.'}},
 {id:'clients',year:1468,who:'William Hastings',role:'Royal chamberlain · the outer court',where:'London',tag:'THE MEN IN TWO LIVERIES',
  q:['Warwick’s servants have brought a roll of names. They ask which of their men are to keep their fees after the new appointments. I can sign the warrants, but I cannot make both households satisfied.','Warwick’s men are already telling petitioners that your chamber is closed to them. One has offered me his service, and his former master calls it theft.'],
  ctx:'A household retainer may receive fees from more than one patron. The conflict is over access, not a formal declaration of rebellion.',
  l:'Publish the fee rolls and protect existing service.',r:'Allow Hastings to replace disputed officers.',
  le:{authority:1,credit:-1,people:{warwick:{trust:1},hastings:{trust:1}},flags:{clientSettlement:'published'},report:'A fee roll is displayed at Westminster; several names appear on both lists.'},
  re:{people:{warwick:{grievance:2},hastings:{influence:1,trust:1}},flags:{clientSettlement:'household'},report:'Hastings fills vacant places. Warwick’s clerks dispute which vacancies were real.'}},
 {id:'affinity',year:1469,who:'A sheriff of Warwickshire',role:'A sealed report from the shire',where:'Midlands',tag:'A RETINUE ASSEMBLES',
  q:['Two bands of men wear different badges and each says he rides under a royal licence. The market has closed early. I beg leave to summon both captains before a jury, not before one another.','The Neville servants have hired horses by the dozen. They call it an escort for the Earl; their neighbours call it a muster. The first blow may be struck before my next letter.'],
  ctx:'A local muster may be protection, intimidation, or rebellion. Edward has the sheriff’s account, not access to the private instructions.',
  l:'Demand sureties from both affinities.',r:'Allow the stronger household to restore order.',
  le:{authority:1,unrest:{Midlands:-2},people:{warwick:{grievance:1},hastings:{grievance:1}},flags:{affinityPeace:'sureties'},report:'The captains swear peace before the sheriff, though some men keep their badges.'},
  re:{authority:-1,unrest:{Midlands:2},people:{warwick:{influence:1,grievance:1}},flags:{affinityPeace:'delegated'},report:'The roads open, but the sheriff reports that one lord now commands both toll gates.'}},
 {id:'terms',year:1470,who:'Richard Neville, Earl of Warwick',role:'An audience sought through intermediaries',where:'Calais',tag:'TERMS OF ALLEGIANCE',
  q:['I have kept your ports, Your Grace. My men ask what place remains for them when new kindred sit beside your chair. Let us write our obligations before mistrust makes traitors of servants.','You may call my followers troublesome, but they are men who have been refused justice. I will not send them home upon a promise that can be forgotten at supper.'],
  ctx:'Warwick’s loyalty is a political choice, not an inevitable historical switch. His grievance is shaped by earlier appointments, the queen’s kin and foreign policy.',
  l:'Negotiate guarantees with named witnesses.',r:'Demand unconditional submission.',
  le:{authority:1,credit:-1,people:{warwick:{trust:2,grievance:-2},montagu:{trust:1}},flags:{nevilleTerms:'negotiated'},report:'Warwick sends a list of proposed sureties; not every captain agrees to sign.'},
  re:{authority:1,people:{warwick:{grievance:3,trust:-2},montagu:{grievance:1}},unrest:{North:1},flags:{nevilleTerms:'ultimatum'},reaction:{actor:'warwick',rival:'hastings',kind:'retinue'},report:'The Earl withdraws before the witnesses arrive. His servants say he has not renounced the king.'}},
 {id:'reckoning',year:1472,who:'A clerk of the royal Council',role:'An inquiry into service and pardons',where:'Westminster',tag:'THE COST OF RECONCILIATION',
  q:['The Earl’s captains have brought their oaths. They will surrender private warrants if the Crown will confirm their lands. Shall we make this peace part of the record?','Several Neville captains seek pardons, but no one agrees on the offences. To pardon without hearing them may purchase peace; to examine them may uncover a new quarrel.'],
  ctx:'The outcome depends on whether the Earl retained trust, how northern lands were settled, and whether rival households were heard.',
  l:'Confirm conditional pardons and land guarantees.',r:'Require separate hearings for every captain.',
  le:{authority:1,people:{warwick:{grievance:-2,trust:1},montagu:{trust:1}},flags:{nevilleSettlement:'pardon'},report:'Some Neville captains return their private commissions and receive royal letters.'},
  re:{authority:2,people:{warwick:{grievance:1},hastings:{trust:1}},flags:{nevilleSettlement:'inquest'},report:'The council opens individual inquiries. A few retainers depart before they can be called.'}}
 ]},
 woodville:{title:'THE QUEEN’S DOOR',start:1465,requires:s=>s.sandbox.marriage==='elizabeth',source:'https://www.royal.uk/edward-iv',anchor:'Edward IV married Elizabeth Woodville in 1464. Patronage for her kin contributed to political tension. The particular petitions and dialogues are fictional.',lead:'woodville',beats:[
 {id:'petition',year:1465,who:'Elizabeth Woodville',role:'Queen of England · the privy chamber',where:'Westminster',tag:'THE QUEEN’S PETITION',
  q:['My lord, Anthony served his family before he served mine. He asks for a place he can perform, not a title he can wear. Must my marriage make every honest petition suspect?','Your servants say a queen should ask nothing for her own blood. Yet when other lords advance their cousins it is called good government. Tell me which rule applies to us.'],
  ctx:'The queen’s family has pre-existing connections. Her marriage amplifies both their opportunities and resentment from other households.',
  l:'Grant Anthony a limited office with public terms.',r:'Refer every Woodville petition to Council.',
  le:{people:{woodville:{influence:1,trust:1},warwick:{grievance:1}},flags:{queenAccess:'direct'},report:'A Woodville commission is entered on the patent rolls.'},
  re:{authority:1,people:{woodville:{grievance:1},warwick:{trust:1}},flags:{queenAccess:'council'},report:'The Council receives the petition. The queen has not withdrawn it.'}},
 {id:'marriage',year:1466,who:'Anthony Woodville',role:'The queen’s brother · a marriage negotiation',where:'Westminster',tag:'A MARRIAGE WITH A PRICE',
  q:['A ward of good estate has been offered to our kin in marriage. I will not pretend the lands do not matter. But the child’s guardian has already taken a fee from another suitor.','The match could strengthen the queen’s house, Your Grace. Yet Warwick’s friends say the guardian once promised the ward elsewhere. They have produced no writing.'],
  ctx:'Marriage negotiations may redirect inherited property and create a rival claim. The Crown knows only the offers presented to it.',
  l:'Approve only after inspecting the wardship.',r:'Permit the private match without an inquiry.',
  le:{authority:1,people:{woodville:{trust:1},warwick:{trust:1}},flags:{woodvilleMatch:'audited'},report:'The wardship is referred to royal officers; both suitors must show their terms.'},
  re:{authority:-1,people:{woodville:{influence:1},warwick:{grievance:2}},flags:{woodvilleMatch:'private'},report:'A private marriage settlement is announced. Its land clauses are not lodged with the court.'}},
 {id:'chamber',year:1468,who:'William Hastings',role:'The king’s chamberlain · access to court',where:'London',tag:'WHO MAY SEE THE KING',
  q:['Petitioners wait in my chamber with letters bearing the queen’s name. I do not doubt her good will. I ask whether the king’s justice now begins at her door or at his seal.','A Woodville clerk has promised a hearing to a man I already refused. If his word is enough, my office is an ornament. If mine is enough, the queen will call it an insult.'],
  ctx:'Court access affects who can press claims and who bears the blame for rejected petitions.',
  l:'Establish one recorded petition register.',r:'Maintain separate channels for royal kin.',
  le:{authority:2,people:{hastings:{trust:1},woodville:{grievance:1}},flags:{petitionDoor:'register'},report:'The first shared petition register exposes two promises for the same office.'},
  re:{people:{woodville:{influence:1},hastings:{grievance:1}},flags:{petitionDoor:'separate'},report:'Two clerks give different dates for the same audience. Neither will withdraw his entry.'}},
 {id:'charter',year:1470,who:'A clerk of the Exchequer',role:'Royal grants and resumed revenues',where:'Westminster',tag:'THE PRICE OF A GRANT',
  q:['A grant to the queen’s kindred names rents already pledged to a northern captain. The same money cannot pay both. Which promise shall I put in the accounts?','The rents promised to the queen’s kin have not arrived. A Neville steward says they were pledged years ago. I have two warrants and one sheriff.'],
  ctx:'This is an imagined accounting dispute, not a claim that a particular historical charter existed. Earlier royal patronage determines who feels wronged.',
  l:'Protect the earlier claim until an audit.',r:'Pay the queen’s kin and offer compensation.',
  le:{credit:1,authority:1,people:{warwick:{trust:1},woodville:{grievance:2}},flags:{woodvilleRents:'audited'},report:'The Exchequer freezes a disputed rent pending a public account.'},
  re:{credit:-2,people:{woodville:{trust:1,influence:1},warwick:{grievance:2}},flags:{woodvilleRents:'preferred'},report:'The sheriff pays one warrant. The displaced creditor petitions for compensation.'}},
 {id:'wardship',year:1474,who:'Elizabeth Woodville',role:'The queen’s household · a minor heir',where:'Westminster',tag:'A CHILD AND AN INHERITANCE',
  q:['A young heir has been placed among my attendants. His mother asks that I keep him safe; his uncle asks for the rents. They are not the same request, and I will not pretend they are.','The child’s relatives have begun sending gifts to rival guardians. If the Crown does not name who may hold his person, they will decide it without us.'],
  ctx:'A wardship combines the care of a minor with temporary control of property. The child is not merely a prize in an adult dispute.',
  l:'Separate guardianship from estate revenues.',r:'Entrust both powers to the queen’s household.',
  le:{authority:1,people:{woodville:{trust:1},hastings:{trust:1}},flags:{queenWard:'separated'},report:'Guardianship and estate income are assigned to different officers.'},
  re:{authority:-1,people:{woodville:{influence:2},hastings:{grievance:1}},flags:{queenWard:'united'},report:'The queen’s household receives custody and rents; a distant kinsman files a protest.'}},
 {id:'reckoning',year:1478,who:'Anthony Woodville',role:'A petition from the queen’s kin',where:'Westminster',tag:'THE FAMILY ACCOUNT',
  q:['We have been favoured, yes. We have also been blamed for every office lost by another man. Let the clerks count our service beside our grants before they write our family into a charge.','Your Grace, I am told we must surrender places to prove we deserve the ones we keep. Name the offence, and I will answer it. Do not make kinship itself a crime.'],
  ctx:'The king must balance public trust, the queen’s household and established noble networks; there is no automatic historical verdict.',
  l:'Publish a review of all household grants.',r:'Protect the queen’s grants from further challenge.',
  le:{authority:2,people:{woodville:{trust:1,grievance:1},warwick:{trust:1}},flags:{queenSettlement:'review'},report:'A register of household grants is opened; it names favours from several competing affinities.'},
  re:{authority:-1,people:{woodville:{influence:1,trust:1},hastings:{grievance:1}},flags:{queenSettlement:'privilege'},report:'Royal protection quiets some petitions, but complaints continue in private.'}}
 ]},
 north:{title:'THE NORTHERN INHERITANCE',start:1465,source:'https://www.historyofwar.org/articles/battles_barnet.html',anchor:'The Nevilles and Percies contested power in the north. In recorded history Henry Percy regained the earldom of Northumberland in 1470 while John Neville received another title. The game allows different settlements.',lead:'montagu',beats:[
 {id:'title',year:1465,who:'John Neville, Lord Montagu',role:'Northern commander · York',where:'North',tag:'THE PRICE OF VICTORY',
  q:['My men kept the roads after Hexham. Now a Percy kinsman asks whether the old rents will be restored to his house. I can command the garrisons; I cannot make the tenants forget their former lord.','The Percies have sent agents to the market towns. They offer old protections and speak of hereditary right. If the king means to change the settlement, let him tell me before the garrisons hear it elsewhere.'],
  ctx:'Northern title, actual possession and local obedience are separate. The Percy–Neville rivalry did not begin with this letter.',
  l:'Commission an inquiry into old titles.',r:'Confirm Montagu’s present authority.',
  le:{authority:1,people:{montagu:{trust:1},percy:{trust:1}},flags:{northTitle:'inquest'},report:'An inquest is ordered. Percy claimants bring witnesses from several shires.'},
  re:{people:{montagu:{trust:1,influence:1},percy:{grievance:2}},flags:{northTitle:'neville'},report:'Montagu’s command is confirmed. Percy tenants continue to speak of the old title.'}},
 {id:'rents',year:1467,who:'A Percy household steward',role:'Rents and service · Northumberland',where:'North',tag:'WHO COLLECTS THE RENTS',
  q:['Your sheriff demands the rent in the king’s name. Montagu’s receiver demands it in his. Our old tenants say they have paid both before. Shall they sell their seed to pay twice?','The Neville receiver has seized our carts. He says he holds the lawful warrant. I ask only that the writ be read aloud where the tenants can hear it.'],
  ctx:'The king has competing accounts. The actual burden on tenants is visible, while the title behind the demand remains disputed.',
  l:'Suspend collection pending an audited account.',r:'Permit the current receiver to collect.',
  le:{credit:-1,authority:1,unrest:{North:-1},people:{percy:{trust:1},montagu:{grievance:1}},flags:{northRents:'suspended'},report:'A clerk posts the suspension at the market cross. Receivers protest the lost revenue.'},
  re:{credit:1,unrest:{North:1},people:{montagu:{trust:1},percy:{grievance:2}},flags:{northRents:'collected'},report:'The current receiver collects. Some tenants abandon their holdings until the dispute is heard.'}},
 {id:'earldom',year:1469,who:'Henry Percy',role:'Petitioner for northern inheritance',where:'York',tag:'THE OLD EARLDOM',
  q:['My father’s title has become a word men are forbidden to speak. I do not ask you to dishonour Lord Montagu. I ask whether the blood of my house may ever serve the Crown again.','The tenants will not be quiet because a Neville warrant calls me an intruder. I will serve you, Your Grace, if you will name what is to become of my inheritance.'],
  ctx:'The real 1470 Percy restoration is a historical pressure, not a mandatory script. Any settlement must address Montagu’s displaced interest.',
  l:'Restore Percy standing with compensation for Montagu.',r:'Keep the Neville title and offer Percy another office.',
  le:{authority:1,people:{percy:{trust:2,influence:1},montagu:{grievance:2,trust:-1}},flags:{northEarldom:'percy'},reaction:{actor:'montagu',rival:'percy',kind:'estate'},report:'Percy’s restoration is announced; Montagu’s stewards demand to see the compensation schedule.'},
  re:{people:{montagu:{trust:1,influence:1},percy:{grievance:2}},flags:{northEarldom:'neville'},report:'The Neville title stands. Percy accepts an office but his household disputes the conditions.'}},
 {id:'castle',year:1471,who:'The constable of a northern castle',role:'Garrison and oath · northern marches',where:'North',tag:'THE KEYS OF THE KEEP',
  q:['My soldiers swear to the king, but their wages come through a lord whose title is now questioned. If I surrender the keys to his rival, who will pay the men at the gate?','A new lord has sent his seal for the keys. The old captain says his oath remains good until he sees the king’s hand. I can hold the gate one week, perhaps two.'],
  ctx:'The castle is an illustrative northern stronghold, not a named documented siege. Garrisons have practical loyalties beyond the wording of a writ.',
  l:'Pay the garrison directly and take royal custody.',r:'Let the local lord retain the keys.',
  le:{credit:-2,authority:2,unrest:{North:-1},people:{montagu:{grievance:1},percy:{grievance:1}},flags:{northGarrison:'crown'},report:'The constable accepts royal wages. His former patron protests the cost of losing the keys.'},
  re:{credit:1,authority:-1,people:{montagu:{influence:1},percy:{grievance:1}},flags:{northGarrison:'lord'},report:'The keys remain in private custody; the constable asks who may command him in war.'}},
 {id:'oath',year:1474,who:'A northern justice of the peace',role:'A county hearing · Northumberland',where:'North',tag:'OATHS AFTER THE SETTLEMENT',
  q:['The same tenants have sworn obedience to two houses in ten years. They ask which oath a royal justice will enforce when the harvest is taken. I have brought their names, not their badges.','The old captains will attend your court if their rivals do. Each demands a guarantee that testimony will not be treated as confession. The villages need a peace they can recognize.'],
  ctx:'Earlier grants, a disputed earldom and garrison decisions determine whether royal peace is enforceable.',
  l:'Hold a public assize and record local obligations.',r:'Accept a private pact between the great houses.',
  le:{authority:2,credit:-1,unrest:{North:-2},people:{percy:{trust:1},montagu:{trust:1}},flags:{northOaths:'public'},report:'Tenants testify before royal justices; the strongest houses dislike the written limits.'},
  re:{authority:-1,unrest:{North:-1},people:{percy:{influence:1},montagu:{influence:1}},flags:{northOaths:'private'},report:'The households exchange private guarantees. Villagers are not shown their terms.'}},
 {id:'legacy',year:1478,who:'A messenger from York',role:'Northern county returns',where:'York',tag:'THE NORTH REMEMBERS',
  q:['Your justices have sent their final account. The roads are quieter, but men still ask which lord will speak for them when the next king is a child. Shall the Crown bind their service directly?','The great houses have made peace over the old rents. They now ask to appoint the very sheriffs who must judge future quarrels. Peace, they say, has earned them that right.'],
  ctx:'A settlement that ended one feud may create a new question about future royal authority and succession.',
  l:'Reserve the sheriff’s office to the Crown.',r:'Recognise the houses’ local nominations.',
  le:{authority:2,people:{montagu:{grievance:1},percy:{grievance:1}},flags:{northLegacy:'crown'},report:'Royal sheriffs take office. Some northern captains refuse to surrender their lists of tenants.'},
  re:{authority:-1,people:{montagu:{influence:1},percy:{influence:1}},flags:{northLegacy:'magnates'},report:'The great houses nominate local officers and promise to keep the roads open.'}}
 ]},
 caister:{title:'LETTERS FROM CAISTER',start:1467,source:'https://historicengland.org.uk/listing/the-list/list-entry/1287573',anchor:'Sir John Fastolf left Caister to John Paston. The Duke of Norfolk took the castle by force in 1469; the Pastons eventually regained it after Norfolk’s death in 1476. These royal interventions and speeches are imagined.',lead:'hastings',beats:[
 {id:'will',year:1467,who:'John Paston',role:'A disputed bequest · Norfolk',where:'Caister',tag:'THE WILL OF FASTOLF',
  q:['Sir John Fastolf left us his castle. My lord of Norfolk says other men sold him a better right. I have brought copies of the will; the originals are in danger whenever we send them upon the road.','The Duke’s men say possession proves title. If that is the law, why should a family keep its charters? I ask for a hearing before someone who does not wear Norfolk’s livery.'],
  ctx:'The will and its challengers are historical. Edward has the petitioner’s copy, not a judicial finding that settles every claim.',
  l:'Appoint independent examiners of the charters.',r:'Ask Norfolk to arbitrate the competing titles.',
  le:{authority:1,credit:-1,flags:{caisterTitle:'commission'},people:{hastings:{trust:1}},report:'Commissioners receive sealed copies of the Fastolf papers.'},
  re:{authority:-1,flags:{caisterTitle:'norfolk'},people:{hastings:{grievance:1}},report:'Norfolk’s steward offers a hearing on terms the Pastons say they cannot accept.'}},
 {id:'rents',year:1468,who:'Margaret Paston',role:'A letter concerning Caister rents',where:'Norfolk',tag:'THE RENTS OF A CASTLE',
  q:['The duke’s receiver has taken the rents before any judge has seen our title. My sons write brave words from London. Brave words do not feed the men who hold our gate.','I have counted the grain in the storehouse. It will not last if men take the rents and leave us the mouths. I ask not for favour, but for an order a sheriff will enforce.'],
  ctx:'Margaret Paston’s letters document the family’s struggle, but this particular address to Edward is fictional. The dispute now concerns food and possession.',
  l:'Protect the harvest pending judgment.',r:'Let the local receiver continue collecting.',
  le:{authority:1,credit:-1,flags:{caisterRents:'protected'},report:'A royal officer orders grain retained for the garrison; the receiver disputes his warrant.'},
  re:{credit:1,flags:{caisterRents:'taken'},people:{hastings:{grievance:1}},report:'The rents are collected. A letter from Caister warns of dwindling stores.'}},
 {id:'muster',year:1469,who:'A Norfolk sheriff',role:'The approaches to Caister',where:'Caister',tag:'THE MEN AT THE GATE',
  q:['The Duke of Norfolk has assembled men near Caister. He says they will merely enforce his title. The Pastons have barred the gate. Shall I ride between them with your banner?','There are armed men in the lanes, Your Grace. One side has the castle and the other the roads. Neither will be the first to dismiss its followers.'],
  ctx:'The historical siege took place in 1469. In this reign the outcome depends on earlier commissions, supplies and royal authority.',
  l:'Send the sheriff with a royal peace commission.',r:'Leave enforcement to the rival claimants.',
  le:{authority:1,credit:-1,unrest:{'East Anglia':-1},flags:{caisterPeace:'intervened'},report:'The sheriff rides to Caister with a sealed prohibition on armed entry.'},
  re:{authority:-1,unrest:{'East Anglia':2},flags:{caisterPeace:'abandoned'},report:'The duke’s men occupy the approaches; neither household accepts responsibility for the first shot.'}},
 {id:'gate',year:1470,who:'A messenger from Caister',role:'The disputed gatehouse · Norfolk',where:'Caister',tag:'THE GATEHOUSE LETTER',
  q:['The king’s commission has kept the gates shut to both claimants. Now the men ask who will pay for the watch. If you leave us without wages, the writ will become a scrap of parchment.','The outer gate has been forced, or so the messenger says; the castellan disputes his count of the men. A widow asks whether a royal writ can reach a besieged tower.'],
  ctx:'The exact state of Caister in this alternate timeline depends on Edward’s previous intervention. The messenger cannot verify every claim.',
  l:'Supply a paid royal garrison pending title judgment.',r:'Offer an immediate possession compromise.',
  le:{credit:-2,authority:2,unrest:{'East Anglia':-1},flags:{caisterGate:'royal'},report:'Royal wages reach the castle; the disputed title is not yet settled.'},
  re:{authority:-1,flags:{caisterGate:'compromise'},report:'The parties exchange proposed terms, but disagree over who may keep the keys.'}},
 {id:'widow',year:1473,who:'Margaret Paston',role:'A family letter · Norfolk',where:'Norfolk',tag:'A WIDOW’S REMEMBRANCE',
  q:['We have obeyed each hearing and paid for every journey to London. My sons are told that the king’s peace is worth waiting for. I ask how long a family must wait before a promise becomes a judgment.','The lawyers have made a trade of our title. One says the will is sound; another says the duke will never release possession. If you cannot settle it, tell us plainly what the law is worth.'],
  ctx:'Repeated legal expenses can ruin a gentry family even without open fighting. The case has accumulated costs and memories.',
  l:'Set a deadline for final judgment.',r:'Fund another private negotiation.',
  le:{authority:2,credit:-1,flags:{caisterDeadline:'public'},report:'A date for judgment is proclaimed. The duke’s representatives seek an adjournment.'},
  re:{credit:-1,flags:{caisterDeadline:'private'},report:'Intermediaries begin new talks; the Pastons warn that they cannot pay lawyers indefinitely.'}},
 {id:'patent',year:1476,who:'John Paston',role:'A petition after a change of lordship',where:'Caister',tag:'THE PATENT AND THE HEIR',
  q:['The Duke of Norfolk is dead, but our quarrel need not die with him. His heirs may inherit a claim they never examined. Shall the king settle possession now, while there is room for peace?','A new household speaks for the Norfolk inheritance. They say a king’s patent cannot erase the memory of their father’s right. We ask for title and a gate we may enter without an army.'],
  ctx:'Norfolk died in 1476 in recorded history; here the disputed rights and the settlement remain contingent. A patent may not end local resentment.',
  l:'Issue a recorded patent after a final inquest.',r:'Accept a settlement with shared rents.',
  le:{authority:2,flags:{caisterOutcome:'patent'},report:'A final royal patent is issued after the inquest; the losing party retains a right to petition.'},
  re:{authority:-1,credit:1,flags:{caisterOutcome:'shared'},report:'The claimants divide the rents and pledge not to use force, leaving title unresolved.'}}
 ]},
 diplomacy:{title:'THE TWO SHORES',start:1466,source:'https://www.royal.uk/edward-iv',anchor:'Edward IV’s diplomacy involved France, Burgundy and the Calais garrison. In recorded history he made a profitable agreement with Louis XI at Picquigny in 1475. No agreement is predetermined here.',lead:'burgundy',beats:[
 {id:'wool',year:1466,who:'A merchant of the Staple',role:'English wool trade · Calais',where:'Calais',tag:'THE MERCHANTS’ LEDGER',
  q:['Our wool crosses through Calais, but French agents offer easier passage if we will carry their letters. I sell cloth, not crowns. Shall I refuse a market because a lord distrusts its prince?','The Burgundian factor promises safe roads and asks for the king’s favour. The Frenchman promises lower duties. Neither promise is written in a language my clerk can enforce.'],
  ctx:'Calais was a key English commercial and military foothold. Merchants seek predictable duties, not necessarily their patrons’ foreign policy.',
  l:'Protect the existing Burgundian trading route.',r:'License exploratory French negotiations.',
  le:{credit:1,people:{burgundy:{trust:1},warwick:{grievance:1}},flags:{tradeRoute:'burgundy'},report:'Calais merchants renew their contracts; French intermediaries seek another channel.'},
  re:{credit:1,people:{warwick:{trust:1},burgundy:{grievance:1}},flags:{tradeRoute:'france'},report:'French merchants send draft terms; Burgundian factors ask if the king has changed policy.'}},
 {id:'embassy',year:1467,who:'Richard Neville, Earl of Warwick',role:'A returning diplomatic embassy',where:'Calais',tag:'THE EMBASSY RETURNS',
  q:['I was sent to hear France, not to be measured against a treaty made behind my back. Tell me what assurances I may carry before I face their king again.','The French council asks if my word is still the king’s. A Burgundian agent has been received by another door. An ambassador cannot serve two instructions at once.'],
  ctx:'The divergence between Warwick’s French diplomacy and Edward’s Burgundian interests is documented. The exact conversation is invented.',
  l:'Give Warwick a public, limited mandate.',r:'Use separate confidential envoys.',
  le:{authority:1,people:{warwick:{trust:1},burgundy:{grievance:1}},flags:{embassy:'public'},report:'A limited French mandate is sealed. Warwick complains about its narrow terms.'},
  re:{people:{warwick:{grievance:2},burgundy:{trust:1}},flags:{embassy:'private'},report:'Two envoys depart with different instructions. Neither sees the other’s letters.'}},
 {id:'letters',year:1469,who:'A clerk from the Calais council',role:'Foreign correspondence and secrecy',where:'Calais',tag:'LETTERS WITH TWO SEALS',
  q:['Two letters promise protection to merchants travelling the same road. One bears the Chancellor’s form; the other was carried without the Great Seal. Both are being shown as royal guarantees.','The Flemish factor asks which of your agents can pledge customs. He has heard that the Chancellor was denied the matter. If we contradict ourselves, the merchants will charge for the risk.'],
  ctx:'Conflicting instructions create financial and political costs even when neither foreign ruler intends immediate war.',
  l:'Reconcile the letters through Chancery.',r:'Keep the newer assurance and withdraw the old.',
  le:{authority:2,credit:-1,people:{warwick:{trust:1},burgundy:{trust:1}},flags:{foreignLetters:'reconciled'},report:'Chancery issues one schedule of customs obligations; both sides lose concessions.'},
  re:{authority:-1,credit:1,people:{warwick:{grievance:1},burgundy:{trust:1}},flags:{foreignLetters:'withdrawn'},report:'A private letter is recalled. Its bearer insists the king promised him protection.'}},
 {id:'captains',year:1472,who:'The captain of a Calais ship',role:'Channel passage and military stores',where:'Calais',tag:'THE PRICE OF A PASSAGE',
  q:['A convoy will sail under your colours. Burgundy offers an escort if we will carry soldiers. France offers safe passage if we carry no arms. The merchants ask for one answer before the tide turns.','Our stores have been counted twice, once for the garrison and once for an expedition that has not been ordered. Men will desert if they are promised pay from the same chest.'],
  ctx:'A naval escort is a logistical choice as much as a diplomatic declaration. Promises made to merchants and captains may conflict.',
  l:'Reserve ships and wages for defence of Calais.',r:'Prepare an expeditionary commitment.',
  le:{credit:1,authority:1,unrest:{Calais:-1},flags:{calaisPolicy:'defence'},report:'The garrison receives stores. Continental allies complain that England has not promised troops.'},
  re:{credit:-2,people:{burgundy:{trust:1}},flags:{calaisPolicy:'expedition'},report:'Ships are provisioned. The treasurer asks which customs revenue will cover the wages.'}},
 {id:'picquigny',year:1475,who:'An envoy of Louis XI',role:'French terms · near Picquigny',where:'France',tag:'THE OFFER OF PEACE',
  q:['My master offers payment, security for merchants, and an end to needless marching. He will not say that he fears you. He will say that he values a neighbour who knows the price of peace.','The Duke of Burgundy has promised more than his men have delivered, so my master believes. Will you stake the kingdom’s credit upon an ally’s arrival, or put a sum upon peace?'],
  ctx:'Edward historically negotiated the Treaty of Picquigny in 1475. This is an alternate negotiation; no payment arrives unless the player accepts enforceable terms.',
  l:'Negotiate peace with scheduled payments.',r:'Continue preparations for armed pressure.',
  le:{credit:3,authority:1,people:{burgundy:{grievance:2}},flags:{frenchSettlement:'payments'},report:'The French offer a schedule of payments; the first instalment is promised, not yet witnessed.'},
  re:{credit:-2,people:{burgundy:{trust:1}},unrest:{Calais:1},flags:{frenchSettlement:'campaign'},report:'The captains prepare to march. Merchants demand compensation for delayed convoys.'}},
 {id:'account',year:1477,who:'A royal treasurer',role:'Receipts from France and Calais',where:'Westminster',tag:'THE LEDGER AFTER PEACE',
  q:['The promised French receipts have improved our account, but the merchants ask whether the peace protects them as well as the king. I can pay a captain or forgive a duty, not both.','The campaign has consumed the credit pledged against the Staple. Our allies still speak of victory; our lenders speak of dates. Which obligation shall the Crown honour first?'],
  ctx:'The financial result is conditional on Edward’s earlier diplomacy, trade promises and military expenditure.',
  l:'Publish the accounts and pay verified obligations.',r:'Reserve funds for strategic patronage.',
  le:{credit:-1,authority:2,people:{london:{trust:1},burgundy:{grievance:1}},flags:{foreignAccount:'published'},report:'A public account is issued. Some creditors discover that their expected payment has been reduced.'},
  re:{credit:1,authority:-1,people:{london:{grievance:2},burgundy:{trust:1}},flags:{foreignAccount:'reserved'},report:'Royal officers retain a reserve for future service. The London lenders ask for a date.'}}
 ]},
 succession:{title:'THE BLOOD AND THE SEAL',start:1468,source:'https://www.cambridge.org/core/journals/historical-journal/article/abs/i-attainder-and-forfeiture-1453-to-15091/1EA8D0EFB954878797B941400045B969',anchor:'Clarence’s marriage and inheritance, the division of Neville estates, and Edward IV’s succession were major dynastic questions. Clarence was executed in 1478 in recorded history; the game does not force his fate.',lead:'woodville',beats:[
 {id:'brother',year:1468,who:'George, Duke of Clarence',role:'The king’s brother · Westminster',where:'Westminster',tag:'THE KING’S BROTHER',
  q:['I am your brother before I am your servant. The great lords offer marriage alliances, and every answer I give is said to threaten the Crown. Will you speak plainly of my place in your house?','You have a queen and new kin. I ask for lands and a household proper to my birth, not a promise to wait until all your children are grown.'],
  ctx:'Clarence has dynastic standing independent of the queen’s family. A marriage alliance could bind him to an ambitious magnate.',
  l:'Offer a recorded appanage with limits.',r:'Leave Clarence free to seek noble patronage.',
  le:{credit:-1,authority:1,people:{warwick:{grievance:1}},flags:{clarencePlace:'recorded'},report:'Clarence receives a limited royal income but asks whether it can be revoked.'},
  re:{authority:-1,people:{warwick:{influence:1}},flags:{clarencePlace:'independent'},report:'Clarence receives visitors from the Neville affinity without a royal officer present.'}},
 {id:'marriage',year:1469,who:'George, Duke of Clarence',role:'A proposed Neville marriage settlement',where:'Westminster',tag:'A PRINCE’S MARRIAGE',
  q:['A Neville bride would bring lands and a great kinship. I will not ask you to love the match, only to judge whether my marriage may be treated as treason before it is made.','The Earl of Warwick offers his daughter in marriage. Your servants call the proposal a faction. If it is a danger, give me an honourable alternative.'],
  ctx:'Clarence historically married Isabel Neville in 1469. This counterfactual proposal may be approved, constrained or redirected.',
  l:'Permit the match with an explicit loyalty oath.',r:'Withhold assent and propose a different settlement.',
  le:{authority:1,people:{warwick:{trust:1,influence:1}},flags:{clarenceMarriage:'neville'},report:'Clarence and the Neville household sign a loyalty undertaking. Its enforcement remains uncertain.'},
  re:{authority:1,people:{warwick:{grievance:2,trust:-1}},flags:{clarenceMarriage:'other'},report:'The match is refused. Clarence asks whether a brother’s marriage is subject to royal licence.'}},
 {id:'estates',year:1473,who:'A clerk of the royal Chancery',role:'Division of inherited lands',where:'Westminster',tag:'TWO BROTHERS, ONE INHERITANCE',
  q:['Clarence and Gloucester claim portions of the same inheritance. One presents a royal grant; the other produces a later promise. If I seal both, the sheriff will be ordered to dispossess himself.','Clarence asks for the lands you promised in place of the Neville marriage. Gloucester’s servants say the same estate was assigned to him already. Which instrument may the judges read?'],
  ctx:'The division of the Warwick and Neville inheritances between Clarence and Gloucester was historically contentious. Specific documents here are imagined.',
  l:'Require a judicial partition with written boundaries.',r:'Settle the estates through royal discretion.',
  le:{authority:2,credit:-1,people:{warwick:{grievance:1}},flags:{clarenceLands:'partition'},report:'Surveyors begin marking a division. Both princely households dispute the value of the parcels.'},
  re:{authority:-1,people:{woodville:{grievance:1}},flags:{clarenceLands:'favour'},report:'A royal grant settles possession for now; a rival household preserves its earlier claim.'}},
 {id:'charges',year:1477,who:'William Hastings',role:'A report on the king’s brother',where:'Westminster',tag:'THE ACCUSATION',
  q:['Men say Clarence has received oaths from servants who should answer to you. I have no sworn witness, only two letters with the same story. Shall I question their authors before the rumour becomes a charge?','A servant of Clarence has been arrested, and now the whole court speaks of treason. The testimony may be true or purchased. I ask leave to examine the seal before we accuse the prince.'],
  ctx:'Charges against Clarence became a grave political crisis in recorded history. In this timeline an allegation is not automatically proof.',
  l:'Order an independent inquiry with witnesses.',r:'Demand Clarence’s immediate submission.',
  le:{authority:2,credit:-1,flags:{clarenceCharge:'inquiry'},report:'Witnesses are summoned; the inquiry records contradictions in the first accounts.'},
  re:{authority:1,unrest:{Court:2},flags:{clarenceCharge:'summons'},report:'Clarence is summoned to answer. His retainers ask for assurances of safe conduct.'}},
 {id:'heir',year:1480,who:'A tutor of the royal household',role:'The prince’s education and protection',where:'Westminster',tag:'THE HEIR’S HOUSEHOLD',
  q:['The young prince must learn to govern men who now compete to guard his door. His mother asks for familiar attendants; the Council asks for officers owing service to the Crown. Whose names shall I enter?','A guardian may love the child and still seek the seal. Two houses have sent lists of attendants, each calling the other dangerous. I need an order that will survive a king’s absence.'],
  ctx:'If no heir is secure in this timeline, the same question concerns the succession settlement rather than a guaranteed historical prince.',
  l:'Divide education, custody and estate revenues.',r:'Concentrate guardianship in one trusted household.',
  le:{authority:2,people:{woodville:{grievance:1},hastings:{trust:1}},flags:{heirHousehold:'separated'},report:'Separate officers are appointed for the heir’s education, custody and revenues.'},
  re:{authority:-1,people:{woodville:{influence:1},hastings:{grievance:1}},flags:{heirHousehold:'united'},report:'One household receives the guardianship. Other counsellors ask who may remove its officers.'}},
 {id:'guardians',year:1482,who:'A clerk of the Council',role:'A sealed succession instrument',where:'Westminster',tag:'THE KING AFTER THE KING',
  q:['Your Grace, a regency can be named on parchment, but it will be made in corridors and at gates. If your heir is young, whose men will hold the Tower and whose officers the treasury?','The prince’s guardians have accepted their titles. They have not agreed which of them may summon soldiers or open the treasury. A succession instrument must answer those questions now.'],
  ctx:'The 1483 crisis is not scripted. The distribution of force, guardianship, revenues and trust shapes the later epilogue.',
  l:'Bind the succession to a recorded Council settlement.',r:'Entrust the transition to a single household.',
  le:{authority:2,people:{hastings:{trust:1},woodville:{grievance:1}},flags:{successionInstrument:'council'},report:'The Council witnesses a succession settlement. Several households seek clarifications.'},
  re:{authority:-2,people:{woodville:{influence:2},hastings:{grievance:1}},flags:{successionInstrument:'household'},report:'One household receives broad guardianship; rival officers quietly retain copies of older warrants.'}}
 ]}
};
