const fs=require('fs'),vm=require('vm'),assert=require('assert');
const c={console,Math,EDWARD_SIMULATION:true,localStorage:{getItem(){return null},setItem(){},removeItem(){}}};vm.createContext(c);
const files=['data','reactive','emergent','sandbox','deepworld','narrative','story_scenes','story_crossovers','story_engine','delayed','engine','world_pressure','historical_world','living_court'];for(const f of files)vm.runInContext(fs.readFileSync(__dirname+'/'+f+'.js','utf8'),c,{filename:f});
vm.runInContext('this.api={newWorld,getNextSituation,resolveChoice,CHAPTERS,lcInit,lcIssue,lcProcess,lcMeeting,lcRespond,lcAppoint,lcDismiss,lcSeat,lcMembers,lcCouncilView,lcAlive,edwardHistoryAudit,lcVoiceCard}',c);
const A=c.api;function start(seed=10){const s=A.newWorld(seed);s.chapterIndex=A.CHAPTERS.length;s.facts.marriage='elizabeth';s.offices.chamberlain='hastings';A.getNextSituation(s);A.lcInit(s);return s;}
function reply(s,kind='audience',target='warwick',topic='appointments'){const id=A.lcIssue(s,kind,target,topic);s.court.clock+=5;A.lcProcess(s);return id;}
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
check('legacy save migrates without changing original state',()=>{const s=A.newWorld(12),before=JSON.stringify(s);A.lcInit(s);const copy=JSON.parse(JSON.stringify(s));delete copy.court;assert.equal(JSON.stringify(copy),before);assert.equal(s.version,10);});
check('appointment and dismissal change offices and grievances',()=>{const s=start();A.lcAppoint(s,'chancellor','stillington');assert.equal(s.offices.chancellor,'stillington');assert(s.court.people.george.grievance>=2);A.lcDismiss(s,'chancellor');assert.equal(s.offices.chancellor,'unassigned');assert.throws(()=>A.lcAppoint(s,'chancellor','warwick'));});
check('death guard excludes George and prevents appointments',()=>{const s=start();s.sandbox.year=1476;assert(!A.lcAlive(s,'george'));assert(!A.lcMembers(s).includes('george'));assert.throws(()=>A.lcAppoint(s,'chancellor','george'));});
check('summons travel, delay and refusal are distinct',()=>{const s=start();let id=A.lcIssue(s,'summon','warwick');assert(!A.lcMeeting(s,id));s.court.clock+=4;A.lcProcess(s);assert(A.lcMeeting(s,id));const t=start();t.sandbox.actors.warwick.trust=-2;id=A.lcIssue(t,'audience','warwick');t.court.clock+=4;A.lcProcess(t);assert(!A.lcMeeting(t,id));t.court.clock+=3;A.lcProcess(t);assert(A.lcMeeting(t,id));const u=start();u.sandbox.actors.warwick.grievance=6;u.sandbox.actors.warwick.influence=5;id=reply(u);assert.equal(u.court.orders.find(o=>o.id===id).status,'refused');});
check('meeting reacts to relationship, evidence and saved memory',()=>{const s=start(),id=reply(s);const first=A.lcMeeting(s,id).line;A.lcRespond(s,id,'question');assert(A.lcMeeting(s,id).evidence);assert.notEqual(A.lcMeeting(s,id).line,first);const t=JSON.parse(JSON.stringify(s));assert.deepEqual(A.lcMeeting(t,id),A.lcMeeting(s,id));A.lcRespond(t,id,'reassure');assert(t.characterMemory.warwick.length);assert.throws(()=>A.lcRespond(t,id,'reassure'));});
check('promises expire or are fulfilled with different consequences',()=>{const s=start(),id=reply(s);A.lcRespond(s,id,'promise');s.court.clock+=6;A.lcProcess(s);assert.equal(s.court.promises[0].status,'broken');assert(s.sandbox.actors.warwick.grievance>=2);const t=start(),i=reply(t);A.lcRespond(t,i,'promise');const j=A.lcIssue(t,'audience','warwick');t.court.clock+=2;A.lcProcess(t);A.lcRespond(t,j,'settle');assert.equal(t.court.promises[0].status,'kept');});
check('council composition changes advice',()=>{const s=start();const before=A.lcCouncilView(s,'appointments').map(x=>x.id);A.lcSeat(s,'george',false);A.lcSeat(s,'stillington',true);const after=A.lcCouncilView(s,'appointments').map(x=>x.id);assert(before.includes('george'));assert(!after.includes('george'));assert(after.includes('stillington'));});
check('initiatives cannot be spammed for free influence',()=>{const s=start();for(let i=0;i<8;i++)A.lcIssue(s,'messenger','hastings');assert.throws(()=>A.lcIssue(s,'messenger','hastings'));assert.equal(s.court.spent[1465],8);assert.equal(s.court.purse,4);});
check('hostile actors independently gather support',()=>{const s=start();s.sandbox.actors.warwick.grievance=5;s.sandbox.actors.warwick.influence=4;s.court.clock=10;A.lcProcess(s);assert(s.agentActions.some(a=>a.actor==='warwick'));assert(s.pending.some(x=>x.id.startsWith('court-coalition-')));});
check('pre-1465 court grievances persist into sandbox',()=>{const s=A.newWorld(19);A.lcDismiss(s,'captain_calais');assert(s.court.people.warwick.grievance>=2);s.chapterIndex=A.CHAPTERS.length;A.getNextSituation(s);assert(s.sandbox.actors.warwick.grievance>=2);});
check('appointments can break an explicit prior-hearing pledge',()=>{const s=start(),id=reply(s);A.lcRespond(s,id,'promise');A.lcAppoint(s,'chancellor','stillington');assert.equal(s.court.promises[0].status,'broken');});
check('council delegation returns an inquiry rather than a passive bonus',()=>{const s=start(),id=A.lcIssue(s,'council',null,'appointments');A.lcRespond(s,id,'delegate');assert(s.court.orders.some(o=>o.kind==='investigate'));s.court.clock+=5;A.lcProcess(s);assert(s.court.audiences.some(m=>m.kind==='investigate'&&m.evidence));});
check('Crown land lease is bounded and persisted',()=>{const s=start(),id=reply(s,'patronage','hastings','land');A.lcRespond(s,id,'settle');assert.equal(s.court.demesneLease.holder,'hastings');assert.equal(JSON.parse(JSON.stringify(s)).facts.court_demesne_lessee,'hastings');});
const out={checks:0,runs:0,failures:[],pairs:0,differentWorlds:0,differentEventSequences:0,convergentExamples:[],browser:'Not run: browser-control capability unavailable; physical iPhone Safari unverified.'};
function run(seed,policy){const s=start(seed),seen=[];let card=A.getNextSituation(s),guard=0,lastYear=0;while(card&&guard++<300){const y=s.sandbox.year;if(y!==lastYear){lastYear=y;const target=policy==='conciliation'?'warwick':'hastings';try{A.lcIssue(s,'audience',target,'appointments');}catch(e){}}
 const meeting=s.court.audiences.find(m=>m.status==='open');if(meeting)try{A.lcRespond(s,meeting.id,policy==='conciliation'?'settle':'threaten');}catch(e){}
 seen.push(JSON.stringify({story:card.storyInfo?{id:card.storyInfo.id,step:card.storyInfo.step}:null,pressure:card.pressureInfo||null,who:card.who,tag:card.tag,quote:typeof card.quote==='function'?card.quote(s):card.quote}));card=A.resolveChoice(s,card,seed%2?'left':'right',null);if(guard%9===0){const clone=JSON.parse(JSON.stringify(s));assert.deepEqual(A.lcInit(clone),s.court);}}
 assert(s.finished);assert(guard<300);assert.equal(A.edwardHistoryAudit(s).length,0);return {s,seen};}
for(let i=0;i<120;i++){try{const a=run(9100+i,'conciliation'),b=run(9100+i,'coercion');out.runs+=2;out.pairs++;if(JSON.stringify(a.s.sandbox.actors)!==JSON.stringify(b.s.sandbox.actors))out.differentWorlds++;if(a.seen.join('|')!==b.seen.join('|'))out.differentEventSequences++;else if(out.convergentExamples.length<5)out.convergentExamples.push({seed:9100+i,reason:'Authored event sequence remains identical despite different court policy.'});}catch(e){out.failures.push({seed:9100+i,error:String(e.stack)});break;}}
for(let seed=0;seed<40;seed++){try{let s=A.newWorld(seed),card=A.getNextSituation(s),n=0;while(card&&n++<300){card=A.resolveChoice(s,card,seed%2?'left':'right',null);}assert(s.finished&&n<300);assert.equal(A.edwardHistoryAudit(s).length,0);out.runs++;}catch(e){out.failures.push({seed,phase:'full-reign',error:String(e.stack)});}}
out.fullReignsFrom1461=40;out.checks=checks;fs.writeFileSync(__dirname+'/living_court_audit.json',JSON.stringify(out,null,2));console.log(out);if(out.failures.length)process.exitCode=1;
