/* Mobile-first card interface. Choice actions have no buttons: drag left/right/up/down. */
const app=document.getElementById('app');
const overlay=document.getElementById('overlay');
const sheet=document.getElementById('sheet');
const QA=new URLSearchParams(location.search).has('qa');
const LOCK_MS=QA?0:5000;
let world=loadWorld()||newWorld();let current=null,arena=null,locked=true,lockStart=0,lockRAF=0,activePointer=null,closing=false;
function E(s){return String(s===undefined||s===null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function intro(){cancelAnimationFrame(lockRAF);app.innerHTML=`<div class="intro" id="intro"><div class="ornament">✦</div><h1>EDWARD<span>IV</span></h1><p>England, 1461.<br>History is the starting point.<br>What remains is yours.</p><div class="enter" id="beginFull">TOUCH TO BEGIN · 1461</div><div class="enter" id="jump1465" style="margin-top:12px">ENTER THE LIVING WORLD · 1465</div><small>Swipe decisions · 96 early situations + historical dossiers + living-world continuation · 1461–1483</small></div>`;document.getElementById('beginFull').addEventListener('click',e=>{e.stopPropagation();begin()},{once:true});document.getElementById('jump1465').addEventListener('click',e=>{e.stopPropagation();world=newWorld();world.chapterIndex=CHAPTERS.length;world.facts.marriage='elizabeth';world.facts.somerset_1464='rebels';world.facts.north_rising_1464='active';world.offices.northern_commission='warwick';world.offices.chamberlain='hastings';world.links.warwick=3;world.links.hastings=2;world.links.woodville=2;saveWorld(world);begin()},{once:true});}
function begin(){if(closing)return;current=getNextSituation(world);if(!current)return ending();renderCard();}
function frame(body,top){return `<div class="header"><div class="logo">EDWARD <em>IV</em></div><div class="topinfo">${E(top||CHAPTERS[world.chapterIndex]?.date||(world.sandbox?String(world.sandbox.year):'1461–1483'))}<br>${E(CHAPTERS[world.chapterIndex]?.name||(world.sandbox?'The living reign':'A reign in the making'))}</div><button class="history-icon" id="historyIcon" aria-label="Historical record">◌</button></div>${body}<div class="nav"><button data-view="realm">Realm</button><button data-view="people">People</button><button data-view="council">Council</button><button data-view="chronicle">Chronicle</button><button data-view="cases">Cases</button></div>`;}
function renderCard(){if(!current)return ending();cancelAnimationFrame(lockRAF);locked=true;lockStart=performance.now();closing=false;
 const n=current;const detail=arena?n[arena]:null;const who=detail?detail.who:n.who;const role=detail?detail.role:n.role;const quote=detail?detail.quote:fmt(n.quote,world);const context=detail?'You have changed who hears this matter. A decision is still required.':fmt(n.context,world);
 const hasUp=!arena&&!!n.up,hasDown=!arena&&!!n.down;const latest=world.reports.slice(-1)[0];
 const body=`<div class="deck"><div class="shadow-card"></div><article class="card" id="card" aria-label="Drag left or right to decide"><div class="card-top"><span>${E(n.where)} · ${E(n.when)}</span><span>${String(world.turn+1).padStart(2,'0')} · ${E(n.tag||'THE CROWN')}</span></div>${arena?`<div class="arena-badge">${arena==='up'?'THE INSTITUTIONAL ARENA':'THE PRIVATE ARENA'} · ${E(detail.title)}</div>`:`<div class="kicker">${E(n.storyInfo?'AN UNFOLDING CHRONICLE · PART '+n.storyInfo.step+'/'+n.storyInfo.total:n.caseInfo?'A HISTORICAL DOSSIER':CHAPTERS[world.chapterIndex]?.name||'THE LIVING REIGN')}</div>`}<div class="speaker">${E(who)}</div><div class="role">${E(role)}</div><div class="rule"></div><blockquote class="quote">“${E(quote)}”</blockquote><div class="context"><b>What Edward knows</b>${E(context)}${latest&&world.turn-latest.turn<=2?`<div class="quiet-report">LATEST REPORT · ${E(latest.from)}: ${E(latest.text)}</div>`:''}</div><div class="choice-chip left" id="chipLeft"></div><div class="choice-chip right" id="chipRight"></div>${hasUp?'<div class="choice-chip up" id="chipUp"></div>':''}${hasDown?'<div class="choice-chip down" id="chipDown"></div>':''}</article></div><div class="locktrack"><i id="lockfill"></i></div><div class="help" id="help">READ THE CARD · THE DECISION WILL RELEASE</div>`;
 app.innerHTML=frame(body);document.getElementById('chipLeft').textContent=(detail||n).left.label;document.getElementById('chipRight').textContent=(detail||n).right.label;
 if(hasUp)document.getElementById('chipUp').textContent='↑ '+n.up.title;if(hasDown)document.getElementById('chipDown').textContent='↓ '+n.down.title;
 bindNav();document.getElementById('historyIcon').onclick=showHistory;bindDrag(document.getElementById('card'),hasUp,hasDown);tickLock(hasUp,hasDown);
}
function tickLock(hasUp,hasDown){const fill=document.getElementById('lockfill'),hint=document.getElementById('help');function update(now){const p=LOCK_MS===0?1:Math.min(1,(now-lockStart)/LOCK_MS);if(fill)fill.style.width=(p*100)+'%';if(p>=1){locked=false;if(hint)hint.innerHTML=`DRAG <strong>← / →</strong> TO DECIDE${hasUp?' · <strong>↑</strong> COUNCIL':''}${hasDown?' · <strong>↓</strong> PRIVATE':''}`;return}lockRAF=requestAnimationFrame(update)}lockRAF=requestAnimationFrame(update);}
function bindNav(){app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showPanel(b.dataset.view));}
function bindDrag(card,hasUp,hasDown){card.addEventListener('pointerdown',e=>{if(closing||overlay.classList.contains('open'))return;activePointer={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0,dy:0,time:performance.now(),lastX:e.clientX,lastY:e.clientY,lastT:performance.now(),vx:0,vy:0};try{card.setPointerCapture(e.pointerId)}catch(err){}card.classList.add('dragging')});
 card.addEventListener('pointermove',e=>{const p=activePointer;if(!p||p.id!==e.pointerId)return;const now=performance.now();const dt=Math.max(8,now-p.lastT);p.vx=(e.clientX-p.lastX)/dt;p.vy=(e.clientY-p.lastY)/dt;p.lastX=e.clientX;p.lastY=e.clientY;p.lastT=now;p.dx=e.clientX-p.x;p.dy=e.clientY-p.y;let x=p.dx,y=p.dy;if(locked){x*=.14;y*=.14}else if(y>0&&!hasDown)y*=.16;else if(y<0&&!hasUp)y*=.16;const rotate=x*.034;card.style.transform=`translate3d(${x}px,${y}px,0) rotate(${rotate}deg)`;showChip(x,y,hasUp,hasDown)});
 card.addEventListener('pointerup',e=>release(card,e,hasUp,hasDown));card.addEventListener('pointercancel',()=>spring(card));card.addEventListener('lostpointercapture',()=>{if(activePointer){activePointer=null;spring(card)}});
}
function showChip(dx,dy,hasUp,hasDown){['chipLeft','chipRight','chipUp','chipDown'].forEach(id=>document.getElementById(id)?.classList.remove('on'));if(locked)return;let id='';if(Math.abs(dx)>Math.abs(dy)*.8&&Math.abs(dx)>28)id=dx<0?'chipLeft':'chipRight';else if(dy<-30&&hasUp)id='chipUp';else if(dy>30&&hasDown)id='chipDown';if(id)document.getElementById(id)?.classList.add('on');}
function release(card,e,hasUp,hasDown){const p=activePointer;if(!p||e.pointerId!==p.id)return;activePointer=null;card.classList.remove('dragging');if(locked)return spring(card);const dx=p.dx,dy=p.dy;const sideways=Math.abs(dx)>Math.abs(dy)*.75;const vert=Math.abs(dy)>Math.abs(dx)*.75;
 if(vert&&dy<-(Math.abs(p.vy)>.7?50:85)&&hasUp)return fly(card,0,-innerHeight,()=>enterArena('up'));
 if(vert&&dy>(Math.abs(p.vy)>.7?50:85)&&hasDown)return fly(card,0,innerHeight,()=>enterArena('down'));
 if(sideways&&Math.abs(dx)>(Math.abs(p.vx)>.7?50:92))return fly(card,dx<0?-innerWidth:innerWidth,dy*.22,()=>decide(dx<0?'left':'right'));
 spring(card);
}
function spring(card){if(!card)return;card.classList.remove('dragging');card.style.transform='translate3d(0,0,0) rotate(0deg)';['chipLeft','chipRight','chipUp','chipDown'].forEach(id=>document.getElementById(id)?.classList.remove('on'));}
function fly(card,x,y,done){closing=true;card.style.transition='transform .28s cubic-bezier(.3,.05,.75,.4),opacity .24s';card.style.transform=`translate3d(${x}px,${y}px,0) rotate(${x*.015}deg)`;card.style.opacity='0';setTimeout(done,275);}
function enterArena(which){arena=which;renderCard();}
function decide(side){resolveChoice(world,current,side,arena);arena=null;current=getNextSituation(world);if(current)renderCard();else ending();}
function openSheet(title,body){sheet.innerHTML=`<div class="sheethead"><h2>${E(title)}</h2><button class="close" id="closeSheet" aria-label="Close">×</button></div>${body}`;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.getElementById('closeSheet').onclick=closeSheet;}
function closeSheet(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');}
overlay.addEventListener('click',e=>{if(e.target===overlay)closeSheet()});
function showHistory(){if(!current)return;const [fact,url]=current.caseInfo?[current.caseInfo.anchor,current.caseInfo.source]:current.dynamic?['This is a fictionalized situation generated from the simulation’s people, interests, and earlier decisions. It is not a documented event or quotation.','https://www.cambridge.org/core/books/wars-of-the-roses/']:(HIST[current.record]||HIST.politics);openSheet('Historical record',`<div class="eyebrow">${E(current.tag)} · ${E(current.when)}</div><p>${E(fact)}</p><div class="row"><b>Reconstruction</b><span>The card’s conversation and player alternatives are dramatized. A documented event is not necessarily a compulsory outcome in this timeline.</span></div><p><a target="_blank" rel="noopener noreferrer" href="${E(url)}">Research reference ↗</a></p>`);}
function showPanel(which){if(which==='realm')return showRealm();if(which==='people')return showPeople();if(which==='council')return showCouncil();if(which==='chronicle')return showChronicle();if(which==='cases')return showCases();}
function showRealm(){const north=world.facts.north_rising_1464==='averted'?'A negotiated northern settlement has averted the expected field campaign in this reign.':world.visited.includes('hexham')?'The northern campaign has been fought; local authority still requires settlement.':world.visited.includes('scots_border')?'Border activity and northern Lancastrian resistance reported.':'Reports from the North remain incomplete.';
 const york=world.facts.york_oath==='public'?'York has publicly sworn obedience.':world.visited.includes('york_oath')?'York welcomed Edward without a new public oath.':'No fresh civic report.';
 const calais=world.visited.includes('calais')?`Supply arranged through ${world.facts.calais_supply==='audited'?'royal auditors':'Warwick’s administration'}.`:'Warwick holds the captaincy; no recent supply report.';
 const recent=world.reports.slice(-4).reverse();
 openSheet('Realm',`<div class="eyebrow">SCHEMATIC · EDWARD’S REPORTS, NOT OMNISCIENCE</div><svg class="map-svg" viewBox="0 0 330 310" role="img" aria-label="Schematic locations in and around England"><path d="M139 18 L179 30 191 69 180 90 198 117 177 141 187 177 171 213 179 243 161 280 130 272 139 235 117 210 131 179 112 149 125 122 115 91 127 63Z"/><path d="M134 5 L175 13 189 25 178 38 139 25Z" fill="#4d4c3f"/><path d="M97 245 L126 253 112 283 90 270Z"/><circle cx="151" cy="105" r="4"/><text x="164" y="108">North</text><circle cx="147" cy="151" r="4"/><text x="160" y="154">York</text><circle cx="151" cy="230" r="4"/><text x="164" y="233">London</text><circle cx="106" cy="271" r="4"/><text x="11" y="299">Calais</text><text x="194" y="26">Scotland</text><text x="203" y="278" font-size="10">NOT TO SCALE</text></svg><div class="row"><b>Northumberland</b><span>${E(north)}</span></div><div class="row"><b>York</b><span>${E(york)}</span></div><div class="row"><b>Westminster / London</b><span>${world.visited.includes('parliament')?'The new regime has brought its settlement to Parliament.':'The royal household and government are forming.'}</span></div><div class="row"><b>Calais</b><span>${E(calais)}</span></div><div class="eyebrow" style="margin-top:18px">REPORTS REACHING THE KING</div>${recent.length?recent.map(r=>`<div class="row"><b>${E(r.from)}</b><span>${E(r.text)} · ${E(r.certainty)}</span></div>`).join(''):'<p>No courier reports yet.</p>'}<p><small>Reports may be delayed, mistaken, or incomplete. This map is not a territorial survey.</small></p>`);
}
function showPeople(){const marriage=world.facts.marriage==='elizabeth'?'Royal marriage':world.facts.marriage==='foreign'?'Foreign marriage policy':'Woodville family';const warwickRole=world.offices.northern_commission==='unassigned'?'Captain of Calais':`Captain of Calais · ${world.offices.northern_commission.replaceAll('_',' ')} in the North`;
 const people=[['Warwick',warwickRole,'Neville affinity'],['George Neville','Chancellor · Warwick’s brother','Neville affinity'],['John Neville','Lord Montagu · Warwick’s brother','Neville affinity'],['William Hastings',world.offices.chamberlain==='hastings'?'Lord Chamberlain':'Royal household','Household'],['Elizabeth Woodville',marriage,'Woodville family'],['Henry Beaufort',world.facts.somerset==='pardoned'?'Received into the king’s peace':world.facts.somerset==='excluded'?'Outside Edward’s favour':'Duke of Somerset','Lancastrian affinity'],['Henry VI','Lancastrian claimant','House of Lancaster']];
 const positions={Edward:[164,30],Warwick:[68,95],George:[47,167],Montagu:[110,201],Hastings:[265,96],Elizabeth:[267,174],Somerset:[171,225]};
 const edge=(a,b,dashed=false)=>`<line x1="${positions[a][0]}" y1="${positions[a][1]}" x2="${positions[b][0]}" y2="${positions[b][1]}" ${dashed?'stroke-dasharray="4 4"':''}/>`;
 const dot=(name,cls='')=>{const [x,y]=positions[name];return `<circle class="${cls}" cx="${x}" cy="${y}" r="21"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="10">${name==='Elizabeth'?'Eliz.':name}</text>`};
 const networks=politicalNetworks(world);const live=world.sandbox?Object.entries(world.sandbox.actors).map(([id,a])=>{const name=SANDBOX_ACTORS[id].name;const report=world.reports.slice().reverse().find(r=>r.from===name||r.text.includes(name));return `<div class="row"><b>${E(name)}</b><span>${E(SANDBOX_ACTORS[id].family)} · ${report?E(report.text):'No recent verified report'}</span></div>`;}).join(''):'';
 openSheet('People',`<div class="eyebrow">RELATIONSHIPS · PUBLIC AND KNOWN</div><svg class="network-svg" viewBox="0 0 330 257" role="img" aria-label="Political relationship network">${edge('Edward','Warwick')}${edge('Warwick','George')}${edge('Warwick','Montagu')}${edge('Edward','Hastings')}${edge('Edward','Elizabeth',true)}${edge('Edward','Somerset',true)}${Object.keys(positions).map(k=>dot(k,k==='Edward'?'crown':k==='Elizabeth'?'wood':k==='Somerset'?'lanc':'')).join('')}</svg><div class="eyebrow" style="margin:12px 0">POLITICAL NETWORKS</div>${Object.entries(networks).map(([name,detail])=>`<div class="row"><b>${E(name)}</b><span>${E(detail.description)}</span></div>`).join('')}${world.sandbox?'<div class="eyebrow">HOUSEHOLDS IN THE LIVING REIGN · PUBLIC INFORMATION ONLY</div>'+live:''}${people.map(p=>`<div class="row"><b>${E(p[0])}</b><span>${E(p[1])} · ${E(p[2])}</span></div>`).join('')}<p><small>Solid links show established service or kinship; dashed links indicate contingent political ties. This network is a simplified representation, not a loyalty meter.</small></p>`);
}
function showCouncil(){const officeRows=[['The Crown','Edward IV'],['Chancellor',world.offices.chancellor==='george'?'George Neville':'Unassigned'],['Lord Chamberlain',world.offices.chamberlain==='hastings'?'William Hastings':'Not yet appointed'],['Captain of Calais','Richard Neville, Earl of Warwick'],['Northern commission',world.offices.northern_commission.replaceAll('_',' ')]];
 const obligations=world.obligations.filter(o=>o.visibility!=='private'||o.from==='edward'||o.to==='edward').slice(-6).reverse();openSheet('Council',`<div class="eyebrow">OFFICES · DELEGATED AUTHORITY</div>${officeRows.map(r=>`<div class="row"><b>${E(r[0])}</b><span>${E(r[1])}</span></div>`).join('')}<div class="eyebrow" style="margin-top:18px">RECENT OBLIGATIONS</div>${obligations.length?obligations.map(o=>`<div class="row"><b>${E(o.from)} → ${E(o.to)}</b><span>${E(o.reason)} · ${E(o.visibility)}</span></div>`).join(''):'<p>No recorded obligations yet.</p>'}<p><small>Not every private promise is known to every councillor. These are obligations Edward has personally created or heard.</small></p>`);
}
function showChronicle(){const items=world.chronicle.slice().reverse();openSheet('Chronicle',`<div class="eyebrow">YOUR REIGN · ${world.turn} DECISIONS</div>${items.length?items.map(e=>`<div class="row"><div class="eyebrow">${E(e.chapter)} · ${E(e.place)}</div><b>${E(e.summary)}</b><span>${E(e.arena==='direct'?'Decision':'Through '+(e.arena==='up'?'Council':'a private audience'))}</span></div>`).join(''):'<p>Nothing has yet been entered in your Chronicle.</p>'}<div class="eyebrow" style="margin-top:20px">MESSAGES RECEIVED</div>${world.reports.slice(-6).reverse().map(r=>`<div class="row"><b>${E(r.from)}</b><span>${E(r.text)}</span></div>`).join('')||'<p>Nothing reported yet.</p>'}<div class="eyebrow" style="margin-top:20px">HISTORICAL DOSSIERS</div>${(world.sandbox?.narrative?.journal||[]).slice(-12).reverse().map(j=>`<div class="row"><b>${E(ND_CASES[j.key]?.title||j.key)} · ${E(j.year)}</b><span>${E(j.stage==='echo'?'The earlier decision returned.':'The case entered your reign.')} ${E(j.summary)}</span></div>`).join('')||'<p>No historical dossiers have yet been heard.</p>'}<div class="eyebrow" style="margin-top:20px">PRECEDENTS</div>${world.precedents.length?world.precedents.slice(-7).reverse().map(p=>`<div class="row"><span>${E(p.text)}</span></div>`).join(''):'<p>No precedents recorded yet.</p>'}<button class="reset-link" id="newReign">Begin a new reign</button>`);document.getElementById('newReign').onclick=()=>{if(confirm('Erase this reign and begin again?')){clearWorld();world=newWorld();current=null;arena=null;closeSheet();intro()}};}
function ending(){cancelAnimationFrame(lockRAF);const outcome=world.sandbox?.endings?{title:world.sandbox.endings.label,text:world.sandbox.endings.narrative}:chapterOutcome(world);const last=world.chronicle.slice(-3).map(x=>x.summary);app.innerHTML=`<div class="outro" id="outro"><div class="chaptertag">END OF THE DEMO · 1483</div><h1>${E(outcome.title)}</h1><p>${E(outcome.text)}</p><p>${world.sandbox?.endings?'Edward’s rule has ended. The world continues into an uncertain succession. The political configuration is recorded below.':'Edward is still king. The next decade remains unwritten.'}</p>${world.sandbox?.endings?.afterworld?'<div class="eyebrow">THE WORLD WITHOUT EDWARD</div>'+world.sandbox.endings.afterworld.map(x=>'<div class="row"><b>'+E(x.year)+'</b><span>'+E(x.text)+'</span></div>').join(''):''}<div class="eyebrow">THE LAST ENTRIES</div>${last.map(x=>`<div class="row"><span>${E(x)}</span></div>`).join('')}<div class="enter">TOUCH TO BEGIN ANOTHER REIGN</div></div>`;document.getElementById('outro').onclick=()=>{clearWorld();world=newWorld();intro()};}
if(QA){window.EDWARD_TEST={get state(){return world},get card(){return current},get arena(){return arena},get networks(){return politicalNetworks(world)},choose(side){if(current)decide(side)},open(which){if(current&&current[which])enterArena(which)},reset(seed=123){world=newWorld(seed);current=getNextSituation(world);arena=null;renderCard()},advance(){current=getNextSituation(world);renderCard()}};}
window.addEventListener('keydown',e=>{if(overlay.classList.contains('open')){if(e.key==='Escape')closeSheet();return}if(!current){if(e.key==='Enter')begin();return}if(locked||closing)return;const k={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(!k)return;e.preventDefault();if(k==='up'||k==='down'){if(!arena&&current[k])enterArena(k)}else decide(k)});
window.addEventListener('error',e=>{if(!app.querySelector('.card')){app.innerHTML='<div class="intro"><h1>EDWARD</h1><p>The game could not start in this viewer. Open the HTML file in a full browser.</p></div>'}console.error(e.message)});
/* Startup is now handled by the title screen, without advancing an existing autosave. */
intro();
function showCases(){const n=world.sandbox?.narrative;const journal=n?.journal||[];
 const cases=[...new Set(journal.map(j=>j.key))].reverse();
 const rows=cases.map(key=>{const d=ND_CASES[key],entries=journal.filter(j=>j.key===key),latest=entries[entries.length-1],first=entries[0];return `<div class="row"><div class="eyebrow">${E(first.year)} · ${entries.length>1?'A CONSEQUENCE RETURNED':'AWAITING CONSEQUENCES'}</div><b>${E(d.title)}</b><span>${E(latest.summary)}</span><span>Historical context: ${E(d.anchor)}</span><span><a href="${E(d.source)}" target="_blank" rel="noopener noreferrer">Research reference ↗</a></span></div>`;}).join('');
 openSheet('The King’s Dossiers',`<p>Political cases that entered this reign. Historical disputes are documented; the dialogue, royal choices and alternate outcomes are reconstructions.</p>${rows||'<p>Historical dossiers will appear as the reign develops.</p>'}`);
}
/* Deep-world inspector: only public property and information known to Edward. */
const _dwRealmPanel=showRealm;
showRealm=function(){_dwRealmPanel();if(!world.sandbox?.deep)return;const d=world.sandbox.deep;
 const rows=d.lands.map(l=>`<div class="row"><b>${E(l.name)} · ${E(l.region)}</b><span>Recorded holder: ${E(SANDBOX_ACTORS[l.holder]?.name||l.holder)}${l.disputed?' · title contested':''}${l.transfers.length?' · transfer entered in Chronicle':''}</span></div>`).join('');
 sheet.insertAdjacentHTML('beforeend',`<div class="eyebrow" style="margin-top:20px">LANDS AND CLAIMS · RECORDED, NOT OMNISCIENT</div>${rows}<p><small>These estates are fictional test cases; holdings are public legal positions, not guaranteed truth about every claimant's rights.</small></p>`);
};
const _dwPeoplePanel=showPeople;
showPeople=function(){_dwPeoplePanel();if(!world.sandbox?.deep)return;const d=world.sandbox.deep;
 const bonds=d.bonds.filter(b=>b.public).slice(-6).reverse();
 const items=bonds.map(b=>`<div class="row"><b>${E(SANDBOX_ACTORS[b.a]?.name||b.a)} — ${E(SANDBOX_ACTORS[b.b]?.name||b.b)}</b><span>${E(b.kind)} · ${E(b.year)}</span></div>`).join('');
 sheet.insertAdjacentHTML('beforeend',`<div class="eyebrow" style="margin-top:20px">RECORDED LINKS IN THIS REIGN</div>${items||'<p>No new public ties recorded yet.</p>'}<p><small>Private arrangements unknown to the Crown are intentionally omitted.</small></p>`);
};
const _dwCouncilPanel=showCouncil;
showCouncil=function(){_dwCouncilPanel();if(!world.sandbox?.deep)return;const d=world.sandbox.deep;
 const claims=Object.entries(d.officeClaims).slice(-6).reverse().map(([id,x])=>`<div class="row"><b>${E(id)}</b><span>${E(typeof x==='string'?x:x.review?'Under review':'Royal warrant in favour of '+(SANDBOX_ACTORS[x.appointee]?.name||x.appointee))}</span></div>`).join('');
 sheet.insertAdjacentHTML('beforeend',`<div class="eyebrow" style="margin-top:20px">APPOINTMENTS AND JURISDICTION</div>${claims||'<p>No new contested appointment recorded.</p>'}`);
};
const _dwChroniclePanel=showChronicle;
showChronicle=function(){_dwChroniclePanel();if(!world.sandbox?.deep)return;const d=world.sandbox.deep;
 const known=d.knowledge.edward.slice(-8).reverse().map(k=>`<div class="row"><b>${E(k.certainty.toUpperCase())} · ${E(k.source)}</b><span>${E(k.claim)}</span></div>`).join('');
 sheet.insertAdjacentHTML('beforeend',`<div class="eyebrow" style="margin-top:20px">WHAT REACHED EDWARD</div>${known||'<p>No separate intelligence entered yet.</p>'}<p><small>The world knows more than Edward. Allegations are not automatically facts.</small></p>`);
};
